{
  "hash": "b8c35cab9d41099d99ceadd8cf56d3eb",
  "result": {
    "markdown": "## Mixed effects models {.unnumbered}\n\nIn this section, we will learn about mixed effects models. Mixed effects models are popular choices for modeling repeated measurements, such as longitudinal or clustered data. Examples of longitudinal data include blood pressure measurements taken over time from the same individuals and CD4 count over time from the same individuals. Examples of clustered data include students within schools and patients within hospitals. There are two components in a mixed effects model: fixed effects and random effects:\n\n-   Fixed effects refer to general trends that are applicable to all subjects/clusters. This implies that we might want to investigate how students perform (on average) in different subjects such as math and history. These effects are commonly observed, i.e., fixed, across all schools.\n\n-   Random Effects capture the unique characteristics of each subject/cluster that differentiate them from one another. For instance, some schools may have better resources, more experienced teachers, or a more supportive learning environment. These differences are specific to each school, and we use random effects to capture them.\n\n\n\n::: {.cell hash='longitudinal1_cache/pdf/setup_794ac21c9c9977d770ba29f81bcaf243'}\n\n```{.r .cell-code}\n# Load required packages\nknitr::opts_chunk$set(echo = TRUE)\nrequire(kableExtra)\n```\n:::\n\n\n\n### Repeated measures\n\n::: column-margin\nA useful reference on repeated measures is Section 9.2 of @faraway2016extending.\n:::\n\nIn repeated measurement design, the response variable are measured multiple times for each individuals.\n\n### Linear Mixed Effects Models for Repeated Measures Data\n\n::: column-margin\nA useful reference on linear mixed effects models is Section 12.4 of @hothorn2014handbook.\n:::\n\n::: callout-important\n-   The linear mixed effect models are based on the idea that the correlation of an individual's responses depends on some unobserved individual characteristics.\n\n-   In linear mixed effect models, we treat these unobserved characteristics as random effects in our model. If we could conditional on the random effects, then the repeated measurements can be assumed to be independent.\n:::\n\n#### Data\n\nWe are going to use the `BtheB` dataset from the `HSAUR2` package to explain the linear mixed effect model:\n\n\n\n::: {.cell hash='longitudinal1_cache/pdf/load_b850b061b41c42bee5343b52204ee006'}\n\n```{.r .cell-code}\nlibrary(HSAUR2)\n#> Loading required package: tools\ndata(\"BtheB\")\nkable(head(BtheB))%>%\n  kable_styling(bootstrap_options = \"striped\", full_width = F, position = \"left\")\n```\n\n::: {.cell-output-display}\n\\begin{tabular}{l|l|l|r|r|r|r|r}\n\\hline\ndrug & length & treatment & bdi.pre & bdi.2m & bdi.3m & bdi.5m & bdi.8m\\\\\n\\hline\nNo & >6m & TAU & 29 & 2 & 2 & NA & NA\\\\\n\\hline\nYes & >6m & BtheB & 32 & 16 & 24 & 17 & 20\\\\\n\\hline\nYes & <6m & TAU & 25 & 20 & NA & NA & NA\\\\\n\\hline\nNo & >6m & BtheB & 21 & 17 & 16 & 10 & 9\\\\\n\\hline\nYes & >6m & BtheB & 26 & 23 & NA & NA & NA\\\\\n\\hline\nYes & <6m & BtheB & 7 & 0 & 0 & 0 & 0\\\\\n\\hline\n\\end{tabular}\n:::\n:::\n\n\n\n-   A typical form of repeated measurement data from a clinical trial data.\n\n-   The individuals are allocated to different treatments then the response Beck Depression Inventory II were taken at baseline, 2, 3, 5, and 8 months\n\n\n\n::: {.cell hash='longitudinal1_cache/pdf/data1_428b56a7e82ecf9180b6baf6c835ab57'}\n\n```{.r .cell-code}\n## Box-plot of responses at different time points in treatment and control groups\ndata(\"BtheB\", package = \"HSAUR2\")\nlayout(matrix(1:2, nrow = 1))\nylim <- range(BtheB[,grep(\"bdi\", names(BtheB))],na.rm = TRUE)\ntau <- subset(BtheB, treatment == \"TAU\")[, grep(\"bdi\", names(BtheB))]\nboxplot(tau, main = \"Treated as Usual\", ylab = \"BDI\",xlab = \"Time (in months)\", \n        names = c(0, 2, 3, 5, 8),ylim = ylim)\nbtheb <- subset(BtheB, treatment == \"BtheB\")[, grep(\"bdi\", names(BtheB))]\nboxplot(btheb, main = \"Beat the Blues\", ylab = \"BDI\",xlab = \"Time (in months)\", \n        names = c(0, 2, 3, 5, 8),ylim = ylim)\n```\n\n::: {.cell-output-display}\n![](longitudinal1_files/figure-pdf/data1-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n-   The side-by-side box plots show the distributions of BDI overtime between control (Treated as Usual) and intervention (Beat the Blues) groups.\n\n-   As time goes, drops in BDI are more obvious in intervention which may indicate the intervention is effective.\n\n#### Regular model fixed intercept and slope\n\nTo compare, we start with fixed effect linear model, i.e., a regular linear model without any random effect:\n\n\n\n::: {.cell hash='longitudinal1_cache/pdf/fixed_527e88a81c109b5947131480b6a698bf'}\n\n```{.r .cell-code}\n## To analyze the data, we first need to convert the dataset to a analysis-ready form\nBtheB$subject <- factor(rownames(BtheB))\nnobs <- nrow(BtheB)\nBtheB_long <- reshape(BtheB, idvar = \"subject\", varying = c(\"bdi.2m\", \"bdi.3m\", \"bdi.5m\", \"bdi.8m\"), \n                      direction = \"long\")\nBtheB_long$time <- rep(c(2, 3, 5, 8), rep(nobs, 4))\nkable(head(BtheB_long))%>%\n  kable_styling(bootstrap_options = \"striped\", full_width = F, position = \"left\")\n```\n\n::: {.cell-output-display}\n\\begin{tabular}{l|l|l|l|r|l|r|r}\n\\hline\n  & drug & length & treatment & bdi.pre & subject & time & bdi\\\\\n\\hline\n1.2m & No & >6m & TAU & 29 & 1 & 2 & 2\\\\\n\\hline\n2.2m & Yes & >6m & BtheB & 32 & 2 & 2 & 16\\\\\n\\hline\n3.2m & Yes & <6m & TAU & 25 & 3 & 2 & 20\\\\\n\\hline\n4.2m & No & >6m & BtheB & 21 & 4 & 2 & 17\\\\\n\\hline\n5.2m & Yes & >6m & BtheB & 26 & 5 & 2 & 23\\\\\n\\hline\n6.2m & Yes & <6m & BtheB & 7 & 6 & 2 & 0\\\\\n\\hline\n\\end{tabular}\n:::\n\n```{.r .cell-code}\nunique(BtheB_long$subject)\n#>   [1] 1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18 \n#>  [19] 19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36 \n#>  [37] 37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54 \n#>  [55] 55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72 \n#>  [73] 73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90 \n#>  [91] 91  92  93  94  95  96  97  98  99  100\n#> 100 Levels: 1 10 100 11 12 13 14 15 16 17 18 19 2 20 21 22 23 24 25 26 27 ... 99\nkable(subset(BtheB_long,  subject == 2))%>%\n  kable_styling(bootstrap_options = \"striped\", full_width = F, position = \"left\")\n```\n\n::: {.cell-output-display}\n\\begin{tabular}{l|l|l|l|r|l|r|r}\n\\hline\n  & drug & length & treatment & bdi.pre & subject & time & bdi\\\\\n\\hline\n2.2m & Yes & >6m & BtheB & 32 & 2 & 2 & 16\\\\\n\\hline\n2.3m & Yes & >6m & BtheB & 32 & 2 & 3 & 24\\\\\n\\hline\n2.5m & Yes & >6m & BtheB & 32 & 2 & 5 & 17\\\\\n\\hline\n2.8m & Yes & >6m & BtheB & 32 & 2 & 8 & 20\\\\\n\\hline\n\\end{tabular}\n:::\n\n```{.r .cell-code}\nkable(subset(BtheB_long,  subject == 99))%>%\n  kable_styling(bootstrap_options = \"striped\", full_width = F, position = \"left\")\n```\n\n::: {.cell-output-display}\n\\begin{tabular}{l|l|l|l|r|l|r|r}\n\\hline\n  & drug & length & treatment & bdi.pre & subject & time & bdi\\\\\n\\hline\n99.2m & No & <6m & TAU & 13 & 99 & 2 & 5\\\\\n\\hline\n99.3m & No & <6m & TAU & 13 & 99 & 3 & 5\\\\\n\\hline\n99.5m & No & <6m & TAU & 13 & 99 & 5 & 0\\\\\n\\hline\n99.8m & No & <6m & TAU & 13 & 99 & 8 & 6\\\\\n\\hline\n\\end{tabular}\n:::\n\n```{.r .cell-code}\n\n\nlmfit <- lm(bdi ~ bdi.pre + time + treatment + drug +length, data = BtheB_long,\n                    na.action = na.omit)\nrequire(jtools)\n#> Loading required package: jtools\nsumm(lmfit)\n```\n\n::: {.cell-output-display}\n\\begin{table}[!h]\n\\centering\n\\begin{tabular}{lr}\n\\toprule\n\\cellcolor{gray!6}{Observations} & \\cellcolor{gray!6}{280 (120 missing obs. deleted)}\\\\\nDependent variable & bdi\\\\\n\\cellcolor{gray!6}{Type} & \\cellcolor{gray!6}{OLS linear regression}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{tabular}{lr}\n\\toprule\n\\cellcolor{gray!6}{F(5,274)} & \\cellcolor{gray!6}{35.78}\\\\\nR² & 0.40\\\\\n\\cellcolor{gray!6}{Adj. R²} & \\cellcolor{gray!6}{0.38}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{threeparttable}\n\\begin{tabular}{lrrrr}\n\\toprule\n  & Est. & S.E. & t val. & p\\\\\n\\midrule\n\\cellcolor{gray!6}{(Intercept)} & \\cellcolor{gray!6}{7.32} & \\cellcolor{gray!6}{1.73} & \\cellcolor{gray!6}{4.24} & \\cellcolor{gray!6}{0.00}\\\\\nbdi.pre & 0.57 & 0.05 & 10.44 & 0.00\\\\\n\\cellcolor{gray!6}{time} & \\cellcolor{gray!6}{-0.94} & \\cellcolor{gray!6}{0.24} & \\cellcolor{gray!6}{-3.97} & \\cellcolor{gray!6}{0.00}\\\\\ntreatmentBtheB & -3.32 & 1.10 & -3.02 & 0.00\\\\\n\\cellcolor{gray!6}{drugYes} & \\cellcolor{gray!6}{-3.57} & \\cellcolor{gray!6}{1.15} & \\cellcolor{gray!6}{-3.11} & \\cellcolor{gray!6}{0.00}\\\\\n\\addlinespace\nlength>6m & 1.71 & 1.11 & 1.54 & 0.12\\\\\n\\bottomrule\n\\end{tabular}\n\\begin{tablenotes}\n\\item Standard errors: OLS\n\\end{tablenotes}\n\\end{threeparttable}\n\\end{table}\n:::\n:::\n\n\n\n#### Random intercept but fixed slope\n\nLet us start with a model with a random intercept but fixed slope. In this case, the resulting regression line for each individual is parallel (for fixed slope) but have different intercepts (for random intercept).\n\n\n\n::: {.cell hash='longitudinal1_cache/pdf/random_59e03e78a55bdf7fafca83a065472613'}\n\n```{.r .cell-code}\n## Fit a random intercept model with lme4 package\nlibrary(\"lme4\")\n#> Loading required package: Matrix\nBtheB_lmer1 <- lmer(bdi ~ bdi.pre + time + treatment + drug +length \n                    + (1 | subject), data = BtheB_long, REML = FALSE, \n                    na.action = na.omit)\n\nsummary(BtheB_lmer1)\n#> Linear mixed model fit by maximum likelihood  ['lmerMod']\n#> Formula: bdi ~ bdi.pre + time + treatment + drug + length + (1 | subject)\n#>    Data: BtheB_long\n#> \n#>      AIC      BIC   logLik deviance df.resid \n#>   1887.5   1916.6   -935.7   1871.5      272 \n#> \n#> Scaled residuals: \n#>     Min      1Q  Median      3Q     Max \n#> -2.6975 -0.5026 -0.0638  0.4124  3.8203 \n#> \n#> Random effects:\n#>  Groups   Name        Variance Std.Dev.\n#>  subject  (Intercept) 48.78    6.984   \n#>  Residual             25.14    5.014   \n#> Number of obs: 280, groups:  subject, 97\n#> \n#> Fixed effects:\n#>                Estimate Std. Error t value\n#> (Intercept)     5.59239    2.24244   2.494\n#> bdi.pre         0.63968    0.07789   8.212\n#> time           -0.70476    0.14639  -4.814\n#> treatmentBtheB -2.32908    1.67036  -1.394\n#> drugYes        -2.82495    1.72684  -1.636\n#> length>6m       0.19708    1.63832   0.120\n#> \n#> Correlation of Fixed Effects:\n#>             (Intr) bdi.pr time   trtmBB drugYs\n#> bdi.pre     -0.682                            \n#> time        -0.238  0.020                     \n#> tretmntBthB -0.390  0.121  0.018              \n#> drugYes     -0.073 -0.237 -0.022 -0.323       \n#> length>6m   -0.243 -0.242 -0.036  0.002  0.157\nsumm(BtheB_lmer1)\n#> Registered S3 methods overwritten by 'broom':\n#>   method            from  \n#>   tidy.glht         jtools\n#>   tidy.summary.glht jtools\n```\n\n::: {.cell-output-display}\n\\begin{table}[!h]\n\\centering\n\\begin{tabular}{lr}\n\\toprule\n\\cellcolor{gray!6}{Observations} & \\cellcolor{gray!6}{280}\\\\\nDependent variable & bdi\\\\\n\\cellcolor{gray!6}{Type} & \\cellcolor{gray!6}{Mixed effects linear regression}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{tabular}{lr}\n\\toprule\n\\cellcolor{gray!6}{AIC} & \\cellcolor{gray!6}{1887.49}\\\\\nBIC & 1916.57\\\\\n\\cellcolor{gray!6}{Pseudo-R² (fixed effects)} & \\cellcolor{gray!6}{0.39}\\\\\nPseudo-R² (total) & 0.79\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{threeparttable}\n\\begin{tabular}{lrrrrr}\n\\toprule\n\\multicolumn{6}{c}{Fixed Effects} \\\\\n\\cmidrule(l{3pt}r{3pt}){1-6}\n  & Est. & S.E. & t val. & d.f. & p\\\\\n\\midrule\n\\cellcolor{gray!6}{(Intercept)} & \\cellcolor{gray!6}{5.59} & \\cellcolor{gray!6}{2.30} & \\cellcolor{gray!6}{2.43} & \\cellcolor{gray!6}{113.05} & \\cellcolor{gray!6}{0.02}\\\\\nbdi.pre & 0.64 & 0.08 & 8.00 & 107.38 & 0.00\\\\\n\\cellcolor{gray!6}{time} & \\cellcolor{gray!6}{-0.70} & \\cellcolor{gray!6}{0.15} & \\cellcolor{gray!6}{-4.79} & \\cellcolor{gray!6}{199.05} & \\cellcolor{gray!6}{0.00}\\\\\ntreatmentBtheB & -2.33 & 1.72 & -1.36 & 100.73 & 0.18\\\\\n\\cellcolor{gray!6}{drugYes} & \\cellcolor{gray!6}{-2.82} & \\cellcolor{gray!6}{1.77} & \\cellcolor{gray!6}{-1.59} & \\cellcolor{gray!6}{101.77} & \\cellcolor{gray!6}{0.11}\\\\\n\\addlinespace\nlength>6m & 0.20 & 1.68 & 0.12 & 103.77 & 0.91\\\\\n\\bottomrule\n\\end{tabular}\n\\begin{tablenotes}\n\\item  p values calculated using Kenward-Roger standard errors and d.f. \n\\end{tablenotes}\n\\end{threeparttable}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{tabular}{lll}\n\\toprule\n\\multicolumn{3}{c}{Random Effects} \\\\\n\\cmidrule(l{3pt}r{3pt}){1-3}\nGroup & Parameter & Std. Dev.\\\\\n\\midrule\n\\cellcolor{gray!6}{subject} & \\cellcolor{gray!6}{(Intercept)} & \\cellcolor{gray!6}{6.98}\\\\\nResidual &  & 5.01\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{tabular}{lrl}\n\\toprule\n\\multicolumn{3}{c}{Grouping Variables} \\\\\n\\cmidrule(l{3pt}r{3pt}){1-3}\nGroup & \\# groups & ICC\\\\\n\\midrule\n\\cellcolor{gray!6}{subject} & \\cellcolor{gray!6}{97} & \\cellcolor{gray!6}{0.66}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n\n\n::: callout-important\n-   AIC, BIC, and -loglik etc are goodness-of-fit statistics, which tells you how well the model fits your data. Since there is no standard to tell what values of these statistics are good, without comparison with other models, they have little information to tell.\n\n-   Fixed effects: this is the standard output we will have in any fixed-effect model. The interpretation of estimated coefficients will be similar to a regular linear model.\n\n-   You may compare the outputs with the regular linear model, then you will find that **lm** tends to **underestimate** the SE for estimated coefficients.\n:::\n\n\n\n::: {.cell hash='longitudinal1_cache/pdf/random2_82006cde93e73e9403241ca7bd9aea2a'}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nBtheB_longna <- na.omit(BtheB_long)\ndat <- data.frame(time=BtheB_longna$time,pred=fitted(BtheB_lmer1),Subject= BtheB_longna$subject)\nggplot(data=dat,aes(x=time, y=pred, group=Subject, color=Subject)) + theme_classic() +\n    geom_line() \n```\n\n::: {.cell-output-display}\n![](longitudinal1_files/figure-pdf/random2-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\nAs we can see, for each individual, we have different intercepts but the slope over follow-up time is the same. Next, we will fit the model with random intercept and random slope.\n\n#### Random intercept and random slope\n\nIn the codes below, we fitted a mixed effects model with both random intercept and random slope:\n\n\n\n::: {.cell hash='longitudinal1_cache/pdf/random3_1312da4ed0fb73113467d434087accc9'}\n\n```{.r .cell-code}\n## We can fit a random slope and intercept model using lme4 package and treat variable time as random slope. \nlibrary(\"lme4\")\nBtheB_lmer2 <- lmer(bdi ~ bdi.pre + time + treatment + drug +length + \n                   (time | subject), data = BtheB_long, REML = FALSE, \n                   na.action = na.omit)\n\nsumm(BtheB_lmer2)\n```\n\n::: {.cell-output-display}\n\\begin{table}[!h]\n\\centering\n\\begin{tabular}{lr}\n\\toprule\n\\cellcolor{gray!6}{Observations} & \\cellcolor{gray!6}{280}\\\\\nDependent variable & bdi\\\\\n\\cellcolor{gray!6}{Type} & \\cellcolor{gray!6}{Mixed effects linear regression}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{tabular}{lr}\n\\toprule\n\\cellcolor{gray!6}{AIC} & \\cellcolor{gray!6}{1891.04}\\\\\nBIC & 1927.39\\\\\n\\cellcolor{gray!6}{Pseudo-R² (fixed effects)} & \\cellcolor{gray!6}{0.39}\\\\\nPseudo-R² (total) & 0.80\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{threeparttable}\n\\begin{tabular}{lrrrrr}\n\\toprule\n\\multicolumn{6}{c}{Fixed Effects} \\\\\n\\cmidrule(l{3pt}r{3pt}){1-6}\n  & Est. & S.E. & t val. & d.f. & p\\\\\n\\midrule\n\\cellcolor{gray!6}{(Intercept)} & \\cellcolor{gray!6}{5.61} & \\cellcolor{gray!6}{2.33} & \\cellcolor{gray!6}{2.41} & \\cellcolor{gray!6}{111.13} & \\cellcolor{gray!6}{0.02}\\\\\nbdi.pre & 0.64 & 0.08 & 7.96 & 106.35 & 0.00\\\\\n\\cellcolor{gray!6}{time} & \\cellcolor{gray!6}{-0.70} & \\cellcolor{gray!6}{0.16} & \\cellcolor{gray!6}{-4.47} & \\cellcolor{gray!6}{59.16} & \\cellcolor{gray!6}{0.00}\\\\\ntreatmentBtheB & -2.38 & 1.74 & -1.37 & 100.93 & 0.17\\\\\n\\cellcolor{gray!6}{drugYes} & \\cellcolor{gray!6}{-2.87} & \\cellcolor{gray!6}{1.80} & \\cellcolor{gray!6}{-1.60} & \\cellcolor{gray!6}{101.96} & \\cellcolor{gray!6}{0.11}\\\\\n\\addlinespace\nlength>6m & 0.14 & 1.70 & 0.08 & 103.76 & 0.93\\\\\n\\bottomrule\n\\end{tabular}\n\\begin{tablenotes}\n\\item  p values calculated using Kenward-Roger standard errors and d.f. \n\\end{tablenotes}\n\\end{threeparttable}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{tabular}{lll}\n\\toprule\n\\multicolumn{3}{c}{Random Effects} \\\\\n\\cmidrule(l{3pt}r{3pt}){1-3}\nGroup & Parameter & Std. Dev.\\\\\n\\midrule\n\\cellcolor{gray!6}{subject} & \\cellcolor{gray!6}{(Intercept)} & \\cellcolor{gray!6}{7.12}\\\\\nsubject & time & 0.43\\\\\n\\cellcolor{gray!6}{Residual} & \\cellcolor{gray!6}{} & \\cellcolor{gray!6}{4.90}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{tabular}{lrl}\n\\toprule\n\\multicolumn{3}{c}{Grouping Variables} \\\\\n\\cmidrule(l{3pt}r{3pt}){1-3}\nGroup & \\# groups & ICC\\\\\n\\midrule\n\\cellcolor{gray!6}{subject} & \\cellcolor{gray!6}{97} & \\cellcolor{gray!6}{0.68}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table}\n:::\n:::\n\n\n\nThe interpretation of the model outputs will be similar to the model with only random intercepts. Let us plot the data:\n\n\n\n::: {.cell hash='longitudinal1_cache/pdf/random5_2774130406b6027b36b81db28a54a80c'}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nBtheB_longna <- na.omit(BtheB_long)\ndat <- data.frame(time=BtheB_longna$time,pred=fitted(BtheB_lmer2),Subject= BtheB_longna$subject)\nggplot(data=dat,aes(x=time, y=pred, group=Subject, color=Subject)) + theme_classic() +\n    geom_line() \n```\n\n::: {.cell-output-display}\n![](longitudinal1_files/figure-pdf/random5-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\nFrom the figure, we can see, we have different intercepts and different slopes over follow-up time for each individual.\n\n#### Choice among models\n\nA common question is to ask should I add random slope to our model or random intercept is good enough. We may want to compare the models in terms of AIC and BIC. Smaller values indicate a better model.\n\n-   **lm** usually will not be considered as a competitor of **lme** as they basically apply to different types of data.\n\n-   When choosing between random intercept and random slope, a quick solution is to fit all possible models then do likelihood ratio tests.\n\n-   For example, I am not sure whether I should use random intercept only or random intercept + random slope. I could fit both model, then do a likelihood ratio test:\n\n\n\n::: {.cell hash='longitudinal1_cache/pdf/model_91e588a35e74729169042955aaa8ac3d'}\n\n```{.r .cell-code}\nanova(BtheB_lmer1, BtheB_lmer2)\n#> Data: BtheB_long\n#> Models:\n#> BtheB_lmer1: bdi ~ bdi.pre + time + treatment + drug + length + (1 | subject)\n#> BtheB_lmer2: bdi ~ bdi.pre + time + treatment + drug + length + (time | subject)\n#>             npar    AIC    BIC  logLik deviance  Chisq Df Pr(>Chisq)\n#> BtheB_lmer1    8 1887.5 1916.6 -935.75   1871.5                     \n#> BtheB_lmer2   10 1891.0 1927.4 -935.52   1871.0 0.4542  2     0.7969\n## The non-significant p-value shows that the second model is not \n## statistically different from the first model. Therefore, adding a \n## random slope is not necessary\n```\n:::\n\n\n\nThe p-value is greater than 0.05, which indicate that adding a random slope does not make the fitting significantly better. To keep the model simple, we may just use random intercept.\n\n### Prediction of Random Effects\n\n-   Ref: [@hothorn2014handbook] Section 12.5\n\nIf you have noticed in the R output of linear mixed effect model. Random effects are not estimated in the model.\n\n-   We could use the fitted model to predict random effects.\n\n-   Also, the predicted random effects can be used to examine the assumptions we have for linear mixed effect model.\n\nThe **ranef** function is used to predict the random effect in R\n\n\n\n::: {.cell hash='longitudinal1_cache/pdf/pred_ae5508b399ce7947957a7d7d1b680e46'}\n\n```{.r .cell-code}\nqint <- ranef(BtheB_lmer1)$subject[[\"(Intercept)\"]]\nqint\n#>  [1] -16.36173411  -2.44276827  -3.81655251   3.05333928   3.45142248\n#>  [6]   7.76598376   2.72263773  -7.22484569   6.84680617  -1.02552084\n#> [11]   2.40417048   1.16611114  -8.55346533  -6.25844483  -2.26117896\n#> [16]  -5.23031336   2.52509381  -1.64263857  -1.07523649   3.93689163\n#> [21]   7.66903473 -16.38156595   1.74883174  -1.31871410  -9.02883854\n#> [26]  -2.75150756   2.38884151   2.72740404  -3.41918542   6.27519245\n#> [31]  -4.52154811  -8.67437225  -0.34470208  -0.63972054  -0.08927194\n#> [36]   7.61914282   2.91050412  -2.58455318   4.24637616 -16.01664364\n#> [41]   5.90993779   3.21014012  -7.04631398   3.09608824   4.71327710\n#> [46]  16.70161338   2.26241522   2.26584476  15.77002952   1.75410838\n#> [51]   6.18741474   1.99791717   0.56774362   4.04107968  10.72891321\n#> [56]  -1.54551028  -5.28330207   2.04552526   2.36472056  -1.56879952\n#> [61]   6.63565636   5.45929329  -4.19695096  -6.39632488  -2.21496288\n#> [66]  -0.95956136  -3.96021851   7.17628718  -1.41644518  -4.99763144\n#> [71]  -2.83374092  -1.28015494   8.79345988  -0.33213428   1.43146353\n#> [76]  -3.13316295  -6.52989461   2.51445573   5.93415004   3.42003755\n#> [81]   4.49954804   3.75178702  -6.44832897  12.88173218  -9.36110814\n#> [86]   2.02028152 -18.09960241  -6.53428535   5.06613705  -3.31816912\n#> [91]   7.26187445   0.03103101  -8.14350181  -4.89326763   2.92437698\n#> [96]   5.24835927  -5.96778945\n## predict random effects using the fitted model\n```\n:::\n\n\n\n### Check assumptions\n\nRemember, we have two assumptions in the linear mixed effect model with random intercept:\n\n-   error term follows normal distribution\n-   beta for subject $i$ follows normal distribution\n\nWe have predict the values of random effect and we could extract residuals from the fitted model. Therefore, we can use QQ-plot to check their normality\n\n\n\n::: {.cell hash='longitudinal1_cache/pdf/assumption_9f84759f00345f54a40ffb2e7d9baa18'}\n\n```{.r .cell-code}\n# Assumption 1\nqres <- residuals(BtheB_lmer1)\nqqnorm(qres, xlim = c(-3, 3), ylim = c(-20, 20), ylab = \"Estimated residuals\",\n       main = \"Residuals\")\nqqline(qres)\n```\n\n::: {.cell-output-display}\n![](longitudinal1_files/figure-pdf/assumption-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\n\n# Assumption 2\nqint <- ranef(BtheB_lmer1)$subject[[\"(Intercept)\"]]\nqqnorm(qint, ylab = \"Estimated random intercepts\", xlim = c(-3, 3), ylim = c(-20, 20),\n       main = \"Random intercepts\")\nqqline(qint)\n```\n\n::: {.cell-output-display}\n![](longitudinal1_files/figure-pdf/assumption-2.pdf){fig-pos='H'}\n:::\n:::\n\n\n\nSince points are almost on the lines, we can say that the normality assumption is met.\n\n### Video content (optional)\n\n::: callout-tip\nFor those who prefer a video walkthrough, feel free to watch the video below, which offers a description of an earlier version of the above content.\n:::\n\n::: {style=\"position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;\"}\n<iframe src=\"https://www.youtube.com/embed/x7bTkZmyBkw\" style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" allowfullscreen>\n\n</iframe>\n:::\n\n::: {style=\"position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;\"}\n<iframe src=\"https://www.youtube.com/embed/SqSjejvTtdk\" style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;\" allowfullscreen>\n\n</iframe>\n:::\n\n### Reference",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"fixed\",\"fixed\",\"fixed\",\"fixed\",\"fixed\",\"fixed\",\"fixed\",\"fixed\",\"fixed\",\"fixed\",\"fixed\",\"fixed\",\"fixed\",\"fixed\",\"random\",\"random\",\"random\",\"random\",\"random\",\"random\",\"random\",\"random\",\"random\",\"random\",\"random\",\"random\",\"random\",\"random\",\"random3\",\"random3\",\"random3\",\"random3\",\"random3\",\"random3\",\"random3\",\"random3\",\"random3\",\"random3\",\"random3\",\"random3\",\"random3\",\"random3\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"table\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"table\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"table\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}