project:
  type: book
  output-dir: docs
execute:
  freeze: auto
book:
  title: "Advanced Epidemiological Methods"
  author: 
  - name: M. Ehsan. Karim
    affiliation: School of Population and Public Health, The University of British Columbia
  - name: Epi-OER team
    affiliation: Epi-OER team includes co-applicants of the UBC OER Fund Implementation Grant - Hossain MB, Frank HA, Yusuf FL, Ahmed SS, Asamoah-Boaheng M, Zheng C (all affiliated with the University of British Columbia)
  reader-mode: true
  search: true
  page-navigation: true
  twitter-card: true
  google-analytics:
    tracking-id: "G-CVBPG0RQMY"
    anonymize-ip: true
  sidebar:
    style: docked
    background: light
  date: today

  chapters:
    - index.qmd
    
    - part: wrangling.qmd
      chapters:
        - wrangling1a.qmd
        - wrangling1b.qmd
        - wrangling1c.qmd
        - wrangling2.qmd
        - wrangling3.qmd
        - wrangling4.qmd
        - wrangling5.qmd
        - wrangling6.qmd
        - wranglingF.qmd
        - wranglingQ.qmd
        - wranglingS.qmd
        - wranglingE.qmd
        - wranglingEsolution.qmd

    - part: accessing.qmd
      chapters: 
        - accessing0.qmd
        - accessing1.qmd
        - accessing1i.qmd
        - accessing2.qmd
        - accessing3.qmd
        - accessing4.qmd
        - accessing5.qmd
        - accessing7.qmd
        - accessing8.qmd
        - accessingF.qmd
        - accessingQ.qmd
        - accessingS.qmd
        - accessingE.qmd
        - accessingEsolution.qmd
        - accessingE1vibep1.qmd
        - accessingE1vibep2.qmd
        - accessingE2.qmd
        - accessingE2solution.qmd
        - accessingE3.qmd
        - accessingE3solution.qmd
        - accessingE3vibe.qmd

    - part: exploring.qmd
      chapters: 
        - exploring0.qmd
        - exploring1.qmd
        - exploring2.qmd
        
    - part: researchquestion.qmd
      chapters: 
        - researchquestion0.qmd
        - researchquestion1.qmd
        - researchquestion2a.qmd
        - researchquestion2b.qmd
        - researchquestion3.qmd
        - researchquestion4.qmd
        - researchquestionF.qmd
        - researchquestionQ.qmd
        - researchquestionS.qmd
        
    - part: Simulation.qmd
      chapters:
        - Simulation1.qmd
        - Simulation2.qmd
        - Simulation3.qmd
        
    - part: confounding.qmd
      chapters:
        - confounding0.qmd
        - confounding1.qmd
        - confounding2.qmd
        - confounding3.qmd
        - confounding3b.qmd
        - confounding4.qmd
        - confounding5.qmd
        - confounding6.qmd
        - confoundingF.qmd
        - confoundingQ.qmd
        - confoundingE.qmd
        - confoundingEsolution.qmd
        - confoundingE2.qmd
        - confoundingE2solution.qmd

    - part: predictivefactors.qmd
      chapters:
        - predictivefactors0.qmd
        - predictivefactors1.qmd
        - predictivefactors2.qmd
        - predictivefactors3.qmd
        - predictivefactors4.qmd
        - predictivefactors5.qmd
        - predictivefactors6.qmd
        - predictivefactors7.qmd
        - predictivefactorsF.qmd
        - predictivefactorsQ.qmd

    - part: surveydata.qmd
      chapters:
        - surveydata0.qmd
        - surveydata1.qmd
        - surveydata2.qmd
        - surveydata3.qmd
        - surveydata4.qmd
        - surveydata5.qmd
        - surveydata6.qmd
        - surveydata7.qmd
        - surveydata8.qmd
        - surveydata9.qmd
        - surveydata9c.qmd
        - surveydataF.qmd
        - surveydataQ.qmd
        - surveydataS.qmd
        - surveydataE.qmd
        - surveydataEsolution.qmd

    - part: missingdata.qmd
      chapters:
        - missingdata0.qmd
        - missingdata1.qmd
        - missingdata2.qmd
        - missingdata3.qmd
        - missingdata4.qmd
        - missingdata5.qmd
        - missingdata6.qmd
        - missingdata7.qmd
        - missingdataF.qmd
        - missingdataQ.qmd
        - missingdataS.qmd
        - missingdataE.qmd
        - missingdataEsolution.qmd

    - part: propensityscore.qmd
      chapters:
        - propensityscore0.qmd
        - propensityscore1.qmd
        - propensityscore2.qmd
        - propensityscore3.qmd
        - propensityscore4.qmd
        - propensityscore5.qmd
        - propensityscore6.qmd
        - propensityscore7.qmd
        - propensityscore8.qmd
        - propensityscore9.qmd
        - propensityscoreF.qmd
        - propensityscoreQ.qmd
        - propensityscoreS.qmd
        - propensityscoreE.qmd
        - propensityscoreEsolution.qmd

    - part: machinelearning.qmd
      chapters:
        - machinelearning0.qmd
        - machinelearning1.qmd
        - machinelearning2.qmd
        - machinelearning3.qmd
        - machinelearning4.qmd
        - machinelearning5.qmd
        - machinelearning6.qmd
        - machinelearning6a.qmd
        - machinelearning6b.qmd
        - machinelearningQ.qmd
        - machinelearningF.qmd
        - machinelearningE.qmd
        - machinelearningEsolution.qmd

    - part: machinelearningCausal.qmd
      chapters:
        - machinelearningCausal0.qmd
        - machinelearningCausal1.qmd
        - machinelearningCausal2.qmd
        - machinelearningCausal3.qmd
        - machinelearningCausal4.qmd
        - machinelearningCausal5.qmd
        - machinelearningCausalQ.qmd
        - machinelearningCausalF.qmd

    - part: nonbinary.qmd
      chapters:
        - nonbinary0.qmd
        - nonbinary1.qmd
        - nonbinary2.qmd
        - nonbinary2a.qmd
        - nonbinary3.qmd
        - nonbinaryF.qmd
        - nonbinaryQ.qmd

    - part: longitudinal.qmd
      chapters:
        - longitudinal0.qmd
        - longitudinal1.qmd
        - longitudinal2.qmd
        - longitudinalF.qmd
        - longitudinalQ.qmd
        
    - part: mediation.qmd
      chapters:
        - mediation0.qmd
        - mediation1.qmd
        - mediation2.qmd
        - mediation3.qmd
        - mediationF.qmd
        - mediationQ.qmd
        
    - part: reporting.qmd
      chapters:
        - reporting1.qmd
        - reporting1a.qmd
        - reporting1b.qmd
        - reporting1c.qmd
        - reporting2.qmd
        
bibliography: ref.bib
highlight-style: pygments

format:
  html:
    toc: true
    theme: cosmo
    df-print: paged
    code-fold: false
    code-overflow: wrap
    code-copy: hover
    code-line-numbers: true
    code-link: true
    code-summary: "Show the code"
    code-tools: 
      source: false
      toggle: true
      caption: none
  pdf:
    toc: true
    toc-depth: 2
    toc-title: "Table of contents"
    code-line-numbers: true
    pdf-engine: xelatex
    colorlinks: true
    keep-tex: true
    options:
      - --page-size
      - A3
      - --numbered
prefer-html: true

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    R.options:
      knitr.graphics.auto_pdf: true

editor: visual

resources:
  - "scriptW.js"
  - "scriptA.js"
  - "scriptQ.js"
  - "scriptR.js"
  - "scriptP.js"
  - "scriptD.js"
  - "scriptM.js"
  - "scriptS.js"
  - "scriptL.js"
  - "scriptC.js"
  - "scriptN.js"
  - "scriptT.js"
  - "scriptI.js"
