project:
  type: book
  output-dir: docs
execute:
  freeze: auto
book:
  title: "OER: Advanced Epidemiological Methods"
  reader-mode: true
  search: true
  page-navigation: true
  twitter-card: true
  sidebar:
    style: docked
    background: light
  date: today

  chapters:
    - index.qmd
    
    - part: wrangling.qmd
      chapters:
        - wrangling1a.qmd
        - wrangling1b.qmd
        - wrangling1c.qmd
        - wrangling2.qmd
        - wrangling3.qmd
        - wrangling4.qmd
        - wrangling5.qmd
        - wranglingF.qmd
        - wranglingQ.qmd
        - wranglingE.qmd

    - part: accessing.qmd
      chapters: 
        - accessing1.qmd
        - accessing2.qmd
        - accessing3.qmd
        - accessing4.qmd
        - accessingF.qmd
        - accessingQ.qmd
        - accessingE.qmd

    - part: researchquestion.qmd
      chapters: 
        - researchquestion1.qmd
        - researchquestion2a.qmd
        - researchquestion2b.qmd
        - researchquestion3.qmd
        - researchquestion4.qmd
        - researchquestionF.qmd
        - researchquestionQ.qmd

    - part: confounding.qmd
      chapters:
        - confounding1.qmd
        - confounding2.qmd
        - confounding3.qmd
        - confounding4.qmd
        - confounding5.qmd
        - confounding6.qmd
        - confoundingF.qmd
        - confoundingQ.qmd

    - part: predictivefactors.qmd
      chapters:
        - predictivefactors1.qmd
        - predictivefactors2.qmd
        - predictivefactors3.qmd
        - predictivefactors4.qmd
        - predictivefactors5.qmd
        - predictivefactors6.qmd
        - predictivefactors7.qmd
        - predictivefactorsF.qmd
        - predictivefactorsQ.qmd

    - part: surveydata.qmd
      chapters:
        - surveydataF.qmd
        - surveydataE.qmd

    - part: missingdata.qmd
      chapters:
        - missingdataF.qmd
        - missingdataE.qmd

    - part: propensityscore.qmd
      chapters:
        - propensityscoreF.qmd
        - propensityscoreE.qmd

    - part: reporting.qmd
      chapters:
        - reportingF.qmd

    - part: machinelearning.qmd
      chapters:
        - machinelearningF.qmd

    - part: machinelearningCausal.qmd
      chapters:
        - machinelearningCausalF.qmd
        
bibliography: ref.bib
highlight-style: pygments

format:
  html:
    toc: true
    theme: cosmo
    df-print: paged
    code-fold: true
    code-overflow: wrap
    code-copy: hover
    code-link: true
    code-summary: "Show the code"
    code-tools: 
      source: false
      toggle: true
      caption: none

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    R.options:
      knitr.graphics.auto_pdf: true

editor: visual
