project:
  type: book
  output-dir: docs

book:
  title: "OER: Advanced Epidemiological Methods"
  reader-mode: true
  search: true
  page-navigation: true
  twitter-card: true
  sidebar:
    style: docked
    background: light
  date: today

  chapters:
    - index.qmd
    
    - part: wrangling.qmd
      chapters:
        - wrangling1a.qmd
        - wrangling1b.qmd
        - wrangling1c.qmd
        - wrangling2.qmd
        - wrangling3.qmd
        - wrangling4.qmd
        - wrangling5.qmd
        - wranglingF.qmd
        - wranglingQ.qmd

        
bibliography: ref.bib
highlight-style: pygments

format:
  html:
    theme: cosmo
    df-print: paged
    code-fold: true
    code-summary: "Show the code"
    code-tools: true

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    R.options:
      knitr.graphics.auto_pdf: true

editor: visual
