project:
  type: book
  output-dir: docs
execute:
  freeze: auto
book:
  title: "Advanced Epidemiological Methods"
  reader-mode: true
  search: true
  page-navigation: true
  twitter-card: true
  google-analytics:
    tracking-id: "G-CVBPG0RQMY"
    anonymize-ip: true
  sidebar:
    style: docked
    background: light
  date: today

  chapters:
    - index.qmd
    
    - part: wrangling.qmd
      chapters:
        - wrangling1a.qmd
        - wrangling1b.qmd
        - wrangling1c.qmd
        - wrangling2.qmd
        - wrangling3.qmd
        - wrangling4.qmd
        - wrangling5.qmd
        - wrangling6.qmd
        - wranglingF.qmd
        - wranglingQ.qmd
        - wranglingE.qmd

    - part: accessing.qmd
      chapters: 
        - accessing0.qmd
        - accessing1.qmd
        - accessing1i.qmd
        - accessing2.qmd
        - accessing3.qmd
        - accessing4.qmd
        - accessing5.qmd
        - accessingF.qmd
        - accessingQ.qmd
        - accessingE.qmd

    - part: researchquestion.qmd
      chapters: 
        - researchquestion0.qmd
        - researchquestion1.qmd
        - researchquestion2a.qmd
        - researchquestion2b.qmd
        - researchquestion3.qmd
        - researchquestion4.qmd
        - researchquestionF.qmd
        - researchquestionQ.qmd

    - part: confounding.qmd
      chapters:
        - confounding0.qmd
        - confounding1.qmd
        - confounding2.qmd
        - confounding3.qmd
        - confounding4.qmd
        - confounding5.qmd
        - confounding6.qmd
        - confounding7.qmd
        - confounding8.qmd
        - confoundingF.qmd
        - confoundingQ.qmd

    - part: predictivefactors.qmd
      chapters:
        - predictivefactors0.qmd
        - predictivefactors1.qmd
        - predictivefactors2.qmd
        - predictivefactors3.qmd
        - predictivefactors4.qmd
        - predictivefactors5.qmd
        - predictivefactors6.qmd
        - predictivefactors7.qmd
        - predictivefactorsF.qmd
        - predictivefactorsQ.qmd

    - part: surveydata.qmd
      chapters:
        - surveydata1.qmd
        - surveydata2.qmd
        - surveydata3.qmd
        - surveydata4.qmd
        - surveydata5.qmd
        - surveydata6.qmd
        - surveydata7.qmd
        - surveydata8.qmd
        - surveydataF.qmd
        - surveydataQ.qmd
        - surveydataE.qmd

    - part: missingdata.qmd
      chapters:
        - missingdata1.qmd
        - missingdata2.qmd
        - missingdata3.qmd
        - missingdata4.qmd
        - missingdata5.qmd
        - missingdata6.qmd
        - missingdata7.qmd
        - missingdataF.qmd
        - missingdataQ.qmd
        - missingdataE.qmd

    - part: propensityscore.qmd
      chapters:
        - propensityscore1.qmd
        - propensityscore2.qmd
        - propensityscore3.qmd
        - propensityscore4.qmd
        - propensityscore5.qmd      
        - propensityscoreF.qmd
        - propensityscoreQ.qmd
        - propensityscoreE.qmd

    - part: machinelearning.qmd
      chapters:
        - machinelearning1.qmd
        - machinelearning2.qmd
        - machinelearning3.qmd
        - machinelearning4.qmd
        - machinelearning5.qmd
        - machinelearning6.qmd
        - machinelearning6a.qmd
        - machinelearning6b.qmd
        - machinelearningF.qmd

    - part: machinelearningCausal.qmd
      chapters:
        - machinelearningCausal1.qmd
        - machinelearningCausal2.qmd
        - machinelearningCausal3.qmd
        - machinelearningCausal4.qmd
        - machinelearningCausal5.qmd
        - machinelearningCausalF.qmd

    - part: nonbinary.qmd
      chapters:
        - nonbinary1.qmd
        - nonbinary2.qmd
        - nonbinary3.qmd
        - nonbinaryF.qmd
        - nonbinaryQ.qmd

    - part: longitudinal.qmd
      chapters:
        - longitudinal1.qmd
        - longitudinal2.qmd
        - longitudinalF.qmd
        - longitudinalQ.qmd
        
    - part: mediation.qmd
      chapters:
        - mediation1.qmd
        - mediation2.qmd
        - mediation3.qmd
        - mediationF.qmd
        - mediationQ.qmd
        
    - part: reporting.qmd
      chapters:
        - reporting1.qmd
        - reporting2.qmd
        
bibliography: ref.bib
highlight-style: pygments

format:
  html:
    toc: true
    theme: cosmo
    df-print: paged
    code-fold: false
    code-overflow: wrap
    code-copy: hover
    code-line-numbers: true
    code-link: true
    code-summary: "Show the code"
    code-tools: 
      source: false
      toggle: true
      caption: none
  pdf:
    toc: true
    toc-depth: 2
    toc-title: "Table of contents"
    code-line-numbers: true
    pdf-engine: xelatex
    colorlinks: true
    keep-tex: true
    options:
      - --page-size
      - A3
      - --numbered
prefer-html: true

knitr:
  opts_chunk: 
    collapse: true
    comment: "#>" 
    R.options:
      knitr.graphics.auto_pdf: true

editor: visual
