## Survey data sources {.unnumbered}

The tutorial discusses complex survey data and highlights potential data sources. Key datasets with survey features include the Canadian Community Health Survey (CCHS), the National Health and Nutrition Examination Survey (NHANES), and the European Social Survey (ESS), among others. Many of these sources, like NHANES and ESS, have specific R packages for data retrieval. In addition, there are other data sources such as the Vanderbilt Biostatistics Datasets and the World Bank Open Data, with the latter also offering dedicated R packages for data access.

### Survey features
Generally survey features include
-   Strata
-   Cluster/primary sampling unit (PSU)
-   Weight, e.g., interview weight, survey weight

### Dataset with survey features

-   Canadian Community Health Survey - Annual Component [CCHS](https://www150.statcan.gc.ca/n1/en/catalogue/11-625-X)
    -   Download link [UBC library](http://dvn.library.ubc.ca/)
-   National Health and Nutrition Examination Survey [NHANES](https://www.cdc.gov/nchs/nhanes/index.htm)
    -   R packages to download data: [nhanesA](https://cran.r-project.org/web/packages/nhanesA/vignettes/Introducing_nhanesA.html), [RNHANES](https://cran.r-project.org/web/packages/RNHANES/vignettes/introduction.html)
-   National Longitudinal Study of Adolescent to Adult Health \[Add Health\], 1994-2008 [ICPSR 21600](http://www.icpsr.umich.edu/icpsrweb/DSDR/studies/21600)
-   European Social Survey [ESS](http://www.europeansocialsurvey.org/)
    -   R package to download data: [essurvey](https://cran.r-project.org/web/packages/essurvey/vignettes/intro_ess.html)
-   Behavioral Risk Factor Surveillance System [BRFSS](https://www.cdc.gov/brfss/data_documentation/index.htm)
-   Bureau of Economic Analysis [BEA](http://www.bea.gov/)
-   US National Vital Statistics System [NVSS](https://www.cdc.gov/nchs/nvss/vsrr.htm)
-   Demographic and Health Surveys [DHS](https://dhsprogram.com/data/available-datasets.cfm)

### Others

-   Vanderbilt Biostatistics Datasets [link](https://biostat.app.vumc.org/wiki/Main/DataSets)
-   World Bank Open Data [WBOD](https://data.worldbank.org/)
    -   R packages to download data: [wbstats](https://cran.r-project.org/web/packages/wbstats/vignettes/wbstats.html), [WDI](https://cran.r-project.org/web/packages/WDI/index.html)
