## Effect modifier {.unnumbered}

**Effect modification** and **interaction** are two distinct concepts in epidemiology. Effect modification occurs when the causal effect of an exposure (A) on an outcome (Y) varies based on the levels of a third factor (B). 

In this scenario, the association between the exposure and the outcome differs within the strata of a second exposure, which acts as the effect modifier. For instance, the impact of alcohol (A) on oral cancer (Y) might differ based on tobacco smoking (B). 

On the other hand, interaction refers to the joint causal effect of two exposures (A and B) on an outcome (Y). It examines how the combination of multiple exposures influences the outcome, such as the combined effect of alcohol (A) and tobacco smoking (B) on oral cancer (Y). 

In essence, while effect modification looks at how a third factor influences the relationship between an exposure and an outcome, interaction focuses on the combined effect of two exposures on the outcome. 

::: callout-important
To revisit or deepen your grasp of these two concepts, consider reviewing this [external tutorial](https://ehsanx.github.io/interaction/).
:::

## Reading list

Key reference: [@vanderweele2009distinction]

## Video content

::: callout-tip
### Effect modification vs. interaction 
:::

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/cxfwqBD1M1c" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen>

</iframe>
:::

## Lecture Slides

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQLJMvwzbtNCkjMMcir5lwLfQyUAjn52IQ2KhMwQqimCuTYNmqO8UCK2j8NBR-980n21JYSDK6RW-ad/embed?start=false&loop=false&delayms=3000" frameborder="0" width="672" height="398" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>

## Links

-   [Google Slides](https://docs.google.com/presentation/d/1q-RTYkiQV8tCbn71BGL3V11jjlGgq1oBfZwavLuWOks/edit?usp=sharing)
-   [PDF Slides](slides/interaction.pdf)

## References