## Table 2 fallacy {.unnumbered}

The "Table 2 Fallacy" in epidemiology refers to the misleading practice of presenting multiple adjusted effect estimates from a single statistical model in one table, often resulting in misinterpretation. This occurs when researchers report both the primary exposure's effects and secondary exposures' (often an adjustment variable for the primary exposure) effects without adequately distinguishing between the types of effects or considering the causal relationships among variables. 

This idea highlights the potential for misunderstanding in interpreting the effects of various exposures on an outcome when they are reported together, leading to confusion over the nature and magnitude of the relationships and possibly influencing the design and interpretation of further studies [@westreich2013table]. The fallacy demonstrates the need for careful consideration of the types of effects estimated and reported in statistical models, urging researchers to be clear about the distinctions and implications of controlled direct effects, total effects, and the presence of confounding or mediating variables.

## Reading list

Key reference: [@westreich2013table]

## Video content

::: callout-tip
### Table 2 fallacy
:::

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/W5nFdiP5pU4" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen>

</iframe>
:::

## Lecture Slides

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTZgDExI3XV75PFJ4f75XOg6RQi0Umrqca-mZPOapBvd_z5d7UPdWsRZGo40lBJNhbx0TKb1jewcwUG/embed?start=false&loop=false&delayms=3000" frameborder="0" width="672" height="398" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>

## Links

-   [Google Slides](https://docs.google.com/presentation/d/1XL3CXHfWpzFtawJmTsLG0ypbf-vKvZJWTM7-QJ5fohw/edit?usp=sharing)
-   [PDF Slides](slides/table2.pdf)
-   [External link from dagitty](https://dagitty.net/learn/graphs/table2-fallacy.html)

## References