## Concepts (T) {.unnumbered}

## Longitudinal Data Analysis

The section offers a brief overview of longitudinal data analysis, focusing on key concepts and methods. It explains that longitudinal data involves the repeated measurement of variables of interest over time, often referred to as panel data. The example study data is initially in wide-form, with multiple variables for each time point, and then it is reshaped into long-form data for analysis.

The analysis of longitudinal data includes various models, such as linear models, mixed-effect models, and marginal models (GEE). Linear models are introduced initially, where each subject has a common slope and intercept. These ideas can be expanded to incorporate random intercepts, random slopes, and combinations of both in mixed-effect models. Model diagnostics, including AIC, BIC, and -loglik, are discussed for model evaluation. The section briefly discussing different correlation structures and highlights the differences in interpretation between mixed models and marginal models.

## Reading list

Key reference: [@faraway2016extending; @hothorn2014handbook]

optional references: [@karim2021dealing; @cui2007selection]

## Lecture Videos

::: callout-tip
### Longitudinal models
:::

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/x7bTkZmyBkw" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen>

</iframe>
:::

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/SqSjejvTtdk" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen>

</iframe>
:::

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/qoqhPq_VILc" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen>

</iframe>
:::

::: callout-tip
### Marginal structural model
:::

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/Meq6I-9fw3k" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen>

</iframe>
:::


## Lecture Slides

Longitudinal models

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vS0wZxF1-YbTFR8L_5n1kcFqKkeIBBK_ZIkvSTzCPhnMGQwgXotTVzxZDOwQ8SVOsPxDZQxsHPDapAD/embed?start=false&amp;loop=false&amp;delayms=3000" frameborder="0" width="672" height="398" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true">

</iframe>

Marginal structural model

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQuW-e9oLomaved5JMkt4HzgJVYBVGsV8h-eyfdhKVmK8M5iFt0ab-Pe6way6HxKqMIy5swi0rbEDWs/embed?start=false&loop=false&delayms=3000" frameborder="0" width="672" height="398" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>

## Links

Longitudinal models

-   [Google Slides](https://docs.google.com/presentation/d/123zJFmHnvuNzy85fvh65ryK11SzWuY41ac6PrTdfSnw/edit?usp=sharing)
-   [PDF Slides](slides/Longitudinal.pdf)

Marginal structural model

-   [Google Slides](https://docs.google.com/presentation/d/1krkVxtmcY7I2BYTJx9V_Jd2iuq5ciTvZKDvJEIpL9aY/edit?usp=sharing)
-   [PDF Slides](slides/MSM.pdf)
-   [GitHub page](https://ehsanx.github.io/MSMsim/) about marginal structural model simulation

## References
