## Concepts (C) {.unnumbered}

## ML in causal inference

In comparative effectiveness studies, researchers typically use propensity score methods. However, propensity score methods have known limitations in real-world scenarios, when the true data generating mechanism is unknown. Targeted maximum likelihood estimation (TMLE) is an alternative estimation method with a number of desirable statistical properties. It is a doubly robust method, enabling the integration of machine learning approaches within the framework. Despite the fact that this method has been shown to perform better in terms of statistical properties (e.g., variance estimation) than propensity score methods in a variety of scenarios, it is not widely used in medical research as the implementation details of this approach are generally not well understood. In this section, we will explain this method in details.

## Reading list

Key reference: [@ehsan_karim_2021_5246085]

Optional reading: [@frank2023implementing]

## Video Lessons

::: callout-tip
### Machine learning

The workshop was first developed for R/Medicine Virtual Conference https://r-medicine.org/ 2021, August 24th. What is included in this Video Lesson/workshop:

-   Chapter 1 RHC data description 4:22
-   Chapter 2 G-computation 23:13
-   Chapter 3 G-computation using ML 45:02
-   Chapter 4 IPTW 1:18:50
-   Chapter 5 IPTW using ML 1:30:11
-   Chapter 6 TMLE 1:36:41
-   Chapter 7 Pre-packaged software 1:58:05
-   Chapter 8 Final Words 2:14:36

The timestamps are also included in the YouTube video description.
:::

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/u5aZRNLjJug" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen>

</iframe>
:::

## Links

The original workshop materials are available [here](https://ehsanx.github.io/TMLEworkshop/).

## References
