## Concepts (L) {.unnumbered}

## Machine learning

Machine learning focuses on developing algorithms and models that enable computers to learn from and make predictions or decisions based on data without being explicitly programmed. In epidemiology, machine learning has several important uses and applications. This section is a very basic introduction to machine learning for Epidemiology.

## Reading list

Key reference

-   [@bi2019machine]

Following ate optional but useful references

-   [@karim2021]
-   [@liu2019read]
-   [@kuhn2013over]
-   [@james2013introduction]
-   [@vittinghoff2012predictor]
-   [@Steyerberg2019]

## Lecture Videos

::: callout-tip
### Machine learning Reference
:::

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/T713OdjNzgk" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen>

</iframe>
:::

::: callout-tip
### Machine learning Terminologies

What is included in this lecture:

-   Reference 0:08
-   Types of Epidemiological models 0:32
-   Analyzing Epidemiological Study data 2:44
-   Machine learning 5:42
-   Terminologies 9:15
-   Classification of Machine learning 12:55
-   Classification of Supervised learning 17:30
-   Other classifications 18:42
-   Popular algorithms 20:06
-   Decision tree 20:50
-   Shrinkage Methods 26:37
-   Ensemble methods 37:04
-   Variable Importance measure 40:20
-   Epidemiologic applications 44:29
-   Future Reading 53:17

The timestamps are also included in the YouTube video description.
:::

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/NkGLxUe3MKs" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen>

</iframe>
:::

## Lecture Slides

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSQiSN4vJGYy4xLsf-gm1r-KgLHDkHgqV6Vn-OTxsC0hPMa0bdgR7lo-yapaWmmgOUEAwNpoSzxyabB/embed?start=false&amp;loop=false&amp;delayms=3000" frameborder="0" width="672" height="398" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true">

</iframe>

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vRkyWcZdEjLn7kAFVPMUOrH-xHMRZUk73pFFo-f76OwYANuPKyZcffQSpsIuJ50KvihHo0IE40OnkaM/embed?start=false&loop=false&delayms=3000" frameborder="0" width="672" height="398" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>

## Links

-   [Google Slides](https://docs.google.com/presentation/d/1qPsBjMHNgD-_EXoVylSM9-FGKv5at1iF4WicxNZ84lQ/edit?usp=sharing)
-   [PDF Slides](slides/MachineLearning.pdf)

## References
