## Concepts (I) {.unnumbered}

## Mediation Analysis

The section provides an overview of the concept and methods of mediation analysis in the context of epidemiology and statistical modeling. The section discusses total effects, indirect and direct paths, and highlights the limitations of the Baron and Kenny approach [@baron1986moderator]. It introduces the counterfactual definition, emphasizing the importance of adjusting for confounders and providing insights into the mechanics of mediation analysis through imputation and weighting methods. The section also covers sensitivity analysis, proportion mediated, and methodological extensions, including multi-category mediators and software references for conducting mediation analysis.

## Reading list

Key reference: [@rochon2014mediation; @lange2017applied]

## Video Lessons

::: callout-tip
### Mediation Analysis - Baron and Kenny (1986)
:::

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/zExuiLx9itY" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen>

</iframe>
:::

::: callout-tip
### Setting up Mediation analysis with counterfactual definitions and why confounding adjustment helps
:::

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/hAkmxp0liAo" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen>

</iframe>
:::

::: callout-tip
### Mediation analysis mechanism under counterfactual definition (i) Outcome imputation & (ii) Weighting
:::

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/OlLNGoO_zss" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen>

</iframe>
:::

::: callout-tip
### Mediation analysis using survey data, assumptions, extensions, software and references
:::

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/jXxyPVFQ8_k" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen>

</iframe>
:::

## Video Lesson Slides

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSvcoHRZlBC73fDQdHDV5vglrXqsSZWNMY1poiheRvB_6OOFyzbTTn1yuQS7RH5E9fNnc-zrVAIvOZ1/embed?start=false&amp;loop=false&amp;delayms=3000" frameborder="0" width="672" height="398" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true">

</iframe>

## Links

-   [Google Slides](https://docs.google.com/presentation/d/1unhfe97NuG_yZgz5O_h3dKJIqAkf7Nz_L3098anTShY/edit?usp=sharing)
-   [PDF Slides](slides/Mediation.pdf)

## References
