## Concepts (M) {.unnumbered}

## Missing Data Analysis

This section is about understanding, categorizing, and addressing missing data in clinical and epidemiological research. It highlights the prevalence of missing data in these fields, the common use of complete case analysis without considering the implications, and the types of missingness: Missing Completely at Random (MCAR), Missing at Random (MAR), and Not Missing at Random (NMAR), each requiring different approaches and considerations. The consequences of not properly addressing missing data are detailed as bias, incorrect standard errors/precision, and a substantial loss of power.

This section also delves into strategies for addressing missing data, focusing on ad-hoc approaches and imputation methods. Ad-hoc approaches, such as ignoring missing data or using a missing category indicator, are generally dismissed as statistically invalid. In contrast, imputation, particularly multiple imputation (MI), is presented as a more robust and statistically sound method. Multiple imputation involves creating multiple complete datasets by predicting missing values and pooling the results to address the uncertainty associated with missing data. The section further discusses the types of imputation, the necessity of including a sufficient number of predictive variables, and the use of subject-area knowledge in building imputation models, providing a nuanced understanding of the challenges and solutions associated with missing data in research.

Reporting Guideline section delves into the complexities of handling missing data in statistical analysis, primarily through MI methods, especially Multiple Imputation by Chained Equations (MICE). It lays out the assumptions necessary for these methods (MCAR, MAR, MNAR). The guide also details how MICE works, using sequential regression imputation to create multiple imputed datasets, thereby allowing for more accurate and robust statistical inferences. Additionally, it provides comprehensive instructions on reporting MICE analysis, including detailing the missingness rates, the reasons for missing data, the assumptions made, and the specifics of the imputation and pooling methods used, ensuring transparency and reproducibility in research.

## Reading list

Key reference: [@sterne2009multiple]

Optional reading: [@vanbuuren2018flexible]

Further optional readings: [@lumley2011complex; @granger2019avoiding; @hughes2019accounting]

## Video Lessons

::: callout-tip
### Missing Data Analysis
:::

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/Wnw5sssW8LI" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen>

</iframe>
:::

::: callout-tip
### Reporting guidelines when missing data is present
:::

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/Fv4FjZzNI_A" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen>

</iframe>
:::

## Video Lesson Slides

Missing data

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vRQfavQM7rta4wE-5eBOg_1Z2z-67uLmOqFM7_I2k7g6YwlwhNcNNAxve_XPrddbQSb421RbwFM7y-w/embed?start=false&loop=false&delayms=3000" frameborder="0" width="672" height="398" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQsPyxXYcVV9aDxKiQCOkkwCGq0ChizfR0Z2e-xPyAfFK2MuGeOr_NH6r4P-iviXDvRTBD5PcYf8FeZ/embed?start=false&amp;loop=false&amp;delayms=3000" frameborder="0" width="672" height="398" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true">

</iframe>

Reporting guideline

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSi4nsgMV3iCEHEVDGiwnMxvumKE_muP6xyh8GYSx7m2g60ma5Pc_bUBC1rRD6MApwI189vn_RcPL4Q/embed?start=false&amp;loop=false&amp;delayms=3000" frameborder="0" width="672" height="398" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true">

</iframe>

## Links

Video Lessons

-   [Google Slides](https://docs.google.com/presentation/d/1-H4_AorB9mJfJZMnpz4r2bo5yXFldCDFpQQKdtUSHD0/edit?usp=sharing)
-   [PDF Slides](slides/Missing.pdf)

Reporting guideline

-   [Google Slides](https://docs.google.com/presentation/d/1apk6C-kW-YOBZcBR5D2Hijm_s8BNa0T7eLnT2LHkPbc/edit?usp=sharing)
-   [PDF Slides](slides/MissingReport.pdf)

## References
