## R for predictive factors {.unnumbered}

The list of new R functions introduced in this *Predictive factors* lab component are below:

| Function name       | Package name  | Use                                                                                                                | Chapters                    |
|------------------|------------------|------------------|------------------|
| aggregate           | base/stats    | To see summary by groups, e.g., by gender                                                                          | Continuous outcome          |
| anova               | base/stats    | To compare models                                                                                                  | Continuous outcome          |
| auc                 | pROC          | To compute the AUC (area under the ROC curve) value                                                                | Binary outcome              |
| BrierScore          | DescTools     | To calculate the Brier score                                                                                       | Bootstrap                   |
| coef                | base/stats    | To see the coefficients of a fitted model                                                                          | Continuous outcome          |
| cor                 | base/stats    | To see the correlation between numeric variables                                                                   | Continuous outcome          |
| corrplot            | corrplot      | To visualize a correlation matrix                                                                                  | Continuous outcome          |
| createDataPartition | caret         | To split a dataset into training and testing sets                                                                   | Data splitting               |
| createFolds         | caret         | To create k folds based on the outcome variable                                                                    | Cross-validation            |
| crPlots             | car           | To see partial residual plot                                                                                       | Continuous outcome          |
| describeBy          | psych         | To see summary by groups, e.g., by gender                                                                          | Continuous outcome          |
| glm                 | base/stats    | To run generalized linear models                                                                                   | Binary outcome              |
| group_by            | dplyr         | To group by variables                                                                                              | Continuous outcome          |
| hat                 | base/stats    | To return a hat matrix                                                                                             | Continuous outcome          |
| ifelse              | base          | To set an condition, e.g., creating a categorical variable from a numerical variable based on a condition          | Binary outcome              |
| kable               | knitr         | To create a nice table                                                                                             | Bootstrap                   |
| layout              | base/graphics | To specify plot arrangement                                                                                        | Continuous outcome          |
| lines               | base/graphics | To daw a line graph                                                                                                | Binary outcome              |
| lm                  | base/stats    | To fit a linear regression                                                                                         | Continuous outcome          |
| lowess              | base/stats    | To smooth a scatter plot                                                                                           | Binary outcome              |
| model.matrix        | base/stats    | To construct a design/model matrix, e.g., a matrix with covariate values                                           | Continuous outcome          |
| ols_plot_resid_lev  | olsrr         | To visualize the residuals vs leverage plot                                                                        | Continuous outcome          |
| ols_vif_tol         | olsrr         | To calculate tolerance and variance inflation factor                                                               | Continuous outcome          |
| predict             | base/stats    | `predict` is a generic function that is used for prediction, e.g., predicting probability of an event from a model | Binary outcome              |
| R2                  | caret         | To calculate the R-squared value                                                                                   | Overfitting and performance |
| RMSE                | caret         | To calculate the RMSE value                                                                                        | Overfitting and performance |
| roc                 | pROC          | To build a ROC curve                                                                                               | Binary outcome              |
| sample              | base          | To take/draw random samples with or without replacement                                                            | Bootstrap                   |
| save.image          | base          | To save an R object                                                                                                | Continuous outcome          |
| spearman2           | Hmisc         | To compute the square of Spearman's rank correlation                                                               | Continuous outcome          |
| summarize           | dplyr         | To see summary                                                                                                     | Continuous outcome          |
| tapply              | base          | To apply a function over an array, e.g., to see the summary of a variable by gender                                | Continuous outcome          |
| train               | caret         | To fit the model with tuning hyperpapameters                                                                       | Cross-vaildation            |
| trainControl        | caret         | To tune the hyperparameters, i.e., controlling the parameters to train the model                                   | Cross-vaildation            |
| varclus             | Hmisc         | We use the `varclus` function to identify collinear predictors with cluster analysis                               | Collinear predictors        |
| vif                 | car           | To calculate variance inflation factor                                                                             | Continuous outcome          |
| which               | base          | To see which indices are TRUE                                                                                      | Continuous outcome          |

: {.striped .hover}
