## Concepts (S) {.unnumbered}

## Propensity Score Analysis

This section provides a comprehensive exploration into various facets of propensity score (PS) methods and their application in observational studies and surveys. Beginning with an in-depth look into key concepts and calculations related to ATE and ATT, the content navigates through the practical application and diagnostic checks of covariate balance using the SMD. It further elucidates the methodology and application of PS, particularly focusing on matching and weighting to mitigate bias and create comparable groups for causal inference. The intricacies of employing PS methods within surveys are explored, highlighting different approaches and the incorporation of design variables in PS and outcome models. Fundamental assumptions for causal inference, namely Conditional Exchangeability, Positivity, and Causal Consistency, are dissected to form a foundational understanding for conducting robust causal analyses. Additionally, the content optionally delves into the nuances of implementing IPW in surveys. Lastly, additional optional content features an insightful workshop, offering more explanations of PS method implementations in research contexts.

## Reading list

Key reference: [@austin2011tutorial]

Optional reading: 

- Propensity score introduction [@karim2021psm] [External link](https://ehsanx.github.io/psw/)
- Extensions of Propensity score approaches [External link](https://ehsanx.github.io/psm/): prepared for Guest Lecture in SPPH 500/007 (Analytical Methods in Epidemiological Research)
- Propensity score for complex surveys [External link](https://ehsanx.github.io/PS-survey/): Uses the same lectures here, with some added text descriptions. This also includes a  a structured framework for reporting analyses using PS methods in research manuscripts.
- Reporting guideline [@stuart2018propensity; @simoneau2022recommendations]
- Assumptions [@hernan2020causal]


Theoretical references for propensity score analyses in complex surveys:

[@austin2018propensity; @dugoff2014generalizing; @zanutto2006comparison; @leite2018propensity; @lenis2018measuring; @lenis2017its; @ridgeway2015propensity]

## Lecture Videos

::: callout-tip
### Target parameters
Average Treatment Effect (ATE) vs. Average Treatment effect on the Treated (ATT)
:::

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/-9W6h0MVrKI" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen>

</iframe>
:::

::: callout-tip
### Balance
Balance and standardized mean difference (SMD) in observational studies
:::

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/hqpPReClbRM" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen>

</iframe>
:::

::: callout-tip
### Propensity score matching
:::

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/42PXOMM1Sfw" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen>

</iframe>
:::

::: callout-tip
### Propensity score matching in complex survey
:::

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/SUjo2bWrfZ8" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen>

</iframe>
:::

::: callout-tip
### Propensity score weighting in complex survey
:::

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/T7M4r3htN2w" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen>

</iframe>
:::

::: callout-tip
### Causal Assumptions
:::

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/ypfnwbLn7DU" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen>

</iframe>
:::




::: callout-tip
### Conference Workshop (Optional)
Post Conference Workshop for 2021 Conference - Canadian Society for Epidemiology and Biostatistics (CSEB)
:::

::: {style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden;"}
<iframe src="https://www.youtube.com/embed/u4Nl7gnDEAY" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%; border:0;" allowfullscreen> </iframe>
:::


## Lecture Slides

Target parameters

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSdr9pcnziLlptu4KtxOuMEwj9eQHs_pcLBKXE6Nd8sGayUF1bcClYWlH-lg7xuNObqqYAmcCBwB1V9/embed?start=false&loop=false&delayms=3000" frameborder="0" width="672" height="398" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>

Balance

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vRoKGRXzHan8zR9eOOf0OyfhwSKpfbBwRDetWIP_CSx_o60GOHwQA9m-ZLrUBSHnACo5mZTU0QIpTdi/embed?start=false&loop=false&delayms=3000" frameborder="0" width="672" height="398" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>

Propensity score matching

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vTa9OOJVE9yhgTBitUWcFm59ZeGgpa93fIKakPED4vgZ6A54bqGx-FYNAT3spS8DrN7GsDEbvuwm4m7/embed?start=false&loop=false&delayms=3000" frameborder="0" width="672" height="398" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>

Propensity score matching in complex survey

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQPwqp-A9K29y2bBZgZO7ghy37RtY3ElmrzON_rztfRjz94WN03nqPrHILVhovK-t2_bclL4GhSiFAh/embed?start=false&loop=false&delayms=3000" frameborder="0" width="672" height="398" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>

Propensity score weighting in complex survey

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vSr74LDTrv9pBbfTQGUmeduS_lkuqa05ptC030NVl_sKXve5CRds77gvAV3hTMb4quNxPw6HXpXQbU6/embed?start=false&loop=false&delayms=3000" frameborder="0" width="672" height="398" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>

Causal Assumptions

<iframe src="https://docs.google.com/presentation/d/e/2PACX-1vQeYyXjsPKG6lsmbK2AvJdHxTAYxVXx_Vtr1XEOLYP6fXbZ3Np9xY3Yb2NE11chlekgDXPFR3vgpTD-/embed?start=false&loop=false&delayms=3000" frameborder="0" width="672" height="398" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>

## Links

Target parameters

-   [Google Slides](https://docs.google.com/presentation/d/1M8XdL0rBDK4K93k7c4F6cpWdFPoAAN9jfq76wDArCsk/edit?usp=sharing)
-   [PDF Slides](slides/targetparam.pdf)

Balance

-   [Google Slides](https://docs.google.com/presentation/d/19zDZnEPw24tuWXYRuIKSk_alyu_ssL-U8qZ9ZGxmDQw/edit?usp=sharing)
-   [PDF Slides](slides/Balance.pdf)

Propensity score matching

-   [Google Slides](https://docs.google.com/presentation/d/1QN4exWiex6wxc2XdQM855R2phNAlKWH5u0muItwdNfA/edit?usp=sharing)
-   [PDF Slides](slides/PropensityScore.pdf)

Propensity score matching in complex survey

-   [Google Slides](https://docs.google.com/presentation/d/12DYK-OxtqmXqoKZpRwF1ZTnU3wBOnr3kshjv38F28Gg/edit?usp=sharing)
-   [PDF Slides](slides/PropensityScoreComplex.pdf)

Propensity score weighting in complex survey

-   [Google Slides](https://docs.google.com/presentation/d/13xU3dcVi2NDamW4dFf1H2ogwgTxlonah-NWmSAbTTZE/edit?usp=sharing)
-   [PDF Slides](slides/PropensityScoreW.pdf)

Causal Assumptions

-   [Google Slides](https://docs.google.com/presentation/d/1ayA7oLB1VBBgQf8YO_6KbauAj_jHVICd8dNXc94Qt6E/edit?usp=sharing)
-   [PDF Slides](slides/Assumptions.pdf)


## References
