## App (S) {.unnumbered}

Below is an example of an app that utilizes the NHANES dataset following the [tutorial materials](propensityscore6.html). Users can visualize the results from a propensity score analysis using complex survey data, and implications of choosing different list of covariates for the propensity score model fit in each step of the analysis.

::: callout-tip
**Web App may need some time to load the necessary files, depending on your internet speed.**
:::

<iframe src="https://ehsanx.github.io/EpiShinyLiveS/" width="100%" height="600">

</iframe>

::: callout-important
If you want to run the app locally in your computer instead for faster load time: you can download the app directly in your R via `shiny::runGitHub("EpiShinyLiveS", "ehsanx", subdir = "app")`. Make sure that `shiny`, `ggplot2`, `survey`, `tableone`, `tibble`, `dplyr`, `tidyr`, `broom.mixed` and `jtools` packages are installed in your computer/R.
:::

::: callout-warning
**Bug Report**:

Fill out [this form](https://forms.gle/YSwuiebtb1E9wjHu9) to report any issues with the app.
:::
