## Formatting Tools {.unnumbered}

### LaTex

Get an account in ShareLaTeX/[Overleaf](https://v2.overleaf.com/login).

### Table conversion 

From MS word to latex / markdown / HTML in [TablesGenerator](http://www.tablesgenerator.com/).

You can use `tableone` package to generate csv file, and then import them in the TablesGenerator to convert to HTML to paste to doc file!

```{r, eval=FALSE}
tab1x <- print(tab1, quote = FALSE, noSpaces = TRUE, printToggle = FALSE)
write.csv(tab1x, file = "tab1x.csv")
```

#### Fancy table and chart generators:

R Packages 

- officer
- officedown
- flextable
- mschart

### Drawing flow chart

[draw.io](https://www.draw.io/.)

### Find appropriate journals

- [jane](http://jane.biosemantics.org)
- See more extensive list [here](https://ehsanx.github.io/Scientific-Writing-for-Health-Research/finding-suitable-journals.html)
- Specific [Epidemiology-focus journals](https://ehsanx.github.io/choosing-epidemiological-journals/)

### Gantt charts

[officetimeline](https://online.officetimeline.com/)

### Simultaneous collaborative writing

Google Docs offers a platform for real-time collaborative writing. Multiple users can edit documents simultaneously, and changes are saved automatically.

- Commenting and Suggesting: Use the comment and suggest features to provide feedback without altering the original text.
- Revision History: Navigate through the revision history to view changes and revert to previous versions if needed.
- Sharing and Permissions: Manage who can view, comment, or edit the document with varied permission levels.

### Reference manager

[Zotero](https://www.zotero.org/) stands out as a free, open-source reference management software that assists researchers, academics, and students in organizing, managing, and formatting their citations and bibliographies. It's not just a reference manager but also a powerful tool for collaborative work on research projects. Try the [Zotero desktop manager](https://www.zotero.org/download/) as well for assisting with reference inserting.

Zotero syncs data across devices, ensuring that users can access their libraries from any location. Users can work offline with Zotero, and any changes made will be synchronized when the internet connection is restored.

[ZoteroBib](https://zbib.org/): Use ZoteroBib to generate bibliographies instantly without creating an account or installing software.