## R for research question {.unnumbered}

The list of new R functions introduced in this *Research question* lab component are below:

|   Function name | Package name | Use | Chapters |
|   -------- | -------- | -------- | -------- |
| as.data.frame	| base	| To force an object to a data frame	| NHANES data	|
| as.formula	| base/stats	| To specify a model formula, e.g., formula for an outcome model	| NHANES data	|
| confint	| base/stats	| To estimate the confidence interval for model parameters	| NHANES data	|
| degf	| survey	| To see the degrees of freedom for a survey design object	| NHANES data	|
| describe	| DescTools	| To see the summary statistics of variables	| RHC data	|
| exp	| base	| Exponentials	| NHANES data	|
| lapply	| base	| To apply a function over a list, e.g., to see the summary of a list of variables or to convert a list of categorical variables to factor variables. A similar function is `sapply`. lapply and sapply have the same functionality. The main difference is that sapply attempts to convert the result into a vector or matrix, while lapply returns a list.	| RHC data	|
| length	| base	| To see the length of an object, e.g., number of elements/observations of a variable	| NHANES data	| 
| plot_missing	| DataExplorer	| To plot the profile of missing values, e.g., the percentage of missing per variable	| NHANES data	| 
| publish	| Publish	| To show/publish regression tables	| NHANES data	| 
| Reduce	| base	| To combine multiple objects, e.g., datasets	| NHANES data	| 
| round	| base	| To round numeric values	| NHANES data	| 
| saveRDS	| base	| To save a single R object. Similarly, readDRS will read an R object	| RHC data	| 
| skim	| skimr	| To see the summary statistics of variables	| RHC data	| 
| svydesign	| survey	| To create a design for the survey data analysis	| NHANES data	| 
| svyglm	| survey	| To run design-adjusted generalized linear models	| NHANES data	| 
| unique	| base	| To see the number of unique elements	| NHANES data	| 
| weights	| base/stats	| To extract model weights, e.g., see the weights from a pre-specified survey design	| NHANES data	|

: {.striped .hover}
