# Research questions

## Background

When we are starting a research project, one of the first steps is to clearly define your research topic or question. We will primarily focus on two types of research questions:

(a) predictive (predictors predicting one outcome)
(b) associational or causal (association between an outcome and an exposure, adjusting for confounders and risk factors for the outcome).

::: callout-important
**Datasets**:

All of the datasets used in this tutorial can be accessed from [this GitHub repository folder](https://github.com/ehsanx/EpiMethods/tree/main/Data/researchquestion)
:::

## Overview of tutorials

### Predictive questions

::: column-margin
In the [previous chapter](accessing.html), we learned about how to access external data. In this chapter, we have embarked on a journey to understand the nuances of different research questions, laying the groundwork for the topics that lie ahead. As we move forward, the next chapter will delve deeper into the challenges associated with [causal questions](confounding.html). We will explore the complexities of causal associations and discuss the optimal types of variables to include in adjustment models for accurate treatment effect estimation. Following that, we will transition to a chapter dedicated entirely to [predictive](predictivefactors.html) questions, shedding light on their unique attributes and the methodologies best suited for addressing them. Join us as we navigate these intricate terrains of research inquiry.
:::

#### [RHC Data](researchquestion1.html)

The [first tutorial](researchquestion1.html) serves to educate the user on how to utilize the RHC dataset to answer a **predictive** research question: developing a prediction model for the length of stay. The tutorial equips users with the skills to clean and process raw data, transforming it into an analyzable format, and introduces concepts that will be foundational for subsequent analysis.

#### Data from NHANES [Part 1: prepare data](researchquestion2a.html) [Part 2: work with data](researchquestion2b.html)

The second tutorial ([part a for downloading](researchquestion2a.html) and [part b for analyzing](researchquestion2b.html)) provides an in-depth guide on how to build a **predictive** model for Diastolic blood pressure using the NHANES dataset for the years 2013-14.

### Causal questions

#### [Data from CCHS](researchquestion3.html)

The [third tutorial](researchquestion3.html) aims to guide a study on the relationship between Osteoarthritis (OA) and cardiovascular diseases (CVD) among Canadian adults from 2001-2005. Utilizing the Canadian Community Health Survey (CCHS) cycle 1.1-3.1, the study intends to explore whether OA **increases** (more accurately, whether **associated** with) the risk of developing CVD.

#### [Data from NHANES](researchquestion4.html)

The NHANES dataset was analyzed in this [forth tutorial](researchquestion4.html) to explore the relationship between health predictors and cholesterol levels (**association/causal**). After refining the survey design and handling missing data, regression models were built using varying predictors. Standard error computations and p-values were derived, adjusting for the survey's unique structure.

::: callout-tip
**Optional Content**:

You will find that some sections conclude with an optional video walkthrough that demonstrates the code. Keep in mind that the content might have been updated since these videos were recorded. Watching these videos is optional.
:::

::: callout-warning
**Bug Report**:

Fill out [this form](https://forms.gle/YSwuiebtb1E9wjHu9) to report any issues with the tutorial.
:::

**Reference**
