## Quiz on wrangling {.unnumbered}

1. **Downloading the File:**
   - Navigate to the link: [See here](Quiz/QuizWrangling.Rmd).
   - Right-click on the link and select "Save link as..." from the dropdown menu.
   - Alternatively <a href="Quiz/QuizWrangling.Rmd" download>click here</a> for downloading the quizzes on data wrangling.
   - Choose a destination folder on your computer where you'd like to save the file (e.g., Desktop). **Remember this location**, as you'll need to navigate to it later.

2. **Setting Up RStudio:**
   - If you don't have RStudio installed, see the download link in [here](wrangling1a.html).
   - Launch RStudio after installing.

3. **Installing Necessary R Packages:**
   - Before running the R Markdown file, ensure you have the required packages. In RStudio's console (located at the bottom left by default), enter the following commands to install them:
     ```R
     install.packages("learnr")
     install.packages("xfun")
     ```

4. **Opening and Running the File:**
   - In RStudio, go to `File` > `Open File...`.
   - Navigate to the folder where you saved the `Rmd` file and select it to open.
   - Once the file is open in RStudio, you'll see a "Run Document" button (green) at the top of the script editor. Click on it to run the R Markdown Quiz file.
