## R Functions (W) {.unnumbered}

::: {.callout-note}
This review/summary page provides an extensive list of R functions tailored for data wrangling tasks that we have used in this chapter. Each function is systematically described, highlighting its primary package source and its specific utility.
:::

To learn more about these functions, readers can:

1.  **Use R's Built-in Help System**: For each function, access its documentation by prefixing the function name with a question mark in the R console, e.g., `?as.factor`. This displays the function's manual page with descriptions, usage, and examples.

2.  **Search Websites**: Simply [Google](https://www.google.com/search?q=as.factor+in+R), or visit the [CRAN website](https://cran.r-project.org/) to search for specific function documentation. Websites like [Stack Overflow](https://stackoverflow.com/) and [RStudio Community](https://community.rstudio.com/) often have discussions related to R functions.

3.  **Tutorials and Online Courses**: Platforms like DataCamp, Coursera, and edX offer R courses that cover many functions in depth. Also there are examples of dedicated R tutorial websites that you might find useful. One example is ["Introduction to R for health data analysis"](https://ehsanx.github.io/intro2R/) by Ehsan Karim, An Hoang and Qu.

4.  **Books**: There are numerous R programming books, such as ["R for Data Science"](https://r4ds.had.co.nz/) by Hadley Wickham and ["The Art of R Programming"](https://nostarch.com/artofr.htm) by Norman Matloff.

5.  **Workshops and Webinars**: Institutions and organizations occasionally offer R programming workshops or webinars.

Whenever in doubt, exploring existing resources can be highly beneficial.

```{r, echo=FALSE, warning=FALSE,message=FALSE}
library(knitr)
library(kableExtra)

data <- data.frame(
  Function_name = c("as.factor", "cbind", "CreateTableOne", "data.frame", "dim", "filter", "function", "head", "is.na", "levels", "list", "mode", "na.omit", "names", "nlevels", "nrow", "plot", "print", "prop.table", "rbind", "read.csv", "relevel", "sasxport.get", "save", "select", "set.seed", "str", "subset", "summary", "table", "write.csv"),
  Package_name = c("base", "base", "tableone", "base", "base", "dplyr", "base", "base", "base", "base", "base", "base", "base/stats", "base", "base", "base", "base/graphics", "base", "base", "base", "base/utils", "base/stats", "Hmisc", "base", "dplyr", "base", "base/utils", "base, dplyr", "base", "base", "base/utils"),
  Use = c(
  "Converts a variable to factors. `as.factor` is a wrapper for the `factor` function.",
  "Merges matrices.",
  "Creates a frequency table.",
  "Creates a dataset with both numeric and character variables. Requires unique column names and equal length for all variables.",
  "Returns the dimensions of a data frame (rows x columns).",
  "Subsets a dataset by selecting a sub-population.",
  "Used to define custom functions, e.g., for calculating standard deviation.",
  "Displays the first six elements of an object (e.g., a dataset). `tail` displays the last six.",
  "Checks for missing values in a variable.",
  "Displays the levels of a factor variable.",
  "Stores vectors, matrices, or lists of differing types.",
  "Determines the type of a variable.",
  "Removes all rows with missing values from a dataset.",
  "Displays names of objects, e.g., variable names of a data frame.",
  "Shows the number of levels in a factor variable.",
  "Returns the dimensions of a data frame. `nrow` gives row count and `ncol` gives column count.",
  "Draws scatter plots or line graphs.",
  "Prints the output to console.",
  "Displays percentage summary for a table.",
  "Appends matrices row-wise.",
  "Reads data from a CSV file.",
  "Changes the reference group of a factor variable.",
  "Loads data in the SAS format.",
  "Saves R objects, such as datasets.",
  "Selects specified variables from a dataset.",
  "Sets a seed for random number generation ensuring reproducibility.",
  "Displays the structure of a dataset, including data type of variables.",
  "Subsets a dataset by selecting a sub-population.",
  "Provides a summary of an object, like variable statistics.",
  "Displays frequency counts for a variable.",
  "Saves a data frame to a CSV file in a specified directory."
)
)

kable(data, format = "html", escape = F, table.attr = 'class="table table-hover"') %>%
  kable_styling(bootstrap_options = c("striped", "hover"), full_width = F) %>%
  column_spec(1, bold = T) %>%
  column_spec(2, color = "blue") %>%
  column_spec(3, italic = T) %>%
  scroll_box(width = "100%", height = "500px")

```
