---
title: "Quiz on data wrangling"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, warning=FALSE, message=FALSE, include=FALSE}
# Load required packages
library(learnr)
library(xfun)
```

```{r wrangling_quiz1, echo=FALSE}
question("What is the purpose of the RStudio IDE mentioned in the text?",
  answer("It is used to download and install the latest version of R."),
  answer("It is used to create and save R scripts."),
  answer("It is used to run R codes and view outputs.", correct = TRUE),
  answer("It is used to generate random numbers from the normal distribution."),
  allow_retry = TRUE,
  incorrect = "Incorrect. See R basics for help.",
  random_answer_order = TRUE
)
```

```{r wrangling_quiz2, echo=FALSE}
question("How can you change the column names of a data frame called df to 'ID', 'Age', and 'Sex' in R?",
  answer("names(df) <- c('ID', 'Age', 'Sex')"),
  answer("colnames(df) <- c('ID', 'Age', 'Sex')", correct = TRUE),
  answer("df$names <- c('ID', 'Age', 'Sex')"),
  answer("df$colnames <- c('ID', 'Age', 'Sex')"),
  allow_retry = TRUE,
  incorrect = "Incorrect. See R basics on how to change the name of the variables/columns in a data frame.",
  random_answer_order = TRUE
)
```

```{r wrangling_quiz3, echo=FALSE}
question("What is the use of `header = TRUE` in `read.table` function?",
  answer("To treat the first coulmn as the names of the variables"),
  answer("To read the names of the variables as the first row", correct = TRUE),
  answer("To read the variables as numeric"),
  answer("To save the variables"),
  allow_retry = TRUE,
  incorrect = "Incorrect. See the help function for `read.table`. ",
  random_answer_order = TRUE
)
```

```{r wrangling_quiz4, echo=FALSE}
question("How can you keep only the variables 'trans', 'cty', and 'drv' of a data frame named dat? (select ALL that apply)",
  answer("mydat <- dat[, c('trans', 'cty', 'drv')]", correct = TRUE),
  answer("mydat <- dat[c('trans', 'cty', 'drv'), ]"),
  answer("mydat <- dplyr::select(dat, -c('trans', 'cty', 'drv'))"),
  answer("mydat <- dplyr::select(dat, c('trans', 'cty', 'drv'))", correct = TRUE),
  allow_retry = TRUE,
  incorrect = "Hints: There are multiple ways to do the same task. We might use the base R or a package (e.g., dplyr) to keep the desired variables. Hence, there could be multiple answers. Select all that apply. For more help, see the 'Data manipulation' section.",
  random_answer_order = FALSE
)
```

```{r wrangling_quiz5, echo=FALSE}
question("Which R function could be used to convert a continuous variable to a categorical variable? (select ALL that apply)",
  answer("`summary` from base R"),
  answer("`cut` from base R", correct = TRUE),
  answer("`ifelse` from base R", correct = TRUE),
  answer("`recode` from car package", correct = TRUE),
  answer("`table` from base R"),
  answer("`relevel` from base R"),
  allow_retry = TRUE,
  incorrect = "Hints: There could be multiple answers. Select all that apply. For more help, see the 'Data manipulation' section.",
  random_answer_order = TRUE
)
```
