---
title: "Quiz on reporting guidelines"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, warning=FALSE, message=FALSE, include=FALSE}
# Load required packages
library(learnr)
library(xfun)
```

```{r reporting_quiz1, echo=FALSE}
question("",
  answer(""),
  answer(""),
  answer("", correct = TRUE),
  answer(""),
  incorrect = "",
  allow_retry = TRUE,
  random_answer_order = TRUE
)
```

```{r reporting_quiz2, echo=FALSE}
question("",
  answer(""),
  answer(""),
  answer("", correct = TRUE),
  answer(""),
  incorrect = "",
  allow_retry = TRUE,
  random_answer_order = TRUE
)
```

```{r reporting_quiz3, echo=FALSE}
question("",
  answer(""),
  answer(""),
  answer("", correct = TRUE),
  answer(""),
  incorrect = "",
  allow_retry = TRUE,
  random_answer_order = TRUE
)
```

```{r reporting_quiz4, echo=FALSE}
question("",
  answer(""),
  answer(""),
  answer("", correct = TRUE),
  answer(""),
  incorrect = "",
  allow_retry = TRUE,
  random_answer_order = TRUE
)
```

```{r reporting_quiz5, echo=FALSE}
question("",
  answer(""),
  answer(""),
  answer("", correct = TRUE),
  answer(""),
  incorrect = "",
  allow_retry = TRUE,
  random_answer_order = TRUE
)
```
