{
  "hash": "3e31317af8a1d90b1403cb2281ab1b6c",
  "result": {
    "markdown": "## Subpopulations {.unnumbered}\n\nThis tutorial demonstrates how to manage missing data in complex surveys using multiple imputation, focusing on specific subpopulations defined by the study's eligibility criteria.\n\n### Purpose\n\nLet us we are interested in exploring the relationship between **rheumatoid arthritis** and **cardiovascular disease** (CVD) among US adults aged 20 years or more. For that, we will use NHANES 2017--2018 dataset, which follows a complex survey design.\n\n::: column-margin\nIn this tutorial, we used a similar approach to the one in a published article by @hossain2022association, but we used less data (restricted to only 2017--2018) to speed up the analysis. [Ref link](https://pubmed.ncbi.nlm.nih.gov/35301105/).\n:::\n\nThe purpose of this example is to *demonstrate how to do the missing data analysis with multiple imputation in the context of complex surveys*.\n\nThe main idea is:\n\n-   working with the analytic data\n-   imputing missing values based on that analytic dataset\n-   keep count of the ineligible subjects from the full data who are not included in the analytic data\n-   adding those ineligible subjects back in the imputed datasets, so that we can utilize the survey features and subset the design.\n\n\n::: {.cell hash='missingdata5_cache/html/setup_42797e97e7265e4ac5182b98ba8c0147'}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(dplyr)\nlibrary(kableExtra)\nlibrary(tableone)\nlibrary(survey)\nlibrary(Publish)\nlibrary(DataExplorer)\nlibrary(mice)\nlibrary(mitools)\n```\n:::\n\n\nLet us import the dataset:\n\n\n::: {.cell hash='missingdata5_cache/html/load_ba74cf765d6bee3d0d3fc1afa4673f12'}\n\n```{.r .cell-code}\nload(\"Data/missingdata/MIexample.RData\")\nls()\n#> [1] \"dat.full\"\n```\n:::\n\n::: {.cell hash='missingdata5_cache/html/data_c75aef60a37fe2cc92080ac80c1dda5b'}\n\n```{.r .cell-code}\ndim(dat.full)\n#> [1] 9254   15\nhead(dat.full)\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"studyid\"],\"name\":[1],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"survey.weight\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"psu\"],\"name\":[3],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"strata\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"cvd\"],\"name\":[5],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"rheumatoid\"],\"name\":[6],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"age\"],\"name\":[7],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"sex\"],\"name\":[8],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"education\"],\"name\":[9],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"race\"],\"name\":[10],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"income\"],\"name\":[11],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"bmi\"],\"name\":[12],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"smoking\"],\"name\":[13],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"htn\"],\"name\":[14],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"diabetes\"],\"name\":[15],\"type\":[\"fct\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"93703\",\"2\":\"9246.492\",\"3\":\"2\",\"4\":\"145\",\"5\":\"NA\",\"6\":\"NA\",\"7\":\"2\",\"8\":\"Female\",\"9\":\"NA\",\"10\":\"Others\",\"11\":\"$75,000 and Over\",\"12\":\"17.5\",\"13\":\"NA\",\"14\":\"NA\",\"15\":\"No\",\"_rn_\":\"1\"},{\"1\":\"93704\",\"2\":\"37338.768\",\"3\":\"1\",\"4\":\"143\",\"5\":\"NA\",\"6\":\"NA\",\"7\":\"2\",\"8\":\"Male\",\"9\":\"NA\",\"10\":\"White\",\"11\":\"$75,000 and Over\",\"12\":\"15.7\",\"13\":\"NA\",\"14\":\"NA\",\"15\":\"No\",\"_rn_\":\"2\"},{\"1\":\"93705\",\"2\":\"8614.571\",\"3\":\"2\",\"4\":\"145\",\"5\":\"No\",\"6\":\"Yes\",\"7\":\"66\",\"8\":\"Female\",\"9\":\"Less than high school\",\"10\":\"Black\",\"11\":\"less than $20,000\",\"12\":\"31.7\",\"13\":\"Previous smoker\",\"14\":\"Yes\",\"15\":\"No\",\"_rn_\":\"3\"},{\"1\":\"93706\",\"2\":\"8548.633\",\"3\":\"2\",\"4\":\"134\",\"5\":\"NA\",\"6\":\"NA\",\"7\":\"18\",\"8\":\"Male\",\"9\":\"NA\",\"10\":\"Others\",\"11\":\"NA\",\"12\":\"21.5\",\"13\":\"Never smoker\",\"14\":\"No\",\"15\":\"No\",\"_rn_\":\"4\"},{\"1\":\"93707\",\"2\":\"6769.345\",\"3\":\"1\",\"4\":\"138\",\"5\":\"NA\",\"6\":\"NA\",\"7\":\"13\",\"8\":\"Male\",\"9\":\"NA\",\"10\":\"Others\",\"11\":\"$20,000 to $74,999\",\"12\":\"18.1\",\"13\":\"NA\",\"14\":\"Yes\",\"15\":\"No\",\"_rn_\":\"5\"},{\"1\":\"93708\",\"2\":\"13329.451\",\"3\":\"2\",\"4\":\"138\",\"5\":\"No\",\"6\":\"NA\",\"7\":\"66\",\"8\":\"Female\",\"9\":\"Less than high school\",\"10\":\"Others\",\"11\":\"$20,000 to $74,999\",\"12\":\"23.7\",\"13\":\"Never smoker\",\"14\":\"Yes\",\"15\":\"No\",\"_rn_\":\"6\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nThe dataset (`dat.full`) contains 9,254 subjects with 15 variables:\n\n**Survey information**\n\n-   `studyid`: Respondent sequence number\n-   `survey.weight`: Full sample 2 year interview weight\n-   `psu`: Masked pseudo PSU\n-   `strata`: Masked pseudo strata\n\n**Outcome variable**\n\n-   `cvd`: Whether having cardiovascular disease\n\n**Exposure variable**\n\n-   `rheumatoid`: Whether having rheumatoid arthritis\n\n**Covariates**\n\n-   `age`: age in years at screening\n-   `sex`\n-   `education`\n-   `race`: Race/Ethnicity\n-   `income`: Family income in \\$\n-   `bmi`: Body Mass Index in kg/m$^2$\n-   `smoking`: Smoking status\n-   `htn`: Having hypertension\n-   `diabetes`: Having diabetes\n\n### Analytic dataset\n\n#### Subsetting according to eligibility\n\nLet us create an analytic dataset for\n\n-   adults aged 20 years or more\n-   without missing values in outcome (cvd) or exposure (rheumatoid arthritis).\n\n\n::: {.cell hash='missingdata5_cache/html/analytic0_6b2a3e0020294586755b261fa4f70093'}\n\n```{.r .cell-code}\n# Drop < 20 years\ndat.with.miss <- subset(dat.full, age >= 20)\n\n# Frequency for outcome and exposure \ntable(dat.with.miss$cvd, useNA = \"always\") # 6 missing\n#> \n#>   No  Yes <NA> \n#> 4872  691    6\ntable(dat.with.miss$rheumatoid, useNA = \"always\") # 1375 missing\n#> \n#>   No  Yes <NA> \n#> 3857  337 1375\n\n# Drop missing in outcome and exposure \n# i.e., dataset with missing values only in covariates\ndat.analytic <- dat.with.miss[complete.cases(dat.with.miss$cvd),]\ndat.analytic <- dat.analytic[complete.cases(dat.analytic$rheumatoid),]\nnrow(dat.analytic)\n#> [1] 4191\n```\n:::\n\n\nAs we can see, we have 4,191 participants aged 20 years or more without missing values in outcome or exposure. Let us count the ineligible subjects from the full data and create an indicator variable.\n\n\n::: {.cell hash='missingdata5_cache/html/analytic1_a868dca770c8020cd9fb2389ff95aa31'}\n\n```{.r .cell-code}\ndat.full$ineligible <- 1\ndat.full$ineligible[dat.full$studyid %in% dat.analytic$studyid] <- 0\ntable(dat.full$ineligible, useNA = \"always\")\n#> \n#>    0    1 <NA> \n#> 4191 5063    0\n```\n:::\n\n\nWe have 4,191 eligible and 5,063 ineligible subjects based on the eligibility criteria.\n\n**General strategy of solution**:\n\n-   We will build the imputation model on 4,191 eligible subjects, and\n-   later we will include 5,063 ineligible subjects in the data so that we can utilize survey features.\n\n#### Table 1\n\nLet us see the summary statistics, i.e., create Table 1 stratified by outcome (cvd). Before that, we will categorize `age` and recode `rheumatoid`:\n\n\n::: {.cell hash='missingdata5_cache/html/analytic2_19116ac6876e6b0897995a28fd8c98b7'}\n\n```{.r .cell-code}\n# Categorical age\ndat.analytic$age.cat <- \n  with(dat.analytic, ifelse(age >= 20 & age < 50, \"20-49\", \n                            ifelse(age >= 50 & age < 65, \n                                   \"50-64\", \"65+\")))\ndat.analytic$age.cat <- factor(dat.analytic$age.cat, \n                               levels = c(\"20-49\", \"50-64\", \"65+\"))\ntable(dat.analytic$age.cat, useNA = \"always\")\n#> \n#> 20-49 50-64   65+  <NA> \n#>  2280  1097   814     0\n\n# Recode rheumatoid to arthritis\ndat.analytic$arthritis <- \ncar::recode(dat.analytic$rheumatoid, \" 'No' = 'No arthritis';\n            'Yes' = 'Rheumatoid arthritis' \", as.factor = T)\ntable(dat.analytic$arthritis, useNA = \"always\")\n#> \n#>         No arthritis Rheumatoid arthritis                 <NA> \n#>                 3854                  337                    0\n\n# Keep only relevant variables\nvars <-  c(\"studyid\", \"survey.weight\", \"psu\", \"strata\", \"cvd\",\n           \"arthritis\", \"age.cat\", \"sex\", \"education\", \"race\",\n           \"income\", \"bmi\", \"smoking\", \"htn\", \"diabetes\")\ndat.analytic2 <- dat.analytic[, vars]\n```\n:::\n\n::: {.cell hash='missingdata5_cache/html/tab1_661a11f9bb6f2dad51bce2b02365b2f7'}\n\n```{.r .cell-code}\n# Create Table 1\nvars <- c(\"arthritis\", \"age.cat\", \"sex\", \"education\", \"race\", \"income\", \"bmi\", \"smoking\",\n          \"htn\", \"diabetes\")\ntab1 <- CreateTableOne(vars = vars, strata = \"cvd\", \n                       data = dat.analytic2, includeNA = F,\n                       addOverall = T, test = F)\nprint(tab1, format = \"f\", showAllLevels = T)\n#>                  Stratified by cvd\n#>                   level                     Overall      No          \n#>   n                                          4191         3823       \n#>   arthritis       No arthritis               3854         3580       \n#>                   Rheumatoid arthritis        337          243       \n#>   age.cat         20-49                      2280         2240       \n#>                   50-64                      1097          979       \n#>                   65+                         814          604       \n#>   sex             Male                       2126         1884       \n#>                   Female                     2065         1939       \n#>   education       Less than high school       828          728       \n#>                   High school                2292         2094       \n#>                   College graduate or above  1063          993       \n#>   race            White                      1275         1113       \n#>                   Black                       998          898       \n#>                   Hispanic                   1015          958       \n#>                   Others                      903          854       \n#>   income          less than $20,000           659          557       \n#>                   $20,000 to $74,999         1967         1796       \n#>                   $75,000 and Over           1143         1079       \n#>   bmi (mean (SD))                           29.28 (7.19) 29.20 (7.18)\n#>   smoking         Never smoker               2570         2427       \n#>                   Previous smoker             882          726       \n#>                   Current smoker              739          670       \n#>   htn             No                         1424         1380       \n#>                   Yes                        2415         2107       \n#>   diabetes        No                         3622         3396       \n#>                   Yes                         566          424       \n#>                  Stratified by cvd\n#>                   Yes         \n#>   n                 368       \n#>   arthritis         274       \n#>                      94       \n#>   age.cat            40       \n#>                     118       \n#>                     210       \n#>   sex               242       \n#>                     126       \n#>   education         100       \n#>                     198       \n#>                      70       \n#>   race              162       \n#>                     100       \n#>                      57       \n#>                      49       \n#>   income            102       \n#>                     171       \n#>                      64       \n#>   bmi (mean (SD)) 30.09 (7.29)\n#>   smoking           143       \n#>                     156       \n#>                      69       \n#>   htn                44       \n#>                     308       \n#>   diabetes          226       \n#>                     142\n```\n:::\n\n\n#### Check missingness using a plot\n\nNow we will see the percentage of missing values in the variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDataExplorer::plot_missing(dat.analytic2)\n```\n\n::: {.cell-output-display}\n![](missingdata5_files/figure-html/miss0-1.png){width=80%}\n:::\n:::\n\n\nWe have about 10% missing values in income, followed by hypertension (8.4%), bmi (6.8%), education (0.2%), and diabetes (0.1%).\n\n### Dealing with missing values in covariates\n\n-   Now we will perform multiple imputation to deal with missing values only in covariates. We will use the `dat.analytic2` dataset that contains missing values in the covariates but no missing values in the outcome or exposure.\n-   For this exercise, we will consider 5 imputed datasets, 3 iterations, and the predictive mean matching method for bmi and income.\n    -   We have already set up the data such that the variables are of appropriate types, e.g., numeric bmi, factor age, sex, and so on.\n    -   We will use the strata variable as an auxiliary variable in the imputation model but not the survey weight or PSU variable.\n    -   Now we will set up the initial model and set up the methods and predictor matrix before imputing 5 datasets.\n\n#### Step 0: Set up the imputation model\n\n::: column-margin\nIn this tutorial, we used `stata` as an  auxiliary variable. There are two ways we can deal with this:\n\na) Use `strata` to predict other variables, but **don't impute** `strata`: `meth[\"strata\"] <- \"\"` (this skips strata's imputation). In our case, since `strata` has no missing observations, this step is unnecessary, as MICE will automatically not impute fully observed variables. However, this strategy is useful for blocking the imputation of auxiliary variables with missing data. \n\n- Also, do not change the `predictorMatrix` for auxiliary variables, allowing them (e.g., strata in our case) to be used as predictors for other variables.\n\n- Setting `pred[\"strata\", ] <- 0` would remove all predictors for `strata`, which means `strata` cannot be imputed because there are no variables to predict its missing values. However, `strata` can still be used as a predictor for other variables. If `strata` has no missing values (as in our case), this step is unnecessary since MICE does not attempt to impute fully observed variables.\n\nb) **Impute** `strata` and use it as a predictor (if strata had missing values): If `strata` had missing data, you wouldn't need to change anything in `predictorMatrix` or `method`. MICE would impute `strata` and use it as a predictor by default. In our case, since `strata` has no missing values, imputation is not necessary. Note that:\n\n- You should not set `pred[\"strata\", ] <- 1` because this would incorrectly make `strata` a predictor for itself, which is invalid. MICE automatically handles this by setting diagonal entries to 0, so you don't need to manually ensure this unless you've changed it. If you do so (set the row values to 1), you need to then set `pred[\"strata\", \"strata\"] <- 0` to ensure `strata` does not predict itself.\n\n- Do not use `pred[, \"strata\"] <- 0` because this would prevent `strata` from being used as a predictor for other variables, which is contrary to the idea of using it as an auxiliary variable.\n\nWhether to **impute or not impute auxiliary variables** depends on their role in the analysis and the potential impact of their missing data. If they are strong predictors or are necessary for future analyses, imputing them may be justified. However, if their missingness is not consequential, and imputing them introduces more noise or complexity, it may be better to leave them unimputed.\n:::\n\n\n::: {.cell hash='missingdata5_cache/html/step0_189ce433e8fc7fc3d02bfcbea37f4be7'}\n\n```{.r .cell-code}\n# Step 0: Set imputation model\nini <- mice(data = dat.analytic2, maxit = 0, print = FALSE)\npred <- ini$pred\n\nkable(pred)\n```\n\n::: {.cell-output-display}\n|              | studyid| survey.weight| psu| strata| cvd| arthritis| age.cat| sex| education| race| income| bmi| smoking| htn| diabetes|\n|:-------------|-------:|-------------:|---:|------:|---:|---------:|-------:|---:|---------:|----:|------:|---:|-------:|---:|--------:|\n|studyid       |       0|             1|   1|      1|   1|         1|       1|   1|         1|    1|      1|   1|       1|   1|        1|\n|survey.weight |       1|             0|   1|      1|   1|         1|       1|   1|         1|    1|      1|   1|       1|   1|        1|\n|psu           |       1|             1|   0|      1|   1|         1|       1|   1|         1|    1|      1|   1|       1|   1|        1|\n|strata        |       1|             1|   1|      0|   1|         1|       1|   1|         1|    1|      1|   1|       1|   1|        1|\n|cvd           |       1|             1|   1|      1|   0|         1|       1|   1|         1|    1|      1|   1|       1|   1|        1|\n|arthritis     |       1|             1|   1|      1|   1|         0|       1|   1|         1|    1|      1|   1|       1|   1|        1|\n|age.cat       |       1|             1|   1|      1|   1|         1|       0|   1|         1|    1|      1|   1|       1|   1|        1|\n|sex           |       1|             1|   1|      1|   1|         1|       1|   0|         1|    1|      1|   1|       1|   1|        1|\n|education     |       1|             1|   1|      1|   1|         1|       1|   1|         0|    1|      1|   1|       1|   1|        1|\n|race          |       1|             1|   1|      1|   1|         1|       1|   1|         1|    0|      1|   1|       1|   1|        1|\n|income        |       1|             1|   1|      1|   1|         1|       1|   1|         1|    1|      0|   1|       1|   1|        1|\n|bmi           |       1|             1|   1|      1|   1|         1|       1|   1|         1|    1|      1|   0|       1|   1|        1|\n|smoking       |       1|             1|   1|      1|   1|         1|       1|   1|         1|    1|      1|   1|       0|   1|        1|\n|htn           |       1|             1|   1|      1|   1|         1|       1|   1|         1|    1|      1|   1|       1|   0|        1|\n|diabetes      |       1|             1|   1|      1|   1|         1|       1|   1|         1|    1|      1|   1|       1|   1|        0|\n:::\n\n```{.r .cell-code}\n\n# Use the strata variable as an auxiliary variable in the imputation model\npred[\"strata\",]\n#>       studyid survey.weight           psu        strata           cvd \n#>             1             1             1             0             1 \n#>     arthritis       age.cat           sex     education          race \n#>             1             1             1             1             1 \n#>        income           bmi       smoking           htn      diabetes \n#>             1             1             1             1             1\n# Do not change the pred matrix for strata. \n# This allows strata to be used as a predictor for other variables.\n\n# Do not use id, survey weight or PSU variable as auxiliary variables\npred[, c(\"studyid\", \"psu\", \"survey.weight\")] <- 0\n# Remove them as predictors for other variables\n\nkable(pred)\n```\n\n::: {.cell-output-display}\n|              | studyid| survey.weight| psu| strata| cvd| arthritis| age.cat| sex| education| race| income| bmi| smoking| htn| diabetes|\n|:-------------|-------:|-------------:|---:|------:|---:|---------:|-------:|---:|---------:|----:|------:|---:|-------:|---:|--------:|\n|studyid       |       0|             0|   0|      1|   1|         1|       1|   1|         1|    1|      1|   1|       1|   1|        1|\n|survey.weight |       0|             0|   0|      1|   1|         1|       1|   1|         1|    1|      1|   1|       1|   1|        1|\n|psu           |       0|             0|   0|      1|   1|         1|       1|   1|         1|    1|      1|   1|       1|   1|        1|\n|strata        |       0|             0|   0|      0|   1|         1|       1|   1|         1|    1|      1|   1|       1|   1|        1|\n|cvd           |       0|             0|   0|      1|   0|         1|       1|   1|         1|    1|      1|   1|       1|   1|        1|\n|arthritis     |       0|             0|   0|      1|   1|         0|       1|   1|         1|    1|      1|   1|       1|   1|        1|\n|age.cat       |       0|             0|   0|      1|   1|         1|       0|   1|         1|    1|      1|   1|       1|   1|        1|\n|sex           |       0|             0|   0|      1|   1|         1|       1|   0|         1|    1|      1|   1|       1|   1|        1|\n|education     |       0|             0|   0|      1|   1|         1|       1|   1|         0|    1|      1|   1|       1|   1|        1|\n|race          |       0|             0|   0|      1|   1|         1|       1|   1|         1|    0|      1|   1|       1|   1|        1|\n|income        |       0|             0|   0|      1|   1|         1|       1|   1|         1|    1|      0|   1|       1|   1|        1|\n|bmi           |       0|             0|   0|      1|   1|         1|       1|   1|         1|    1|      1|   0|       1|   1|        1|\n|smoking       |       0|             0|   0|      1|   1|         1|       1|   1|         1|    1|      1|   1|       0|   1|        1|\n|htn           |       0|             0|   0|      1|   1|         1|       1|   1|         1|    1|      1|   1|       1|   0|        1|\n|diabetes      |       0|             0|   0|      1|   1|         1|       1|   1|         1|    1|      1|   1|       1|   1|        0|\n:::\n:::\n\n\n::: column-margin\n- The rows represent the variables that can be imputed. The entries in each row show which variables will be used as predictors to impute the variable corresponding to that row.\n - The columns represent the variables that can be used as predictors to impute other variables. An entry of 1 in a cell means that the corresponding variable (from the column) will be used to predict the variable represented by the row.\n - `pred[, c(\"studyid\", \"psu\", \"survey.weight\")] <- 0` action sets all values in the columns for `studyid`, `psu`, and `survey.weight` to 0. Effectively, it tells MICE not to use them as predictors when imputing other variables. In other words, these variables will not be used to predict missing values in other variables.\n::: \n\n\n::: {.cell hash='missingdata5_cache/html/step0a_8e566d7cb2d3f1a9bc1cc2734821a07f'}\n\n```{.r .cell-code}\n# Set imputation method\nmeth <- ini$meth\nmeth[\"bmi\"] <- \"pmm\"\nmeth[\"income\"] <- \"pmm\"\nmeth\n#>       studyid survey.weight           psu        strata           cvd \n#>            \"\"            \"\"            \"\"            \"\"            \"\" \n#>     arthritis       age.cat           sex     education          race \n#>            \"\"            \"\"            \"\"     \"polyreg\"            \"\" \n#>        income           bmi       smoking           htn      diabetes \n#>         \"pmm\"         \"pmm\"            \"\"      \"logreg\"      \"logreg\"\nmeth[\"strata\"] # method used for strata to be imputed\n#> strata \n#>     \"\"\n# meth[\"strata\"] <- \"\" # you can skip auxiliary variable's imputation\n# Modify the method to skip imputation of \"studyid\", \"psu\", and \"survey.weight\"\nmeth[\"studyid\"] <- \"\"\nmeth[\"psu\"] <- \"\"\nmeth[\"survey.weight\"] <- \"\"\nmeth\n#>       studyid survey.weight           psu        strata           cvd \n#>            \"\"            \"\"            \"\"            \"\"            \"\" \n#>     arthritis       age.cat           sex     education          race \n#>            \"\"            \"\"            \"\"     \"polyreg\"            \"\" \n#>        income           bmi       smoking           htn      diabetes \n#>         \"pmm\"         \"pmm\"            \"\"      \"logreg\"      \"logreg\"\n```\n:::\n\n\n-   There is no missing for studyid, survey.weight, psu, strata, cvd, arthritis, age, sex, race, smoking. Hence, no method is assigned for these variables.\n-   For education, `polyreg` (Polytomous logistic regression) will be used.\n-   Similarly, we will use `pmm` (Predictive mean matching) for bmi, income and used `logreg` (Logistic regression) for htn, diabetes. See the [Imputation](missingdata1.html) chapter to see how the PMM method works.\n\n#### Step 1: Imputing missing values using mice\n\n##### 1.1 Imputing dataset for eligible subjects\n\n\n::: {.cell hash='missingdata5_cache/html/step1a_343025e8907ecc9b42fdaf9f3ccf3897'}\n\n```{.r .cell-code}\n# Step 1: impute the incomplete data\nimputation <- mice(data = dat.analytic2,\n                   seed = 123,\n                   predictorMatrix = pred,\n                   method = meth,\n                   m = 5,\n                   maxit = 3,\n                   print = FALSE)\n```\n:::\n\n\nNow we will combine m = 5 datasets and create a stacked dataset. This dataset should contain 5\\*4,191 = 20,955 rows.\n\n\n::: {.cell hash='missingdata5_cache/html/step1b_371bbf00355780283d1b7f4725c9933d'}\n\n```{.r .cell-code}\nimpdata <- mice::complete(imputation, action=\"long\")\n\ntable(impdata$age.cat)\n#> \n#> 20-49 50-64   65+ \n#> 11400  5485  4070\n```\n:::\n\n\nNote that age has no missing values, and everyone is above 20.\n\n\n::: {.cell hash='missingdata5_cache/html/step1c_df3d8aa12bebe7b4c4d3cba774f7342a'}\n\n```{.r .cell-code}\n#Remove .id variable from the model as it was created in an intermediate step\nimpdata$.id <- NULL\n\n# Create an indicator of eligible subjects \nimpdata$ineligible <- 0\n\n# Number of subjects\nnrow(impdata)\n#> [1] 20955\n```\n:::\n\n\nLet's see whether there is any missing value after imputation:\n\n\n::: {.cell hash='missingdata5_cache/html/step1d_339d22a2e246262fc8ba4797b82b3345'}\n\n```{.r .cell-code}\nDataExplorer::plot_missing(impdata)\n```\n\n::: {.cell-output-display}\n![](missingdata5_files/figure-html/step1d-1.png){width=672}\n:::\n:::\n\n\n-   There is no missing value after imputation.\n-   As we can see, there is an additional variable (`.imp`) in the imputed dataset. This `.imp` goes from 1 to m = 5, indicating the first to the fifth imputed datasets.\n\n##### 1.2 Preparing dataset for ineligible subjects\n\nThe next task is adding the **ineligible subjects** in the imputed datasets, so that we can set up the survey design on the full dataset and then subset the design.\n\n\n::: {.cell hash='missingdata5_cache/html/step1e_f89f3c3d5399e11b4eb0c9cc493c69ad'}\n\n```{.r .cell-code}\n# Number of ineligible subjects\n#dat.full$ineligible <- 1\n#dat.full$ineligible[dat.full$studyid %in% dat.analytic$studyid] <- 0\ntable(dat.full$ineligible, useNA = \"always\")\n#> \n#>    0    1 <NA> \n#> 4191 5063    0\n```\n:::\n\n\nNow we will subset the data for ineligible subjects and create `m = 5` copies.\n\n\n::: {.cell hash='missingdata5_cache/html/step1f_83d34d75c94e80736bf0e3ca4bcdbfd6'}\n\n```{.r .cell-code}\n# Subset for ineligible\ndat.ineligible <- subset(dat.full, ineligible == 1)\n\n# Create m = 5 datasets with .imp 1 to m = 5\ndat31 <- dat.ineligible; dat31$.imp <- 1\ndat32 <- dat.ineligible; dat32$.imp <- 2\ndat33 <- dat.ineligible; dat33$.imp <- 3\ndat34 <- dat.ineligible; dat34$.imp <- 4\ndat35 <- dat.ineligible; dat35$.imp <- 5\n```\n:::\n\n\nThe next step is combining ineligible datasets. Before merging the `stacked dataset for ineligible subjects` to the `imputed stacked dataset for eligible subjects,` we must ensure the variable names are the same.\n\n\n::: {.cell hash='missingdata5_cache/html/step1g_e8c52cc5cbe8a10e86f8914464c423fe'}\n\n```{.r .cell-code}\n# Stacked data for ineligible subjects\ndat.ineligible.stacked <- rbind(dat31, dat32, dat33, dat34, dat35)\n```\n:::\n\n\nWe should have missing value in this ineligible part of the data:\n\n\n::: {.cell hash='missingdata5_cache/html/step1h_ab595b1094e2f32b43c2990fd012212c'}\n\n```{.r .cell-code}\nDataExplorer::plot_missing(dat.ineligible.stacked)\n```\n\n::: {.cell-output-display}\n![](missingdata5_files/figure-html/step1h-1.png){width=672}\n:::\n:::\n\n\n##### 1.3 Combining eligible (imputed) and ineligible (unimputed) subjects\n\n\n::: {.cell hash='missingdata5_cache/html/step1i_e13df16d249ba291cca6ccb72af3a18f'}\n\n```{.r .cell-code}\nnames(impdata)\n#>  [1] \"studyid\"       \"survey.weight\" \"psu\"           \"strata\"       \n#>  [5] \"cvd\"           \"arthritis\"     \"age.cat\"       \"sex\"          \n#>  [9] \"education\"     \"race\"          \"income\"        \"bmi\"          \n#> [13] \"smoking\"       \"htn\"           \"diabetes\"      \".imp\"         \n#> [17] \"ineligible\"\n```\n:::\n\n::: {.cell hash='missingdata5_cache/html/step1j_23fb9e35a454d0c789587c2d3b6857f3'}\n\n```{.r .cell-code}\nnames(dat.ineligible.stacked)\n#>  [1] \"studyid\"       \"survey.weight\" \"psu\"           \"strata\"       \n#>  [5] \"cvd\"           \"rheumatoid\"    \"age\"           \"sex\"          \n#>  [9] \"education\"     \"race\"          \"income\"        \"bmi\"          \n#> [13] \"smoking\"       \"htn\"           \"diabetes\"      \"ineligible\"   \n#> [17] \".imp\"\n```\n:::\n\n\nAs we can see, the variable names are different in the two datasets. Particularly, `arthritis` and `age.cat` variables are not available in the `dat.ineligible.stacked` dataset. Now we will recode these variables in the same format as done for `impdata`:\n\n\n::: {.cell hash='missingdata5_cache/html/step1k_74821416eaa42505fd511a627109fec3'}\n\n```{.r .cell-code}\n# Categorical age\nsummary(dat.ineligible.stacked$age)\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>    0.00    5.00   12.00   23.25   41.00   80.00\ndat.ineligible.stacked$age.cat <- \n  with(dat.ineligible.stacked, \n       ifelse(age >= 20 & age < 50, \"20-49\", \n              ifelse(age >= 50 & age < 65, \"50-64\", \n                     ifelse(age >= 65, \"65+\", NA))))\ndat.ineligible.stacked$age.cat <- \n  factor(dat.ineligible.stacked$age.cat, \n         levels = c(\"20-49\", \"50-64\", \"65+\"))\n```\n:::\n\n\nNote that, we are assigning anyone with less than 20 age as missing.\n\n\n::: {.cell hash='missingdata5_cache/html/step1l_b82eb689e31c9ef9ec127e958044ea26'}\n\n```{.r .cell-code}\ntable(dat.ineligible.stacked$age.cat, useNA = \"always\")\n#> \n#> 20-49 50-64   65+  <NA> \n#>  1100  2360  3430 18425\n# Recode arthritis\ndat.ineligible.stacked$arthritis <- \n  car::recode(dat.ineligible.stacked$rheumatoid, \n  \" 'No' = 'No arthritis'; 'Yes' = 'Rheumatoid arthritis' \", \n  as.factor = T)\n```\n:::\n\n\nNote: In the above step, we could also create two variables with missing values rather than recoding. The reason is that we will subset the design; no matter whether we recode or create missing values for ineligible, the only information we need from ineligible subjects is their survey features when creating the design.\n\nThe next step is to combine these two datasets (`impdata` and `dat.ineligible.stacked`).\n\n\n::: {.cell hash='missingdata5_cache/html/step1m_210fefb2b508542d51d189e00d2e64ae'}\n\n```{.r .cell-code}\n# Variable names in the imputed dataset\nvars <- names(impdata) \n\n# Set up the dataset for ineligible - same variables as impdata\ndat.ineligible.stacked <- dat.ineligible.stacked[, vars]\n```\n:::\n\n\nNow we will merge ineligible and eligible subjects to make the full dataset of 5 $\\times$ 9,254 = 46,270 subjects.\n\n\n::: {.cell hash='missingdata5_cache/html/step1n_b589ea0bf47686da8f767929e0d197b0'}\n\n```{.r .cell-code}\nimpdata2 <- rbind(impdata, dat.ineligible.stacked)\nimpdata2 <- impdata2[order(impdata2$.imp, impdata2$studyid),]\ndim(impdata2)\n#> [1] 46270    17\n```\n:::\n\n\n##### 1.4 Prepating Survey design and subpopulation of eligible\n\nThe next step is to create the design on full dataset \\[with eligible (imputed) and ineligible (unimputed) subjects\\] of 5 $\\times$ 9,254 = 46,270 subjects and subset the design for 5 $\\times$ 4,716 = 23,580 subjects.\n\n\n::: {.cell hash='missingdata5_cache/html/step1o_c898035f72f04854ccefd69fca4622e1'}\n\n```{.r .cell-code}\nm <- 5\nallImputations <- imputationList(lapply(1:m, function(n) \n  subset(impdata2, subset=.imp==n)))\n\n# Step 2: Survey data analysis\nw.design0 <- svydesign(ids = ~psu, \n                       weights = ~survey.weight, \n                       strata = ~strata,\n                      data = allImputations, \n                      nest = TRUE) # Design on full data\nw.design <- subset(w.design0, ineligible == 0) # Subset the design\n```\n:::\n\n\nWe can see the length of the subsetted design:\n\n\n::: {.cell hash='missingdata5_cache/html/step1p_c57c3708aa230dfc6503959dcdddda28'}\n\n```{.r .cell-code}\ndim(w.design)\n#> [1] 4191   17    5\n```\n:::\n\n\nThe subsetted design contains 4,191 subjects with 17 variables and 5 imputed datasets. Now we will run the design-adjusted logistic regression on and pool the estimate using Rubin's rule:\n\n#### Step 2: Design adjusted regression analysis\n\n\n::: {.cell hash='missingdata5_cache/html/step2_0e501d2be3e08fc8e321b8f5f7391e77'}\n\n```{.r .cell-code}\n# Design-adjusted logistic regression\nfit <- with(w.design, \n            svyglm(I(cvd == \"Yes\") ~ arthritis + age.cat + \n                     sex + education + race + income + bmi + \n                     smoking + htn + diabetes, \n                   family = quasibinomial))\nres <- exp(as.data.frame(cbind(coef(fit[[1]]),\n      coef(fit[[2]]),\n      coef(fit[[3]]),\n      coef(fit[[4]]),\n      coef(fit[[5]]))))\nnames(res) <- paste(\"OR from m =\", 1:5)\nres.rounded <- round(t(res),2)\nkable(res.rounded)\n```\n\n::: {.cell-output-display}\n|              | (Intercept)| arthritisRheumatoid arthritis| age.cat50-64| age.cat65+| sexFemale| educationHigh school| educationCollege graduate or above| raceBlack| raceHispanic| raceOthers| income$20,000 to $74,999| income$75,000 and Over|  bmi| smokingPrevious smoker| smokingCurrent smoker| htnYes| diabetesYes|\n|:-------------|-----------:|-----------------------------:|------------:|----------:|---------:|--------------------:|----------------------------------:|---------:|------------:|----------:|------------------------:|----------------------:|----:|----------------------:|---------------------:|------:|-----------:|\n|OR from m = 1 |        0.02|                          2.12|         4.72|      13.04|      0.46|                 0.73|                               0.73|      0.94|         0.53|       0.86|                     0.47|                   0.32| 1.03|                   1.57|                  1.44|   1.34|        3.05|\n|OR from m = 2 |        0.02|                          2.10|         4.75|      13.24|      0.46|                 0.72|                               0.73|      0.99|         0.54|       0.87|                     0.53|                   0.36| 1.03|                   1.57|                  1.48|   1.28|        3.06|\n|OR from m = 3 |        0.02|                          2.12|         4.56|      11.91|      0.47|                 0.71|                               0.71|      0.97|         0.53|       0.84|                     0.49|                   0.35| 1.02|                   1.60|                  1.43|   1.49|        3.14|\n|OR from m = 4 |        0.02|                          2.07|         4.64|      12.72|      0.46|                 0.71|                               0.73|      0.95|         0.53|       0.88|                     0.52|                   0.34| 1.03|                   1.58|                  1.49|   1.45|        2.96|\n|OR from m = 5 |        0.02|                          2.11|         4.58|      12.29|      0.46|                 0.74|                               0.77|      0.92|         0.53|       0.85|                     0.43|                   0.29| 1.02|                   1.59|                  1.43|   1.51|        3.11|\n:::\n:::\n\n\n#### Step 3: Pooling estimates\n\n\n::: {.cell hash='missingdata5_cache/html/step3_0c20e9870be956f1013daecdec82b9de'}\n\n```{.r .cell-code}\n# Step 3: Pooled estimates\npooled.estimates <- MIcombine(fit)\nOR <- round(exp(pooled.estimates$coefficients), 2)\nOR <- as.data.frame(OR)\nCI <- round(exp(confint(pooled.estimates)), 2)\nOR <- cbind(OR, CI)\nOR\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"OR\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"2.5 %\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"97.5 %\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"0.02\",\"2\":\"0.01\",\"3\":\"0.04\",\"_rn_\":\"(Intercept)\"},{\"1\":\"2.10\",\"2\":\"1.30\",\"3\":\"3.41\",\"_rn_\":\"arthritisRheumatoid arthritis\"},{\"1\":\"4.65\",\"2\":\"2.43\",\"3\":\"8.90\",\"_rn_\":\"age.cat50-64\"},{\"1\":\"12.63\",\"2\":\"7.68\",\"3\":\"20.77\",\"_rn_\":\"age.cat65+\"},{\"1\":\"0.46\",\"2\":\"0.35\",\"3\":\"0.61\",\"_rn_\":\"sexFemale\"},{\"1\":\"0.72\",\"2\":\"0.42\",\"3\":\"1.25\",\"_rn_\":\"educationHigh school\"},{\"1\":\"0.73\",\"2\":\"0.42\",\"3\":\"1.30\",\"_rn_\":\"educationCollege graduate or above\"},{\"1\":\"0.96\",\"2\":\"0.65\",\"3\":\"1.40\",\"_rn_\":\"raceBlack\"},{\"1\":\"0.53\",\"2\":\"0.27\",\"3\":\"1.03\",\"_rn_\":\"raceHispanic\"},{\"1\":\"0.86\",\"2\":\"0.44\",\"3\":\"1.67\",\"_rn_\":\"raceOthers\"},{\"1\":\"0.49\",\"2\":\"0.32\",\"3\":\"0.75\",\"_rn_\":\"income$20,000 to $74,999\"},{\"1\":\"0.33\",\"2\":\"0.21\",\"3\":\"0.53\",\"_rn_\":\"income$75,000 and Over\"},{\"1\":\"1.02\",\"2\":\"1.00\",\"3\":\"1.05\",\"_rn_\":\"bmi\"},{\"1\":\"1.58\",\"2\":\"1.24\",\"3\":\"2.01\",\"_rn_\":\"smokingPrevious smoker\"},{\"1\":\"1.45\",\"2\":\"1.03\",\"3\":\"2.05\",\"_rn_\":\"smokingCurrent smoker\"},{\"1\":\"1.41\",\"2\":\"0.80\",\"3\":\"2.50\",\"_rn_\":\"htnYes\"},{\"1\":\"3.06\",\"2\":\"2.00\",\"3\":\"4.69\",\"_rn_\":\"diabetesYes\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n### Conclusion\n\nAmong US adults aged 20 years or more, the odds of CVD was approximately twice among those with rheumatoid arthritis than no arthritis.\n\n### References\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}