{
  "hash": "99a57351b5c524444f1c64d0e6f99cdf",
  "result": {
    "markdown": "## Subpopulations {.unnumbered}\n\nThis tutorial demonstrates how to manage missing data in complex surveys using multiple imputation, focusing on specific subpopulations defined by the study's eligibility criteria.\n\n### Purpose\n\nLet us we are interested in exploring the relationship between **rheumatoid arthritis** and **cardiovascular disease** (CVD) among US adults aged 20 years or more. For that, we will use NHANES 2017--2018 dataset, which follows a complex survey design.\n\n::: column-margin\nIn this tutorial, we used a similar approach to the one in a published article by @hossain2022association, but we used less data (restricted to only 2017--2018) to speed up the analysis. [Ref link](https://pubmed.ncbi.nlm.nih.gov/35301105/).\n::: \n\nThe purpose of this example is to *demonstrate how to do the missing data analysis with multiple imputation in the context of complex surveys*.\n\nThe main idea is:\n\n-   working with the analytic data\n-   imputing missing values based on that analytic dataset\n-   keep count of the ineligible subjects from the full data who are not included in the analytic data\n-   adding those ineligible subjects back in the imputed datasets, so that we can utilize the survey features and subset the design.\n\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/setup_644883d1dd3d060cfbf4d7a57c0f3069'}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(dplyr)\nlibrary(kableExtra)\nlibrary(tableone)\nlibrary(survey)\nlibrary(Publish)\nlibrary(DataExplorer)\nlibrary(mice)\nlibrary(mitools)\n```\n:::\n\n\n\nLet us import the dataset:\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/load_d7eb3e16b0bb604443d7d81b4fae5d75'}\n\n```{.r .cell-code}\nload(\"Data/missingdata/MIexample.RData\")\nls()\n#> [1] \"dat.full\"        \"has_annotations\"\n```\n:::\n\n::: {.cell hash='missingdata5_cache/pdf/data_6dae3d65e1098322b2eabc574c3d7d93'}\n\n```{.r .cell-code}\ndim(dat.full)\n#> [1] 9254   15\nhead(dat.full)\n#>   studyid survey.weight psu strata  cvd rheumatoid age    sex\n#> 1   93703      9246.492   2    145 <NA>       <NA>   2 Female\n#> 2   93704     37338.768   1    143 <NA>       <NA>   2   Male\n#> 3   93705      8614.571   2    145   No        Yes  66 Female\n#> 4   93706      8548.633   2    134 <NA>       <NA>  18   Male\n#> 5   93707      6769.345   1    138 <NA>       <NA>  13   Male\n#> 6   93708     13329.451   2    138   No       <NA>  66 Female\n#>               education   race             income  bmi         smoking  htn\n#> 1                  <NA> Others   $75,000 and Over 17.5            <NA> <NA>\n#> 2                  <NA>  White   $75,000 and Over 15.7            <NA> <NA>\n#> 3 Less than high school  Black  less than $20,000 31.7 Previous smoker  Yes\n#> 4                  <NA> Others               <NA> 21.5    Never smoker   No\n#> 5                  <NA> Others $20,000 to $74,999 18.1            <NA>  Yes\n#> 6 Less than high school Others $20,000 to $74,999 23.7    Never smoker  Yes\n#>   diabetes\n#> 1       No\n#> 2       No\n#> 3       No\n#> 4       No\n#> 5       No\n#> 6       No\n```\n:::\n\n\n\nThe dataset (`dat.full`) contains 9,254 subjects with 15 variables:\n\n**Survey information**\n\n-   `studyid`: Respondent sequence number\n-   `survey.weight`: Full sample 2 year interview weight\n-   `psu`: Masked pseudo PSU\n-   `strata`: Masked pseudo strata\n\n**Outcome variable**\n\n-   `cvd`: Whether having cardiovascular disease\n\n**Exposure variable**\n\n-   `rheumatoid`: Whether having rheumatoid arthritis\n\n**Covariates**\n\n-   `age`: age in years at screening\n-   `sex`\n-   `education`\n-   `race`: Race/Ethnicity\n-   `income`: Family income in \\$\n-   `bmi`: Body Mass Index in kg/m$^2$\n-   `smoking`: Smoking status\n-   `htn`: Having hypertension\n-   `diabetes`: Having diabetes\n\n### Analytic dataset\n\n#### Subsetting according to eligibility\n\nLet us create an analytic dataset for\n\n-   adults aged 20 years or more\n-   without missing values in outcome (cvd) or exposure (rheumatoid arthritis).\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/analytic0_bc61b6bb2d8d1cb3db78c94b7fa383ed'}\n\n```{.r .cell-code}\n# Drop < 20 years\ndat.with.miss <- subset(dat.full, age >= 20)\n\n# Frequency for outcome and exposure \ntable(dat.with.miss$cvd, useNA = \"always\") # 6 missing\n#> \n#>   No  Yes <NA> \n#> 4872  691    6\ntable(dat.with.miss$rheumatoid, useNA = \"always\") # 1375 missing\n#> \n#>   No  Yes <NA> \n#> 3857  337 1375\n\n# Drop missing in outcome and exposure - dataset with missing values only in covariates\ndat.analytic <- dat.with.miss[complete.cases(dat.with.miss$cvd),]\ndat.analytic <- dat.analytic[complete.cases(dat.analytic$rheumatoid),]\nnrow(dat.analytic)\n#> [1] 4191\n```\n:::\n\n\n\nAs we can see, we have 4,191 participants aged 20 years or more without missing values in outcome or exposure. Let us count the ineligible subjects from the full data and create an indicator variable.\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/analytic1_2db8863bcb77ab0ece25ac9084c77794'}\n\n```{.r .cell-code}\ndat.full$ineligible <- 1\ndat.full$ineligible[dat.full$studyid %in% dat.analytic$studyid] <- 0\ntable(dat.full$ineligible, useNA = \"always\")\n#> \n#>    0    1 <NA> \n#> 4191 5063    0\n```\n:::\n\n\n\nWe have 4,191 eligible and 5,063 ineligible subjects based on the eligibility criteria.\n\n**General strategy of solution**:\n\n-   We will build the imputation model on 4,191 eligible subjects, and\n-   later we will include 5,063 ineligible subjects in the data so that we can utilize survey features.\n\n#### Table 1\n\nLet us see the summary statistics, i.e., create Table 1 stratified by outcome (cvd). Before that, we will categorize `age` and recode `rheumatoid`:\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/analytic2_75827c46a2d42f222dde0dc0549a687d'}\n\n```{.r .cell-code}\n# Categorical age\ndat.analytic$age.cat <- with(dat.analytic, ifelse(age >= 20 & age < 50, \"20-49\", \n                                  ifelse(age >= 50 & age < 65, \"50-64\", \"65+\")))\ndat.analytic$age.cat <- factor(dat.analytic$age.cat, levels = c(\"20-49\", \"50-64\", \"65+\"))\ntable(dat.analytic$age.cat, useNA = \"always\")\n#> \n#> 20-49 50-64   65+  <NA> \n#>  2280  1097   814     0\n\n# Recode rheumatoid to arthritis\ndat.analytic$arthritis <- car::recode(dat.analytic$rheumatoid, \" 'No' = 'No arthritis';\n                                      'Yes' = 'Rheumatoid arthritis' \", as.factor = T)\ntable(dat.analytic$arthritis, useNA = \"always\")\n#> \n#>         No arthritis Rheumatoid arthritis                 <NA> \n#>                 3854                  337                    0\n\n# Keep only relevant variables\nvars <-  c(\"studyid\", \"survey.weight\", \"psu\", \"strata\", \"cvd\", \"arthritis\", \"age.cat\", \n           \"sex\", \"education\", \"race\", \"income\", \"bmi\", \"smoking\", \"htn\", \"diabetes\")\ndat.analytic2 <- dat.analytic[, vars]\n```\n:::\n\n::: {.cell hash='missingdata5_cache/pdf/tab1_b9c47d58672ef89052654be4754d5c43'}\n\n```{.r .cell-code}\n# Create Table 1\nvars <- c(\"arthritis\", \"age.cat\", \"sex\", \"education\", \"race\", \"income\", \"bmi\", \"smoking\",\n          \"htn\", \"diabetes\")\ntab1 <- CreateTableOne(vars = vars, strata = \"cvd\", data = dat.analytic2, includeNA = F,\n                       addOverall = T, test = F)\nprint(tab1, format = \"f\", showAllLevels = T)\n#>                  Stratified by cvd\n#>                   level                     Overall      No          \n#>   n                                          4191         3823       \n#>   arthritis       No arthritis               3854         3580       \n#>                   Rheumatoid arthritis        337          243       \n#>   age.cat         20-49                      2280         2240       \n#>                   50-64                      1097          979       \n#>                   65+                         814          604       \n#>   sex             Male                       2126         1884       \n#>                   Female                     2065         1939       \n#>   education       Less than high school       828          728       \n#>                   High school                2292         2094       \n#>                   College graduate or above  1063          993       \n#>   race            White                      1275         1113       \n#>                   Black                       998          898       \n#>                   Hispanic                   1015          958       \n#>                   Others                      903          854       \n#>   income          less than $20,000           659          557       \n#>                   $20,000 to $74,999         1967         1796       \n#>                   $75,000 and Over           1143         1079       \n#>   bmi (mean (SD))                           29.28 (7.19) 29.20 (7.18)\n#>   smoking         Never smoker               2570         2427       \n#>                   Previous smoker             882          726       \n#>                   Current smoker              739          670       \n#>   htn             No                         1424         1380       \n#>                   Yes                        2415         2107       \n#>   diabetes        No                         3622         3396       \n#>                   Yes                         566          424       \n#>                  Stratified by cvd\n#>                   Yes         \n#>   n                 368       \n#>   arthritis         274       \n#>                      94       \n#>   age.cat            40       \n#>                     118       \n#>                     210       \n#>   sex               242       \n#>                     126       \n#>   education         100       \n#>                     198       \n#>                      70       \n#>   race              162       \n#>                     100       \n#>                      57       \n#>                      49       \n#>   income            102       \n#>                     171       \n#>                      64       \n#>   bmi (mean (SD)) 30.09 (7.29)\n#>   smoking           143       \n#>                     156       \n#>                      69       \n#>   htn                44       \n#>                     308       \n#>   diabetes          226       \n#>                     142\n```\n:::\n\n\n\n#### Check missingness using a plot\n\nNow we will see the percentage of missing values in the variables.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nDataExplorer::plot_missing(dat.analytic2)\n```\n\n::: {.cell-output-display}\n![](missingdata5_files/figure-pdf/miss0-1.pdf){fig-pos='H' width=80%}\n:::\n:::\n\n\n\nWe have about 10% missing values in income, followed by hypertension (8.4%), bmi (6.8%), education (0.2%), and diabetes (0.1%).\n\n### Dealing with missing values in covariates\n\n-   Now we will perform multiple imputation to deal with missing values only in covariates. We will use the `dat.analytic2` dataset that contains missing values in the covariates but no missing values in the outcome or exposure.\n-   For this exercise, we will consider 5 imputed datasets, 3 iterations, and the predictive mean matching method for bmi and income.\n    -   We have already set up the data such that the variables are of appropriate types, e.g., numeric bmi, factor age, sex, and so on.\n    -   We will use the strata variable as an auxiliary variable in the imputation model but not the survey weight or PSU variable.\n    -   Now we will set up the initial model and set up the methods and predictor matrix before imputing 5 datasets.\n\n#### Step 0: Set up the imputation model\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/step0_3f62c42b76ce414682daa3c20752b06d'}\n\n```{.r .cell-code}\n# Step 0: Set imputation model\nini <- mice(data = dat.analytic2, maxit = 0, print = FALSE)\npred <- ini$pred\n\n# Use the strata variable as an auxiliary variable in the imputation model\npred[\"strata\",] <- 0\n\n# Do not use survey weight or PSU variable as auxiliary variables\npred[,\"studyid\"] <- pred[\"studyid\",] <- 0\npred[,\"psu\"] <- pred[\"psu\",] <- 0\npred[,\"survey.weight\"] <- pred[\"survey.weight\",] <- 0\n\n# Set imputation method\nmeth <- ini$meth\nmeth[\"bmi\"] <- \"pmm\"\nmeth[\"income\"] <- \"pmm\"\nmeth\n#>       studyid survey.weight           psu        strata           cvd \n#>            \"\"            \"\"            \"\"            \"\"            \"\" \n#>     arthritis       age.cat           sex     education          race \n#>            \"\"            \"\"            \"\"     \"polyreg\"            \"\" \n#>        income           bmi       smoking           htn      diabetes \n#>         \"pmm\"         \"pmm\"            \"\"      \"logreg\"      \"logreg\"\n```\n:::\n\n\n\n-   There is no missing for studyid, survey.weight, psu, strata, cvd, arthritis, age, sex, race, smoking. Hence, no method is assigned for these variables.\n-   For education, `polyreg` (Polytomous logistic regression) will be used.\n-   Similarly, we will use `pmm` (Predictive mean matching) for bmi, income and used `logreg` (Logistic regression) for htn, diabetes.\n\n#### Step 1: Imputing missing values using mice\n\n##### 1.1 Imputing dataset for eligible subjects\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/step1a_65556d5d38f7415bbe1d2840cec1e36c'}\n\n```{.r .cell-code}\n# Step 1: impute the incomplete data\nimputation <- mice(data = dat.analytic2,\n                   seed = 123,\n                   predictorMatrix = pred,\n                   method = meth,\n                   m = 5,\n                   maxit = 3,\n                   print = FALSE)\n```\n:::\n\n\n\nNow we will combine m = 5 datasets and create a stacked dataset. This dataset should contain 5\\*4,191 = 20,955 rows.\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/step1b_63a6968fd35ee13fea437d66e5bf0839'}\n\n```{.r .cell-code}\nimpdata <- mice::complete(imputation, action=\"long\")\n\ntable(impdata$age.cat)\n#> \n#> 20-49 50-64   65+ \n#> 11400  5485  4070\n```\n:::\n\n\n\nNote that age has no missing values, and everyone is above 20.\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/step1c_72cf066bc619fd07c7a6c573f25e1393'}\n\n```{.r .cell-code}\n#Remove .id variable from the model as it was created in an intermediate step\nimpdata$.id <- NULL\n\n# Create an indicator of eligible subjects \nimpdata$ineligible <- 0\n\n# Number of subjects\nnrow(impdata)\n#> [1] 20955\n```\n:::\n\n\n\nLet's see whether there is any missing value after imputation:\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/step1d_8131ae4429044716316b6124eb2b9fde'}\n\n```{.r .cell-code}\nDataExplorer::plot_missing(impdata)\n```\n\n::: {.cell-output-display}\n![](missingdata5_files/figure-pdf/step1d-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n-   There is no missing value after imputation.\n-   As we can see, there is an additional variable (`.imp`) in the imputed dataset. This `.imp` goes from 1 to m = 5, indicating the first to the fifth imputed datasets.\n\n##### 1.2 Preparing dataset for ineligible subjects\n\nThe next task is adding the **ineligible subjects** in the imputed datasets, so that we can set up the survey design on the full dataset and then subset the design.\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/step1e_db7d77029b9ff9dcbfb844e4d29e7fd6'}\n\n```{.r .cell-code}\n# Number of ineligible subjects\n#dat.full$ineligible <- 1\n#dat.full$ineligible[dat.full$studyid %in% dat.analytic$studyid] <- 0\ntable(dat.full$ineligible, useNA = \"always\")\n#> \n#>    0    1 <NA> \n#> 4191 5063    0\n```\n:::\n\n\n\nNow we will subset the data for ineligible subjects and create `m = 5` copies.\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/step1f_c0dc30f99adfa7ff0d6ae751221cb9b7'}\n\n```{.r .cell-code}\n# Subset for ineligible\ndat.ineligible <- subset(dat.full, ineligible == 1)\n\n# Create m = 5 datasets with .imp 1 to m = 5\ndat31 <- dat.ineligible; dat31$.imp <- 1\ndat32 <- dat.ineligible; dat32$.imp <- 2\ndat33 <- dat.ineligible; dat33$.imp <- 3\ndat34 <- dat.ineligible; dat34$.imp <- 4\ndat35 <- dat.ineligible; dat35$.imp <- 5\n```\n:::\n\n\n\nThe next step is combining ineligible datasets. Before merging the `stacked dataset for ineligible subjects` to the `imputed stacked dataset for eligible subjects,` we must ensure the variable names are the same.\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/step1g_53bd18d1c2cc2328dc28464b48d19221'}\n\n```{.r .cell-code}\n# Stacked data for ineligible subjects\ndat.ineligible.stacked <- rbind(dat31, dat32, dat33, dat34, dat35)\n```\n:::\n\n\n\nWe should have missing value in this ineligible part of the data:\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/step1h_d777a9a5e9bef904cb94a4760f7be61a'}\n\n```{.r .cell-code}\nDataExplorer::plot_missing(dat.ineligible.stacked)\n```\n\n::: {.cell-output-display}\n![](missingdata5_files/figure-pdf/step1h-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n##### 1.3 Combining eligible (imputed) and ineligible (unimputed) subjects\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/step1i_5d577e9f420d5966edd0dbdd644febfa'}\n\n```{.r .cell-code}\nnames(impdata)\n#>  [1] \".imp\"          \"studyid\"       \"survey.weight\" \"psu\"          \n#>  [5] \"strata\"        \"cvd\"           \"arthritis\"     \"age.cat\"      \n#>  [9] \"sex\"           \"education\"     \"race\"          \"income\"       \n#> [13] \"bmi\"           \"smoking\"       \"htn\"           \"diabetes\"     \n#> [17] \"ineligible\"\n```\n:::\n\n::: {.cell hash='missingdata5_cache/pdf/step1j_e61569fa2f7c2f1fe5a4698d630ab01b'}\n\n```{.r .cell-code}\nnames(dat.ineligible.stacked)\n#>  [1] \"studyid\"       \"survey.weight\" \"psu\"           \"strata\"       \n#>  [5] \"cvd\"           \"rheumatoid\"    \"age\"           \"sex\"          \n#>  [9] \"education\"     \"race\"          \"income\"        \"bmi\"          \n#> [13] \"smoking\"       \"htn\"           \"diabetes\"      \"ineligible\"   \n#> [17] \".imp\"\n```\n:::\n\n\n\nAs we can see, the variable names are different in the two datasets. Particularly, `arthritis` and `age.cat` variables are not available in the `dat.ineligible.stacked` dataset. Now we will recode these variables in the same format as done for `impdata`:\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/step1k_5301279a41f96cf7536a0a8ed2b61fc2'}\n\n```{.r .cell-code}\n# Categorical age\nsummary(dat.ineligible.stacked$age)\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>    0.00    5.00   12.00   23.25   41.00   80.00\ndat.ineligible.stacked$age.cat <- with(dat.ineligible.stacked, \n                                       ifelse(age >= 20 & age < 50, \"20-49\", \n                                              ifelse(age >= 50 & age < 65, \"50-64\", \n                                                    ifelse(age >= 65, \"65+\", NA))))\ndat.ineligible.stacked$age.cat <- factor(dat.ineligible.stacked$age.cat, \n                                         levels = c(\"20-49\", \"50-64\", \"65+\"))\n```\n:::\n\n\n\nNote that, we are assigning anyone with less than 20 age as missing.\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/step1l_d39febf2b5df7c1bd83ca02889bac7a8'}\n\n```{.r .cell-code}\ntable(dat.ineligible.stacked$age.cat, useNA = \"always\")\n#> \n#> 20-49 50-64   65+  <NA> \n#>  1100  2360  3430 18425\n# Recode arthritis\ndat.ineligible.stacked$arthritis <- car::recode(dat.ineligible.stacked$rheumatoid, \n                                                \" 'No' = 'No arthritis'; 'Yes' = \n                                                'Rheumatoid arthritis' \", as.factor = T)\n```\n:::\n\n\n\nNote: In the above step, we could also create two variables with missing values rather than recoding. The reason is that we will subset the design; no matter whether we recode or create missing values for ineligible, the only information we need from ineligible subjects is their survey features when creating the design.\n\nThe next step is to combine these two datasets (`impdata` and `dat.ineligible.stacked`).\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/step1m_5937bfe551469fc493052190645817f3'}\n\n```{.r .cell-code}\n# Variable names in the imputed dataset\nvars <- names(impdata) \n\n# Set up the dataset for ineligible - same variables as impdata\ndat.ineligible.stacked <- dat.ineligible.stacked[, vars]\n```\n:::\n\n\n\nNow we will merge ineligible and eligible subjects to make the full dataset of 5 $\\times$ 9,254 = 46,270 subjects.\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/step1n_79c3e5c96b998bf2ade2b48248645eea'}\n\n```{.r .cell-code}\nimpdata2 <- rbind(impdata, dat.ineligible.stacked)\nimpdata2 <- impdata2[order(impdata2$.imp, impdata2$studyid),]\ndim(impdata2)\n#> [1] 46270    17\n```\n:::\n\n\n\n##### 1.4 Prepating Survey design and subpopulation of eligible\n\nThe next step is to create the design on full dataset \\[with eligible (imputed) and ineligible (unimputed) subjects\\] of 5 $\\times$ 9,254 = 46,270 subjects and subset the design for 5 $\\times$ 4,716 = 23,580 subjects.\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/step1o_5374efe14155f96f1265852cbb8d09ab'}\n\n```{.r .cell-code}\nm <- 5\nallImputations <- imputationList(lapply(1:m, function(n) subset(impdata2, subset=.imp==n)))\n\n# Step 2: Survey data analysis\nw.design0 <- svydesign(ids = ~psu, \n                       weights = ~survey.weight, \n                       strata = ~strata,\n                      data = allImputations, \n                      nest = TRUE) # Design on full data\nw.design <- subset(w.design0, ineligible == 0) # Subset the design\n```\n:::\n\n\n\nWe can see the length of the subsetted design:\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/step1p_5ece71e1712e281c618b9c1aee5b1e44'}\n\n```{.r .cell-code}\ndim(w.design)\n#> [1] 4191   17    5\n```\n:::\n\n\n\nThe subsetted design contains 4,191 subjects with 17 variables and 5 imputed datasets. Now we will run the design-adjusted logistic regression on and pool the estimate using Rubin's rule:\n\n#### Step 2: Design adjusted regression analysis\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/step2_7224c60cd53872c5c8ac17c5fcd18b7d'}\n\n```{.r .cell-code}\n# Design-adjusted logistic regression\nfit <- with(w.design, svyglm(I(cvd == \"Yes\") ~ arthritis + age.cat + sex + education + \n                               race + income + bmi + smoking + htn + diabetes, \n                             family = quasibinomial))\nres <- exp(as.data.frame(cbind(coef(fit[[1]]),\n      coef(fit[[2]]),\n      coef(fit[[3]]),\n      coef(fit[[4]]),\n      coef(fit[[5]]))))\nnames(res) <- paste(\"OR from m =\", 1:5)\nround(t(res),2)\n#>               (Intercept) arthritisRheumatoid arthritis age.cat50-64 age.cat65+\n#> OR from m = 1        0.02                          2.03         4.71      13.08\n#> OR from m = 2        0.02                          2.04         4.74      13.21\n#> OR from m = 3        0.02                          2.12         4.58      11.88\n#> OR from m = 4        0.02                          2.10         4.59      12.45\n#> OR from m = 5        0.02                          2.07         4.47      12.25\n#>               sexFemale educationHigh school educationCollege graduate or above\n#> OR from m = 1      0.46                 0.75                               0.75\n#> OR from m = 2      0.45                 0.76                               0.79\n#> OR from m = 3      0.47                 0.71                               0.70\n#> OR from m = 4      0.46                 0.70                               0.71\n#> OR from m = 5      0.45                 0.75                               0.77\n#>               raceBlack raceHispanic raceOthers income$20,000 to $74,999\n#> OR from m = 1      0.96         0.54       0.86                     0.48\n#> OR from m = 2      0.97         0.54       0.88                     0.48\n#> OR from m = 3      0.98         0.54       0.85                     0.54\n#> OR from m = 4      0.96         0.53       0.86                     0.51\n#> OR from m = 5      0.99         0.55       0.87                     0.53\n#>               income$75,000 and Over  bmi smokingPrevious smoker\n#> OR from m = 1                   0.33 1.02                   1.55\n#> OR from m = 2                   0.32 1.03                   1.55\n#> OR from m = 3                   0.36 1.01                   1.59\n#> OR from m = 4                   0.34 1.02                   1.56\n#> OR from m = 5                   0.34 1.02                   1.55\n#>               smokingCurrent smoker htnYes diabetesYes\n#> OR from m = 1                  1.43   1.35        3.01\n#> OR from m = 2                  1.47   1.30        3.01\n#> OR from m = 3                  1.45   1.48        3.13\n#> OR from m = 4                  1.44   1.46        3.03\n#> OR from m = 5                  1.45   1.47        3.05\n```\n:::\n\n\n\n#### Step 3: Pooling estimates\n\n\n\n::: {.cell hash='missingdata5_cache/pdf/step3_593dbdc12b872443251b924e6e84d492'}\n\n```{.r .cell-code}\n# Step 3: Pooled estimates\npooled.estimates <- MIcombine(fit)\nOR <- round(exp(pooled.estimates$coefficients), 2)\nOR <- as.data.frame(OR)\nCI <- round(exp(confint(pooled.estimates)), 2)\nOR <- cbind(OR, CI)\nOR\n#>                                       OR 2.5 % 97.5 %\n#> (Intercept)                         0.02  0.01   0.05\n#> arthritisRheumatoid arthritis       2.07  1.27   3.38\n#> age.cat50-64                        4.62  2.41   8.85\n#> age.cat65+                         12.56  7.60  20.76\n#> sexFemale                           0.46  0.35   0.61\n#> educationHigh school                0.73  0.42   1.28\n#> educationCollege graduate or above  0.74  0.41   1.33\n#> raceBlack                           0.97  0.67   1.42\n#> raceHispanic                        0.54  0.28   1.03\n#> raceOthers                          0.86  0.44   1.69\n#> income$20,000 to $74,999            0.51  0.33   0.77\n#> income$75,000 and Over              0.34  0.21   0.53\n#> bmi                                 1.02  0.99   1.05\n#> smokingPrevious smoker              1.56  1.22   2.00\n#> smokingCurrent smoker               1.45  1.02   2.04\n#> htnYes                              1.41  0.78   2.54\n#> diabetesYes                         3.05  1.98   4.70\n```\n:::\n\n\n\n### Conclusion\n\nAmong US adults aged 20 years or more, the odds of CVD was approximately twice among those with rheumatoid arthritis than no arthritis.\n\n\n### References",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}