{
  "hash": "fc57244648c8469a8a5fcb555c4f77e1",
  "result": {
    "engine": "knitr",
    "markdown": "## Exercise 1 Solution (A) {.unnumbered}\n\n\n\nWe will use the following article:\n\nPalis, Marchand & Oviedo-Joekes. (2020). The relationship between sense of community belonging and self-rated mental health among Canadians with mental or substance use disorders. Journal of Mental Health, 29(2): 168-175. DOI: [10.1080/09638237.2018.1437602](https://www.tandfonline.com/doi/abs/10.1080/09638237.2018.1437602?journalCode=ijmh20) (available in the \"Library Online Course Reserves\": [open link](https://www.researchgate.net/profile/Heather_Palis/publication/323136807_The_relationship_between_sense_of_community_belonging_and_self-rated_mental_health_among_Canadians_with_mental_or_substance_use_disorders/links/5a96ff210f7e9ba42974c0dd/The-relationship-between-sense-of-community-belonging-and-self-rated-mental-health-among-Canadians-with-mental-or-substance-use-disorders.pdf).\n\n-   Download the [CCHS MH topical index](https://gsg.uottawa.ca/data/teaching/escc-cchs/fmgd_pumf/2012/cchs_mh_topical_index.pdf)\n-   Download the [CCHS MH Data Dictionary](https://gsg.uottawa.ca/data/teaching/escc-cchs/fmgd_pumf/2012/cchs_mh_datadictionary.pdf)\n\n# Question 1: \n\n## 1(a) Importing dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Importing dataset\nload(\"Data/accessing/cchsMH.RData\")\n```\n:::\n\n\n## 1(b) Subsetting according to eligibility\n\nSubset the dataset according to the eligibility criteria / restriction specified in the paper\n\n-   Identify the variable needed for eligibility criteria\n\n**Hint**\n\n-   Read the first paragraph of **Analytic sample** (page 2) for the eligibility criteria\n-   Eligibility criteria was determined based on only **one** variable. Only work with 'YES' category.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Subsetting according to eligibility\ndat <- subset(cmh, MHPFY==\"YES\")\n```\n:::\n\n\n## 1(c) Retaining necessary variables\n\nIn the dataset, retain only the variables associated with outcome measure, explanatory variable, potential confounders and survey weight. There should be eight variables (one outcome, one exposure, five confounders, and one survey weight).\n\nHere are the steps:\n\n-   Identify the outcome variable\n\n-   Identify the explanatory variable\n\n-   Identify the potential confounders\n\n-   Identify the survey weight variable\n\n-   **Hint**\n\n    1.  Read\n\n    -   first and second paragraphs of **Study variables** for the outcome, explanatory and confounding variables\n    -   third paragraph of the **Statistical analyses** for the survey weights variable.\n\n    2.  There were **five** potential confounders.\n    3.  Potentially useful functions for this exercise:\n\n    -   [%in%](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/match)\n    -   [levels](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/levels)\n    -   [recode](https://rdrr.io/cran/car/man/recode.html)\n    -   [subset](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/subset)\n    -   [as.factor](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/factor)\n    -   [relevel](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/relevel)\n    -   or [dplyr ways](https://ehsanx.github.io/intro2R/data-analysis-with-dplyr.html): [filter](https://www.rdocumentation.org/packages/dplyr/versions/0.7.8/topics/filter), [select](https://www.rdocumentation.org/packages/dplyr/versions/0.7.8/topics/select)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <- with(dat, data.frame(srmh = SCR_082, # Outcome - SMRH\n                            community = GEN_10, # explanatory - community belonging\n                            sex = DHH_SEX, # sex\n                            age = DHHGAGE, # age\n                            race = SDCGCGT, # respondent's racial identity\n                            income = INCG7, # main source of income\n                            help = PNC_01A, # received help for problems\n                            weight = WTS_M)) # sampling weight\n```\n:::\n\n\n## 1(e) Creating analytic dataset\n\nOutcome variable has a category 'NOT STATED', but for our analysis, we will omit anyone associated with this category. Similarly, for explanatory variable, we have categories such as DON'T KNOW, REFUSAL and NOT STATED. We will omit anyone with these categories.\n\n-   Assign missing values for categories such as DON'T KNOW, REFUSAL and NOT STATED.\n-   Recode the variables as shown in Table 1 in the article. You can use any function/package of your choice. Here is an example (but feel free to use other functions. In R there are many other ways to do this same task.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## your code here\n# levels(your.data.frame$your.age.variable) <- \n#   list(\"15 to 24 years\" = c(\"15 TO 19 YEARS\", \"20 TO 24 YEARS\"),\n#        \"25 to 34 years\" = c(\"25 TO 29 YEARS\", \"30 TO 34 YEARS\"),\n#        \"35 to 44 years\" = c(\"35 TO 39 YEARS\", \"40 TO 44 YEARS\"),\n#        \"45 to 54 years\" = c(\"45 TO 49 YEARS\", \"50 TO 54 YEARS\"),\n#        \"55 to 64 years\" = c(\"55 TO 59 YEARS\", \"60 TO 64 YEARS\"),\n#        \"65 years or older\" = c(\"65 TO 69 YEARS\", \"70 TO 74 YEARS\", \n#        \"75 TO 79 YEARS\", \"80 YEARS OR MORE\"))\n\n# Outcome variable: Self-rated Mental Health\n#table(dat$srmh, useNA = \"always\")\ndat$srmh <- car::recode(dat$srmh, \" c('FAIR','POOR') = 'Poor or Fair'; \n                        'GOOD' = 'Good'; c('EXCELLENT', 'VERY GOOD') = \n                        'Very good or excellent'; else = NA \")\ndat$srmh <- factor(dat$srmh, levels=c(\"Poor or Fair\", \"Good\", \"Very good or excellent\"))\n\n# Explanatory variable: Community belonging\n#table(dat$community, useNA = \"always\")\ndat$community <- recode(dat$community, recodes = \" 'VERY STRONG' = 'Very strong';\n                        'SOMEWHAT STRONG' = 'Somewhat strong'; 'SOMEWHAT WEAK' = \n                        'Somewhat weak'; 'VERY WEAK' = 'Very weak'; else = NA \")\ndat$community <- factor(dat$community, levels = c(\"Very weak\", \"Somewhat weak\",\n                                                  \"Somewhat strong\", \"Very strong\"))\n\n# Sex\n#table(dat$sex, useNA = \"always\")\ndat$sex <- recode(dat$sex, recodes = \"'MALE' = 'Males'; 'FEMALE' = 'Females'; \n                  else = NA\")\n\n# Age group\n#table(dat$age, useNA = \"always\")\nlevels(dat$age) <- list(\"15 to 24 years\" = c(\"15 TO 19 YEARS\", \"20 TO 24 YEARS\"),\n                        \"25 to 34 years\" = c(\"25 TO 29 YEARS\", \"30 TO 34 YEARS\"),\n                        \"35 to 44 years\" = c(\"35 TO 39 YEARS\", \"40 TO 44 YEARS\"),\n                        \"45 to 54 years\" = c(\"45 TO 49 YEARS\", \"50 TO 54 YEARS\"),\n                        \"55 to 64 years\" = c(\"55 TO 59 YEARS\", \"60 TO 64 YEARS\"),\n                        \"65 years or older\" = c(\"65 TO 69 YEARS\", \"70 TO 74 YEARS\", \n                                                \"75 TO 79 YEARS\", \"80 YEARS OR MORE\"))\n\n# Race/Ethnicity\n#table(dat$race, useNA = \"always\")\ndat$race <- recode(dat$race, \" 'WHITE'='White'; 'NON-WHITE'='Non-white'; else=NA \")\n\n# Income\n#table(dat$income, useNA = \"always\") \nlevels(dat$income) <- list(\"Employment Income\" = \"EMPLOYMENT INC.\",\n                           \"Worker's Compensation\" = \"EI/WORKER'S COMP\",\n                           \"Senior Benefits\" = \"SENIOR BENEFITS\", \n                           \"Other\" = \"OTHER\",\n                           \"Not applicable\" = \"NOT APPLICABLE\")\n```\n:::\n\n\n## 1(f) Number of columns and variable names\n\nReport the number of columns in your analytic dataset, and the variable names.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Number of columns\nncol(dat)\n#> [1] 8\n\n# Variable names\nnames(dat)\n#> [1] \"srmh\"      \"community\" \"sex\"       \"age\"       \"race\"      \"income\"   \n#> [7] \"help\"      \"weight\"\n```\n:::\n\n\n# Question 2: Table 1 \n\nReproduce Table 1 presented in the article (or see below). Omit the 'Main source of income' variable from the table. The table you produce should report numbers as follows, with all columns as shown in the table. In other words, the numbers should match.\n\n| Self-rated Mental Health Variable | Total n(%) | Poor or Fair n(%) | Good n(%) | Very good or excellent n(%) |\n|------------------|--------------|--------------|--------------|---------------|\n| **Study sample** | 2628 (100) | 1002 (38.1) | 885 (33.7) | 741 (28.2) |\n| **Community belonging** |  |  |  |  |\n| \\- Very weak | 480 (18.3) | 282 (28.1) | 118 (13.3)a | 80 (10.8)a |\n| \\- Somewhat weak | 857 (32.6) | 358 (35.7) | 309 (34.9) | 190 (25.6) |\n| \\- Somewhat strong | 1005 (38.2) | 288 (28.7) | 362 (40.9) | 355 (47.9) |\n| \\- Very strong | 286 (10.9) | 74 (7.4)a | 96 (10.8)a | 116 (15.7)a |\n| **Sex** |  |  |  |  |\n| \\- Females | 1407 (53.5) | 616 (61.5) | 487 (55.0) | 304 (41.0) |\n| \\- Males | 1221 (46.5) | 386 (38.5) | 398 (45.0) | 437 (59.0) |\n| **Age group** |  |  |  |  |\n| \\- 15 to 24 years | 740 (28.2) | 191 (19.1) | 264 (29.8) | 285 (38.5) |\n| \\- 25 to 34 years | 475 (18.1) | 141 (14.1) | 167 (18.9) | 167 (22.5) |\n| \\- 35 to 44 years | 393 (15.0) | 185 (18.5) | 119 (13.4)a | 89 (12.0)a |\n| \\- 45 to 54 years | 438 (16.6) | 220 (22.0) | 139 (15.7) | 79 (10.7)a |\n| \\- 55 to 64 years | 379 (14.4) | 198 (19.7) | 113 (12.8)a | 68 (9.2)a |\n| \\- 65 years or older | 203 (7.7) | 67 (6.6)a | 83 (8.4)a | 53 (7.1)b |\n| **Race/Ethnicity** |  |  |  |  |\n| \\- Non-white | 458 (17.4) | 184 (18.4) | 140 (15.8) | 134 (18.1) |\n| \\- White | 2170 (82.6) | 818 (81.6) | 745 (84.2) | 607 (81.9) |\n| **Main source of income** |  |  |  |  |\n| \\- Employment Income\\^d | 1054 (40.1) | 289 (28.8) | 386 (43.6) | 379 (51.1) |\n| \\- Worker's Compensation\\^e | 160 (6.1) | 91 (9.1)a | 44 (5.0)b | 25 (3.4)c |\n| \\- Senior Benefits\\^f | 134 (5.1) | 57 (5.7)a | 42 (4.7)b | 35 (4.7) |\n| \\- Other\\^g | 184 (7.0) | 82 (8.2)a | 60 (6.8)a | 42 (5.7)b |\n| \\- Not applicable\\^h | 851 (32.4) | 402 (40.1) | 263 (29.7) | 186 (25.1) |\n| \\- Not Stated\\^i | 245 (9.3) | 81 (8.1)a | 90 (10.2)a | 74 (10.0) |\n\n$^a$ Coefficient of variation between 16.6 and 25.0%. $^b$ Coefficient of variation between 25.1 and 33.3%. $^c$ Coefficient of variation \\> 33.3%. $^d$ Employment Income: Wages/salaries or self-employment. $^e$ Worker's compensation: Employment insurance or worker's compensation or social assistance/welfare. $^f$ Senior Benefits: Benefits from Canada or Quebec Pension Plan or job related retirement pensions, superannuation and annuities or RRSP/RRIF of Old Age Security and Guaranteed Income Supplement. $^g$ Other: Dividends/interest or child tax benefit or child support or alimony or other or no income. $^h$ Not applicable: Respondents who live in a household with only one person. The income variable \"main source of personal income\" is applicable only to those that live in a household of more than one person. $^i$ Not Stated: Question was not answered (don't know, refusal, not stated).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Drop main source of income\ndat <- dplyr::select(dat,-c(income))\n\n# Drop received help for problems \ndat <- dplyr::select(dat,-c(help))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Complete case data\ndat <- as.data.frame(na.omit(dat))\n\nvars <- c(\"community\", \"sex\", \"age\", \"race\")\n\n# Summary table\ntab1 <- CreateTableOne(vars = vars, data = dat, strata =\"srmh\", includeNA = F, test = F, \n                       addOverall = T)\n#print(tab1, showAllLevels = T)\n\nkableone <- function(x, ...) {\n   capture.output(x <- print(x, showAllLevels= TRUE, padColnames = TRUE, \n                             insertLevel = TRUE))\n   knitr::kable(x, ...)\n}\nkableone(tab1, printToggle = FALSE)\n```\n\n::: {.cell-output-display}\n\n\n|              |      level       |   Overall  |Poor or Fair |    Good   |Very good or excellent |\n|:-------------|:-----------------|:-----------|:------------|:----------|:----------------------|\n|n             |                  |2628        |1002         |885        |741                    |\n|community (%) |Very weak         |480 (18.3)  |282 (28.1)   |118 (13.3) |80 (10.8)              |\n|              |Somewhat weak     |857 (32.6)  |358 (35.7)   |309 (34.9) |190 (25.6)             |\n|              |Somewhat strong   |1005 (38.2) |288 (28.7)   |362 (40.9) |355 (47.9)             |\n|              |Very strong       |286 (10.9)  |74 ( 7.4)    |96 (10.8)  |116 (15.7)             |\n|sex (%)       |Females           |1407 (53.5) |616 (61.5)   |487 (55.0) |304 (41.0)             |\n|              |Males             |1221 (46.5) |386 (38.5)   |398 (45.0) |437 (59.0)             |\n|age (%)       |15 to 24 years    |740 (28.2)  |191 (19.1)   |264 (29.8) |285 (38.5)             |\n|              |25 to 34 years    |475 (18.1)  |141 (14.1)   |167 (18.9) |167 (22.5)             |\n|              |35 to 44 years    |393 (15.0)  |185 (18.5)   |119 (13.4) |89 (12.0)              |\n|              |45 to 54 years    |438 (16.7)  |220 (22.0)   |139 (15.7) |79 (10.7)              |\n|              |55 to 64 years    |379 (14.4)  |198 (19.8)   |113 (12.8) |68 ( 9.2)              |\n|              |65 years or older |203 ( 7.7)  |67 ( 6.7)    |83 ( 9.4)  |53 ( 7.2)              |\n|race (%)      |Non-white         |458 (17.4)  |184 (18.4)   |140 (15.8) |134 (18.1)             |\n|              |White             |2170 (82.6) |818 (81.6)   |745 (84.2) |607 (81.9)             |\n\n\n:::\n:::\n\n\n# Question 3: \n\n## 3(a) Subset\n\nSubset the dataset excluding 'Very good or excellent' responses from the self-rated mental health variable\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat3 <- dplyr::filter(dat, srmh != \"Very good or excellent\")\n```\n:::\n\n\n## 3(b) Recode\n\nRecode self-rated mental health variable and make it a binary variable: 'Good' vs. 'Poor' (simplifying category labels only). Convert that variable to a factor variable with 'Poor' being the reference level.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat3$srmh <- recode(dat3$srmh, recodes = \" 'Poor or Fair' = 'Poor'; 'Good' = 'Good'; \n                    else = NA\", levels = c(\"Poor\", \"Good\"))\n```\n:::\n\n\n## 3(c) Regression\n\nRun a logistic regression model for finding the relationship between community belonging (Reference: Very weak) and self-rated mental health (Reference: Poor) among respondents with mental or substance use disorders. Adjust the model for three confounders: sex, age, and race/ethnicity. Do not need to report summary of the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit <- glm(I(srmh==\"Good\") ~ community + sex + age + race, data = dat3, \n           family = binomial)\n```\n:::\n\n\n## 3(d) Reporting odds ratio\n\nReport the odds ratios and associated confidence intervals. Publish or jtools package could be useful to report the odds ratios with confidence intervals.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrequire(Publish)\npublish(fit)\n#>   Variable             Units OddsRatio       CI.95    p-value \n#>  community         Very weak       Ref                        \n#>                Somewhat weak      1.93 [1.48;2.53]    < 1e-04 \n#>              Somewhat strong      2.90 [2.22;3.80]    < 1e-04 \n#>                  Very strong      3.32 [2.27;4.85]    < 1e-04 \n#>        sex           Females       Ref                        \n#>                        Males      1.32 [1.09;1.60]   0.003993 \n#>        age    15 to 24 years       Ref                        \n#>               25 to 34 years      0.85 [0.63;1.15]   0.292243 \n#>               35 to 44 years      0.45 [0.33;0.61]    < 1e-04 \n#>               45 to 54 years      0.45 [0.34;0.61]    < 1e-04 \n#>               55 to 64 years      0.41 [0.30;0.56]    < 1e-04 \n#>            65 years or older      0.87 [0.59;1.27]   0.468623 \n#>       race         Non-white       Ref                        \n#>                        White      1.32 [1.03;1.71]   0.030025\n```\n:::\n\n\n",
    "supporting": [
      "accessingEsolution_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}