---
title: "Quiz on mediation analysis"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, warning=FALSE, message=FALSE, include=FALSE}
# Load required packages
library(learnr)
library(xfun)
```

```{r nonbinary_quiz1, echo=FALSE}
question("Q1. What is the appropriate way to justify the causal and relational assumptions behind the mediation analysis?",
  answer("Significance/hypothesis testing always at 5% level of significance."),
  answer("Use standardized mean difference, with cut point 0.1 or 0.2."),
  answer("Use subject-area expertise / knowledge to explain/justify the causal and biological mechanism and relationships as much as possible.", correct = TRUE),
  answer("Impute missing variables if they are not measured at baseline."),
  allow_retry = TRUE,
  random_answer_order = FALSE,
)
```

```{r nonbinary_quiz2, echo=FALSE}
question("Q2. Which is the recommended aprroach to estimate the standard error in mediation analysis?",
  answer("Model based"),
  answer("Cross-validation"),
  answer("Bootstrap with a large number of replications, e.g., 250", correct = TRUE),
  answer("Bootstrap with 5 replications"),
  allow_retry = TRUE,
  random_answer_order = TRUE
)
```
