{
  "hash": "c83d29547e61a329721423607e5aef21",
  "result": {
    "markdown": "## PS Weighting (US) {.unnumbered}\n\n\n\n\n\n\n\n### Propensity analysis problem\n\nIn this chapter, we will use **propensity score weighting** (using SMD cut-point 0.2, may adjust for imbalanced and/or all covariates in the outcome model, if any) analysis as per the following recommendations - [@zanutto2006comparison] - [@dugoff2014generalizing] - [@austin2018propensity]\n\n#### Dataset\n\n-   The following modified NHANES dataset\n    -   NHANES15lab5.RData\n-   use the data set \"analytic.with.miss\" within this file.\n    -   for obtaining the final treatment effect estimates, you can omit missing values, but only after creating the design (e.g., subset the design, not the data itself directly).\n-   The same dataset was used for [**propensity score weighting**](propensityscore4.html)\n\n#### Variables\n\n-   Outcome: diabetes\n    -   'No' as the reference category\n-   Exposure: bmi\n    -   convert to binary with \\>25 vs. \\<= 25,\n    -   with \\> 25 as the reference category\n-   Confounder list:\n    -   gender\n    -   age\n        -   assume continuous\n    -   race\n    -   income\n    -   education\n    -   married\n    -   cholesterol\n    -   diastolicBP\n    -   systolicBP\n-   Mediator:\n    -   physical.work\n        -   'No' as the reference category\n-   Survey features\n    -   psu\n    -   strata\n    -   weight\n\n### Pre-processing\n\n#### Load data\n\n\n\n::: {.cell hash='propensityscore6_cache/pdf/data_4a9bfb2935f5b9154b4c4762ff05e59e'}\n\n```{.r .cell-code}\nload(file=\"Data/propensityscore/NHANES15lab5.RData\")\n```\n:::\n\n\n\n#### Variable summary\n\n\n\n::: {.cell hash='propensityscore6_cache/pdf/varsum_29440d485b7253e8e6187bb22ceb704e'}\n\n```{.r .cell-code}\n# Full data\ndat.full <- analytic.with.miss\n\n# Exposure\ndat.full$bmi <- with(dat.full, ifelse(bmi>25, \"Overweight\", \n                                      ifelse(bmi<=25, \"Not overweight\", NA)))\ndat.full$bmi <- as.factor(dat.full$bmi)\ndat.full$bmi <- relevel(dat.full$bmi, ref = \"Overweight\")\n\n# Drop unnecessary variables \ndat.full$born <- NULL\ndat.full$physical.work <- NULL\n\n# Rename the weight variable into interview.weight\nnames(dat.full)[names(dat.full) == \"weight\"] <- \"interview.weight\"\n```\n:::\n\n\n\n#### Complete case data\n\nWe will use the complete case data to perform the analysis.\n\n\n\n::: {.cell hash='propensityscore6_cache/pdf/ccdata_bb089ebf9192c9984f3258dd34f65b74'}\n\n```{.r .cell-code}\n# Complete case data \nanalytic.data <- dat.full[complete.cases(dat.full),]\ndim(analytic.data)\n#> [1] 6316   15\n```\n:::\n\n\n\n#### Reproducibility\n\n\n\n::: {.cell hash='propensityscore6_cache/pdf/seed_e2c0e13f32326b4ea7c75ff319a9f07d'}\n\n```{.r .cell-code}\nset.seed(504)\n```\n:::\n\n\n\n### Approach by Zanutto (2006)\n\n#### Step 1\n\n\n\n::: {.cell hash='propensityscore6_cache/pdf/Zanstep1_c2eca73848b35b48296879160d9a54e5'}\n\n```{.r .cell-code}\n# Specify the PS model to estimate propensity scores\nps.formula <- as.formula(I(bmi==\"Not overweight\") ~ gender + age + race + income + education + \n                           married + cholesterol + diastolicBP + systolicBP)\n```\n:::\n\n\n\n#### Step 2\n\nFor the second step, we will calculate the both unstabilized and stabilized weights. However, stabilized inverse probability weight is often recommended to prevent from extreme weights [@hernan2006estimating].\n\n\n\n::: {.cell hash='propensityscore6_cache/pdf/Zanstep2_4a5d436b89ae7c49d61b5413477d34ce'}\n\n```{.r .cell-code}\n# Propensity scores\nps.fit <- glm(ps.formula, data = analytic.data, family = binomial(\"logit\"))\nanalytic.data$ps <- predict(ps.fit, type = \"response\", newdata = analytic.data)\n\n# Unstabilized weight\nanalytic.data$usweight <- with(analytic.data, ifelse(I(bmi==\"Not overweight\"), \n                                                     1/ps, 1/(1-ps)))\n\n# Unstabilized weight summary\nround(summary(analytic.data$usweight), 2)\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>    1.01    1.33    1.63    2.10    2.14   62.31\n\n# Stabilized weight\nanalytic.data$sweight <- with(analytic.data, ifelse(I(bmi==\"Not overweight\"), \n                                                    mean(I(bmi==\"Not overweight\"))/ps, \n                                                    (1-mean(I(bmi==\"Not overweight\")))/(1-ps)))\n\n# Stabilized weight summary\nround(summary(analytic.data$sweight), 2)\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>    0.44    0.70    0.84    1.04    1.08   25.40\n```\n:::\n\n\n\nWe can see that the mean of stabilized weights is 1, while it is approximately 2.1 for unstabilized weights. For both unstabilized and stabilized weights, it seems there are extreme weights, particularly for the unstabilized weights. Extreme weights could be dealt with weight truncation, typically truncated at the 1st and 99th percentiles [@cole2008constructing].\n\nLet us truncate the weights at the 1st and 99th percentiles\n\n\n\n::: {.cell hash='propensityscore6_cache/pdf/wgttruc_fec30d1ef4e74e405dad32a005215c4d'}\n\n```{.r .cell-code}\n# Truncating unstabilized weight\nanalytic.data <- analytic.data %>% \n  mutate(usweight_t = pmin(pmax(usweight, quantile(usweight, 0.01)), \n                           quantile(usweight, 0.99)))\nsummary(analytic.data$usweight_t)\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>   1.055   1.335   1.629   2.020   2.140  10.912\n\n# Truncating stabilized weight\nanalytic.data <- analytic.data %>% \n  mutate(sweight_t = pmin(pmax(sweight, quantile(sweight, 0.01)), \n                          quantile(sweight, 0.99)))\nsummary(analytic.data$sweight_t)\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>  0.4861  0.7035  0.8400  1.0044  1.0833  4.4901\n```\n:::\n\n\n\n#### Step 3\n\nNow we will check the distribution of the covariates by the exposure status on the pseudo population in terms of pre-specified SMD.\n\n\n\n::: {.cell hash='propensityscore6_cache/pdf/Zanstep3_5eaa024b25fd1f98e47feedbd356774b'}\n\n```{.r .cell-code}\n# Covariates\nvars <- c(\"gender\", \"age\", \"race\", \"income\", \"education\", \"married\", \"cholesterol\", \n         \"diastolicBP\", \"systolicBP\")\n\n# Design with truncated unstabilized weight\ndesign.unstab <- svydesign(ids = ~ID, weights = ~usweight_t, data = analytic.data)\n\n# Design with truncated stabilized weight\ndesign.stab <- svydesign(ids = ~ID, weights = ~sweight_t, data = analytic.data)\n\n# Balance checking with truncated unstabilized weight\ntab.unstab <- svyCreateTableOne(vars = vars, strata = \"bmi\", data = design.unstab, test = F)\nprint(tab.unstab, smd = T)\n#>                          Stratified by bmi\n#>                           Overweight      Not overweight  SMD   \n#>   n                        6199.3          6559.7               \n#>   gender = Male (%)        2999.3 (48.4)   3126.6 (47.7)   0.014\n#>   age (mean (SD))           48.38 (17.38)   49.83 (18.11)  0.082\n#>   race (%)                                                 0.047\n#>      Black                 1304.7 (21.0)   1407.8 (21.5)        \n#>      Hispanic              1901.9 (30.7)   1873.7 (28.6)        \n#>      Other                  956.4 (15.4)   1029.3 (15.7)        \n#>      White                 2036.2 (32.8)   2249.0 (34.3)        \n#>   income (%)                                               0.033\n#>      <25k                  1664.3 (26.8)   1829.5 (27.9)        \n#>      Between.25kto54k      1986.5 (32.0)   2133.5 (32.5)        \n#>      Between.55kto99k      1449.1 (23.4)   1466.6 (22.4)        \n#>      Over100k              1099.4 (17.7)   1130.0 (17.2)        \n#>   education (%)                                            0.019\n#>      College               3469.5 (56.0)   3610.4 (55.0)        \n#>      High.School           2047.7 (33.0)   2217.9 (33.8)        \n#>      School                 682.1 (11.0)    731.4 (11.1)        \n#>   married (%)                                              0.040\n#>      Married               3728.2 (60.1)   3853.6 (58.7)        \n#>      Never.married         1101.9 (17.8)   1147.0 (17.5)        \n#>      Previously.married    1369.2 (22.1)   1559.1 (23.8)        \n#>   cholesterol (mean (SD))  181.58 (40.93)  183.13 (43.59)  0.037\n#>   diastolicBP (mean (SD))   66.31 (14.64)   66.87 (14.78)  0.038\n#>   systolicBP (mean (SD))   121.04 (16.61)  123.60 (23.62)  0.125\n\n# Balance checking with truncated stabilized weight\ntab.stab <- svyCreateTableOne(vars = vars, strata = \"bmi\", data = design.stab, test = F)\nprint(tab.stab, smd = T)\n#>                          Stratified by bmi\n#>                           Overweight      Not overweight  SMD   \n#>   n                        3665.9          2677.9               \n#>   gender = Male (%)        1771.7 (48.3)   1276.5 (47.7)   0.013\n#>   age (mean (SD))           48.40 (17.38)   49.84 (18.12)  0.081\n#>   race (%)                                                 0.048\n#>      Black                  772.6 (21.1)    575.0 (21.5)        \n#>      Hispanic              1126.3 (30.7)    764.6 (28.6)        \n#>      Other                  561.1 (15.3)    420.5 (15.7)        \n#>      White                 1206.0 (32.9)    917.9 (34.3)        \n#>   income (%)                                               0.033\n#>      <25k                   982.8 (26.8)    747.3 (27.9)        \n#>      Between.25kto54k      1176.4 (32.1)    870.8 (32.5)        \n#>      Between.55kto99k       857.6 (23.4)    598.5 (22.3)        \n#>      Over100k               649.2 (17.7)    461.3 (17.2)        \n#>   education (%)                                            0.019\n#>      College               2051.4 (56.0)   1473.3 (55.0)        \n#>      High.School           1210.5 (33.0)    905.9 (33.8)        \n#>      School                 404.0 (11.0)    298.7 (11.2)        \n#>   married (%)                                              0.040\n#>      Married               2205.9 (60.2)   1572.9 (58.7)        \n#>      Never.married          650.0 (17.7)    468.0 (17.5)        \n#>      Previously.married     810.1 (22.1)    637.1 (23.8)        \n#>   cholesterol (mean (SD))  181.62 (40.91)  183.15 (43.61)  0.036\n#>   diastolicBP (mean (SD))   66.37 (14.53)   66.87 (14.81)  0.034\n#>   systolicBP (mean (SD))   121.06 (16.58)  123.63 (23.65)  0.126\n```\n:::\n\n\n\nAs we can see, all SMDs are less than our specified cut-point of 0.2, indicating that there is good covariate balancing. next, we will fit the outcome model on the pseudo population (i.e., weighted data). Note that we must utilize the survey feature as the design for the population-level estimate. For this step, we will multiply propensity score weight and survey weight and create a `new weight` variable.\n\n#### Step 4 - with unstabilized weight\n\n\n\n::: {.cell hash='propensityscore6_cache/pdf/Zanstep4_9882acea139e25abcf17ce39ca88e567'}\n\n```{.r .cell-code}\nrequire(survey)\nrequire(jtools)\n\n# Create an indicator variable in the full dataset\ndat.full$ind <- 0\ndat.full$ind[dat.full$ID %in% analytic.data$ID] <- 1\n\n# New weight = interview weight * unstabilized weight \nanalytic.data$new.usweight_t <- with(analytic.data, interview.weight * usweight_t)\nsummary(analytic.data$new.usweight_t)\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>    6437   26567   42862   77768   88106 1831548\n\n#  New weight variable in the full dataset\ndat.full$new.usweight_t <- 0\ndat.full$new.usweight_t[dat.full$ID %in% analytic.data$ID] <- \n  analytic.data$new.usweight_t\nsummary(dat.full$new.usweight_t)\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>       0       0   24068   49261   55161 1831548\n\n# Survey setup with full data \nw.design0 <- svydesign(id = ~psu, strata = ~strata, weights = ~new.usweight_t, \n                      data = dat.full, nest = TRUE)\n\n# Subset the design for analytic sample\nw.design.s <- subset(w.design0, ind == 1)\n\n# Outcome model\nout.formula <- as.formula(I(diabetes == \"Yes\") ~ bmi)\nfit <- svyglm(out.formula, design = w.design.s, family = binomial(\"logit\"))\nsumm(fit, exp = TRUE, confint = TRUE, digits = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}[!h]\n\\centering\n\\begin{tabular}{lr}\n\\toprule\n\\cellcolor{gray!6}{Observations} & \\cellcolor{gray!6}{6316}\\\\\nDependent variable & I(diabetes == \"Yes\")\\\\\n\\cellcolor{gray!6}{Type} & \\cellcolor{gray!6}{Survey-weighted generalized linear model}\\\\\nFamily & binomial\\\\\n\\cellcolor{gray!6}{Link} & \\cellcolor{gray!6}{logit}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{tabular}{lr}\n\\toprule\n\\cellcolor{gray!6}{Pseudo-R² (Cragg-Uhler)} & \\cellcolor{gray!6}{0.062}\\\\\nPseudo-R² (McFadden) & 0.047\\\\\n\\cellcolor{gray!6}{AIC} & \\cellcolor{gray!6}{3371.907}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{threeparttable}\n\\begin{tabular}{lrrrrr}\n\\toprule\n  & exp(Est.) & 2.5\\% & 97.5\\% & t val. & p\\\\\n\\midrule\n\\cellcolor{gray!6}{(Intercept)} & \\cellcolor{gray!6}{0.164} & \\cellcolor{gray!6}{0.141} & \\cellcolor{gray!6}{0.190} & \\cellcolor{gray!6}{-24.213} & \\cellcolor{gray!6}{0.000}\\\\\nbmiNot overweight & 0.280 & 0.217 & 0.361 & -9.814 & 0.000\\\\\n\\bottomrule\n\\end{tabular}\n\\begin{tablenotes}\n\\item Standard errors: Robust\n\\end{tablenotes}\n\\end{threeparttable}\n\\end{table}\n:::\n:::\n\n\n\n#### Step 4 - with stabilized weight\n\nSimilarly, we can fit the outcome model with stabilized weights.\n\n\n\n::: {.cell hash='propensityscore6_cache/pdf/Zanstep4stab_b6c06c5866914653e84bfb745d51bb8d'}\n\n```{.r .cell-code}\n# Create an indicator variable in the full dataset\ndat.full$ind <- 0\ndat.full$ind[dat.full$ID %in% analytic.data$ID] <- 1\n\n# New weight = interview weight * stabilized weight\nanalytic.data$new.sweight_t <- with(analytic.data, interview.weight * sweight_t)\nsummary(analytic.data$new.sweight_t)\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>    2985   13311   22494   39174   43896  753678\n\n#  New weight variable in the full dataset\ndat.full$new.sweight_t <- 0\ndat.full$new.sweight_t[dat.full$ID %in% analytic.data$ID] <- analytic.data$new.sweight_t\nsummary(dat.full$new.sweight_t)\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>       0       0   12115   24814   28232  753678\n\n# Survey setup with full data \nw.design0 <- svydesign(id = ~psu, strata = ~strata, weights = ~new.sweight_t, \n                       data = dat.full, nest = TRUE)\n\n# Subset the design for analytic sample\nw.design.s2 <- subset(w.design0, ind == 1)\n\n# Outcome model\nout.formula <- as.formula(I(diabetes == \"Yes\") ~ bmi)\nfit.stab <- svyglm(out.formula, design = w.design.s2, family = binomial(\"logit\"))\nsumm(fit.stab, exp = TRUE, confint = TRUE, digits = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}[!h]\n\\centering\n\\begin{tabular}{lr}\n\\toprule\n\\cellcolor{gray!6}{Observations} & \\cellcolor{gray!6}{6316}\\\\\nDependent variable & I(diabetes == \"Yes\")\\\\\n\\cellcolor{gray!6}{Type} & \\cellcolor{gray!6}{Survey-weighted generalized linear model}\\\\\nFamily & binomial\\\\\n\\cellcolor{gray!6}{Link} & \\cellcolor{gray!6}{logit}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{tabular}{lr}\n\\toprule\n\\cellcolor{gray!6}{Pseudo-R² (Cragg-Uhler)} & \\cellcolor{gray!6}{0.055}\\\\\nPseudo-R² (McFadden) & 0.041\\\\\n\\cellcolor{gray!6}{AIC} & \\cellcolor{gray!6}{3712.451}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{threeparttable}\n\\begin{tabular}{lrrrrr}\n\\toprule\n  & exp(Est.) & 2.5\\% & 97.5\\% & t val. & p\\\\\n\\midrule\n\\cellcolor{gray!6}{(Intercept)} & \\cellcolor{gray!6}{0.164} & \\cellcolor{gray!6}{0.141} & \\cellcolor{gray!6}{0.190} & \\cellcolor{gray!6}{-24.235} & \\cellcolor{gray!6}{0.000}\\\\\nbmiNot overweight & 0.280 & 0.217 & 0.361 & -9.815 & 0.000\\\\\n\\bottomrule\n\\end{tabular}\n\\begin{tablenotes}\n\\item Standard errors: Robust\n\\end{tablenotes}\n\\end{threeparttable}\n\\end{table}\n:::\n:::\n\n\n\n#### Double adjustment\n\n\n\n::: {.cell hash='propensityscore6_cache/pdf/Zandoubleadj_4aa879c82f2296c98e394d1a289d4e65'}\n\n```{.r .cell-code}\nlibrary(survey)\n# Outcome model with covariates adjustment\nfit.DA <- svyglm(I(diabetes == \"Yes\") ~ bmi + gender + age + race + income + \n                 education + married + cholesterol + diastolicBP + systolicBP, \n               design = w.design.s2, family = binomial(\"logit\"))\nsumm(fit.DA, exp = TRUE, confint = TRUE, digits = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}[!h]\n\\centering\n\\begin{tabular}{lr}\n\\toprule\n\\cellcolor{gray!6}{Observations} & \\cellcolor{gray!6}{6316}\\\\\nDependent variable & I(diabetes == \"Yes\")\\\\\n\\cellcolor{gray!6}{Type} & \\cellcolor{gray!6}{Survey-weighted generalized linear model}\\\\\nFamily & binomial\\\\\n\\cellcolor{gray!6}{Link} & \\cellcolor{gray!6}{logit}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{tabular}{lr}\n\\toprule\n\\cellcolor{gray!6}{Pseudo-R² (Cragg-Uhler)} & \\cellcolor{gray!6}{0.194}\\\\\nPseudo-R² (McFadden) & 0.149\\\\\n\\cellcolor{gray!6}{AIC} & \\cellcolor{gray!6}{3331.238}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{threeparttable}\n\\begin{tabular}{lrrrrr}\n\\toprule\n  & exp(Est.) & 2.5\\% & 97.5\\% & t val. & p\\\\\n\\midrule\n\\cellcolor{gray!6}{(Intercept)} & \\cellcolor{gray!6}{0.045} & \\cellcolor{gray!6}{0.015} & \\cellcolor{gray!6}{0.133} & \\cellcolor{gray!6}{-5.608} & \\cellcolor{gray!6}{NA}\\\\\nbmiNot overweight & 0.234 & 0.175 & 0.312 & -9.826 & NA\\\\\n\\cellcolor{gray!6}{genderMale} & \\cellcolor{gray!6}{1.402} & \\cellcolor{gray!6}{1.190} & \\cellcolor{gray!6}{1.652} & \\cellcolor{gray!6}{4.038} & \\cellcolor{gray!6}{NA}\\\\\nage & 1.050 & 1.041 & 1.058 & 11.793 & NA\\\\\n\\cellcolor{gray!6}{raceHispanic} & \\cellcolor{gray!6}{0.790} & \\cellcolor{gray!6}{0.600} & \\cellcolor{gray!6}{1.040} & \\cellcolor{gray!6}{-1.677} & \\cellcolor{gray!6}{NA}\\\\\n\\addlinespace\nraceOther & 0.849 & 0.428 & 1.683 & -0.470 & NA\\\\\n\\cellcolor{gray!6}{raceWhite} & \\cellcolor{gray!6}{0.541} & \\cellcolor{gray!6}{0.371} & \\cellcolor{gray!6}{0.789} & \\cellcolor{gray!6}{-3.192} & \\cellcolor{gray!6}{NA}\\\\\nincomeBetween.25kto54k & 0.723 & 0.478 & 1.093 & -1.540 & NA\\\\\n\\cellcolor{gray!6}{incomeBetween.55kto99k} & \\cellcolor{gray!6}{0.647} & \\cellcolor{gray!6}{0.411} & \\cellcolor{gray!6}{1.018} & \\cellcolor{gray!6}{-1.883} & \\cellcolor{gray!6}{NA}\\\\\nincomeOver100k & 0.476 & 0.309 & 0.733 & -3.371 & NA\\\\\n\\addlinespace\n\\cellcolor{gray!6}{educationHigh.School} & \\cellcolor{gray!6}{0.937} & \\cellcolor{gray!6}{0.725} & \\cellcolor{gray!6}{1.211} & \\cellcolor{gray!6}{-0.498} & \\cellcolor{gray!6}{NA}\\\\\neducationSchool & 0.930 & 0.568 & 1.524 & -0.286 & NA\\\\\n\\cellcolor{gray!6}{marriedNever.married} & \\cellcolor{gray!6}{0.895} & \\cellcolor{gray!6}{0.628} & \\cellcolor{gray!6}{1.275} & \\cellcolor{gray!6}{-0.615} & \\cellcolor{gray!6}{NA}\\\\\nmarriedPreviously.married & 0.791 & 0.529 & 1.184 & -1.137 & NA\\\\\n\\cellcolor{gray!6}{cholesterol} & \\cellcolor{gray!6}{0.993} & \\cellcolor{gray!6}{0.990} & \\cellcolor{gray!6}{0.997} & \\cellcolor{gray!6}{-3.760} & \\cellcolor{gray!6}{NA}\\\\\n\\addlinespace\ndiastolicBP & 1.007 & 0.999 & 1.014 & 1.744 & NA\\\\\n\\cellcolor{gray!6}{systolicBP} & \\cellcolor{gray!6}{1.002} & \\cellcolor{gray!6}{0.993} & \\cellcolor{gray!6}{1.012} & \\cellcolor{gray!6}{0.529} & \\cellcolor{gray!6}{NA}\\\\\n\\bottomrule\n\\end{tabular}\n\\begin{tablenotes}\n\\item Standard errors: Robust\n\\end{tablenotes}\n\\end{threeparttable}\n\\end{table}\n:::\n\n```{.r .cell-code}\n\n# Log odds ratio with p-values\nsummary(fit.DA, df.resid = degf(w.design.s2))\n#> \n#> Call:\n#> svyglm(formula = I(diabetes == \"Yes\") ~ bmi + gender + age + \n#>     race + income + education + married + cholesterol + diastolicBP + \n#>     systolicBP, design = w.design.s2, family = binomial(\"logit\"))\n#> \n#> Survey design:\n#> subset(w.design0, ind == 1)\n#> \n#> Coefficients:\n#>                            Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)               -3.095813   0.552073  -5.608 4.99e-05 ***\n#> bmiNot overweight         -1.454514   0.148024  -9.826 6.29e-08 ***\n#> genderMale                 0.338112   0.083733   4.038  0.00107 ** \n#> age                        0.048468   0.004110  11.793 5.48e-09 ***\n#> raceHispanic              -0.235285   0.140287  -1.677  0.11422    \n#> raceOther                 -0.164132   0.349277  -0.470  0.64517    \n#> raceWhite                 -0.613643   0.192233  -3.192  0.00606 ** \n#> incomeBetween.25kto54k    -0.324911   0.211048  -1.540  0.14451    \n#> incomeBetween.55kto99k    -0.435472   0.231288  -1.883  0.07927 .  \n#> incomeOver100k            -0.742995   0.220399  -3.371  0.00420 ** \n#> educationHigh.School      -0.065157   0.130721  -0.498  0.62540    \n#> educationSchool           -0.072034   0.251806  -0.286  0.77874    \n#> marriedNever.married      -0.110932   0.180496  -0.615  0.54803    \n#> marriedPreviously.married -0.233875   0.205646  -1.137  0.27327    \n#> cholesterol               -0.006873   0.001828  -3.760  0.00189 ** \n#> diastolicBP                0.006728   0.003859   1.744  0.10169    \n#> systolicBP                 0.002438   0.004605   0.529  0.60430    \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Zero or negative residual df; p-values not defined\n#> \n#> (Dispersion parameter for binomial family taken to be 0.9452878)\n#> \n#> Number of Fisher Scoring iterations: 6\n```\n:::\n\n\n\n::: callout-tip\n**Double adjustment**:\n\nAs explained in the [previous chapter](propensityscore4.html), double adjustment should be applied thoughtfully, with careful consideration of model specification, covariate selection, and underlying assumptions to ensure valid and reliable results. Always consider the specific context of the study and consult statistical guidelines or experts when applying advanced methods like double adjustment in propensity score analysis.\n:::\n\n### Approach by DuGoff et al. (2014)\n\n#### Step 1\n\n\n\n::: {.cell hash='propensityscore6_cache/pdf/duGstep1_a9532296612ee5e2a95b4ed4201bd236'}\n\n```{.r .cell-code}\n# Specify the PS model to estimate propensity scores\nps.formula2 <- as.formula(I(bmi == \"Not overweight\") ~ gender + age + race + income + education + \n                           married + cholesterol + diastolicBP + systolicBP + \n                           psu + strata + interview.weight)\n```\n:::\n\n\n\n#### Step 2\n\n\n\n::: {.cell hash='propensityscore6_cache/pdf/duGstep2_76040d286a5bf0527cdaabff3c814bb2'}\n\n```{.r .cell-code}\n# Propensity scores\nps.fit2 <- glm(ps.formula2, data = analytic.data, family = binomial(\"logit\"))\nanalytic.data$ps2 <- fitted(ps.fit2)\n\n# Stabilized weight\nanalytic.data$sweight.dug <- with(analytic.data, ifelse(I(bmi==\"Not overweight\"), \n                                                    mean(I(bmi==\"Not overweight\"))/ps2, \n                                                    (1-mean(I(bmi==\"Not overweight\")))/(1-ps2)))\nsummary(analytic.data$sweight.dug)\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>  0.4349  0.6942  0.8296  1.0307  1.0859 23.0226\n\n# Truncating stabilized weight\nanalytic.data <- analytic.data %>% \n  mutate(sweight.dug_t = pmin(pmax(sweight.dug, quantile(sweight.dug, 0.01)), \n                          quantile(sweight.dug, 0.99)))\nsummary(analytic.data$sweight.dug_t)\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>  0.4802  0.6942  0.8296  1.0019  1.0859  4.4041\n```\n:::\n\n\n\n#### Step 3\n\n\n\n::: {.cell hash='propensityscore6_cache/pdf/duGstep3_55d066af9567533d9b0bc9a3baf3a9f3'}\n\n```{.r .cell-code}\n# Balance checking\ncov2 <- c(\"gender\", \"age\", \"race\", \"income\", \"education\", \"married\", \"cholesterol\", \n         \"diastolicBP\", \"systolicBP\")\n\n# Design with truncated stabilized weight\ndesign.stab <- svydesign(ids = ~ID, weights = ~sweight.dug_t, data = analytic.data)\n\n# Balance checking with truncated stabilized weight\ntab.stab2 <- svyCreateTableOne(vars = cov2, strata = \"bmi\", data = design.stab, test = F)\nprint(tab.stab2, smd = T)\n#>                          Stratified by bmi\n#>                           Overweight      Not overweight  SMD   \n#>   n                        3652.9          2675.0               \n#>   gender = Male (%)        1766.5 (48.4)   1276.8 (47.7)   0.013\n#>   age (mean (SD))           48.47 (17.42)   49.80 (17.99)  0.075\n#>   race (%)                                                 0.056\n#>      Black                  769.1 (21.1)    568.7 (21.3)        \n#>      Hispanic              1121.5 (30.7)    755.4 (28.2)        \n#>      Other                  553.0 (15.1)    417.0 (15.6)        \n#>      White                 1209.4 (33.1)    933.9 (34.9)        \n#>   income (%)                                               0.023\n#>      <25k                   982.1 (26.9)    734.0 (27.4)        \n#>      Between.25kto54k      1172.1 (32.1)    871.1 (32.6)        \n#>      Between.55kto99k       846.1 (23.2)    597.0 (22.3)        \n#>      Over100k               652.6 (17.9)    472.9 (17.7)        \n#>   education (%)                                            0.012\n#>      College               2049.1 (56.1)   1484.2 (55.5)        \n#>      High.School           1202.5 (32.9)    893.7 (33.4)        \n#>      School                 401.3 (11.0)    297.1 (11.1)        \n#>   married (%)                                              0.035\n#>      Married               2201.3 (60.3)   1581.2 (59.1)        \n#>      Never.married          647.4 (17.7)    465.6 (17.4)        \n#>      Previously.married     804.2 (22.0)    628.2 (23.5)        \n#>   cholesterol (mean (SD))  181.74 (40.94)  182.97 (43.25)  0.029\n#>   diastolicBP (mean (SD))   66.46 (14.42)   66.88 (14.79)  0.029\n#>   systolicBP (mean (SD))   121.14 (16.59)  123.39 (23.38)  0.111\n```\n:::\n\n\n\nAll SMDs are less than our specified cut-point of 0.2.\n\n#### Step 4\n\n\n\n::: {.cell hash='propensityscore6_cache/pdf/duGstep4_dc12c7f2812c9d18eba330eed2e21f87'}\n\n```{.r .cell-code}\n# Create an indicator variable in the full dataset\ndat.full$ind <- 0\ndat.full$ind[dat.full$ID %in% analytic.data$ID] <- 1\n\n# New weight = interview weight * stabilized weight\nanalytic.data$new.sweight.dug_t <- with(analytic.data, interview.weight * sweight.dug_t)\nsummary(analytic.data$new.sweight.dug_t)\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>    2996   13343   22260   39436   43914  855145\n\n#  New weight variable in the full dataset\ndat.full$new.sweight.dug_t <- 0\ndat.full$new.sweight.dug_t[dat.full$ID %in% analytic.data$ID] <- analytic.data$new.sweight.dug_t\nsummary(dat.full$new.sweight.dug_t)\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>       0       0   12058   24980   28225  855145\n\n# Survey setup with full data \nw.design0 <- svydesign(id = ~psu, strata = ~strata, weights = ~new.sweight.dug_t, \n                       data = dat.full, nest = TRUE)\n\n# Subset the design for analytic sample\nw.design.s2 <- subset(w.design0, ind == 1)\n\n# Outcome model\nout.formula <- as.formula(I(diabetes == \"Yes\") ~ bmi)\nfit.stab.dug <- svyglm(out.formula, design = w.design.s2, family = binomial(\"logit\"))\nsumm(fit.stab.dug, exp = TRUE, confint = TRUE, digits = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}[!h]\n\\centering\n\\begin{tabular}{lr}\n\\toprule\n\\cellcolor{gray!6}{Observations} & \\cellcolor{gray!6}{6316}\\\\\nDependent variable & I(diabetes == \"Yes\")\\\\\n\\cellcolor{gray!6}{Type} & \\cellcolor{gray!6}{Survey-weighted generalized linear model}\\\\\nFamily & binomial\\\\\n\\cellcolor{gray!6}{Link} & \\cellcolor{gray!6}{logit}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{tabular}{lr}\n\\toprule\n\\cellcolor{gray!6}{Pseudo-R² (Cragg-Uhler)} & \\cellcolor{gray!6}{0.060}\\\\\nPseudo-R² (McFadden) & 0.045\\\\\n\\cellcolor{gray!6}{AIC} & \\cellcolor{gray!6}{3518.691}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{threeparttable}\n\\begin{tabular}{lrrrrr}\n\\toprule\n  & exp(Est.) & 2.5\\% & 97.5\\% & t val. & p\\\\\n\\midrule\n\\cellcolor{gray!6}{(Intercept)} & \\cellcolor{gray!6}{0.161} & \\cellcolor{gray!6}{0.140} & \\cellcolor{gray!6}{0.185} & \\cellcolor{gray!6}{-26.027} & \\cellcolor{gray!6}{0.000}\\\\\nbmiNot overweight & 0.272 & 0.203 & 0.364 & -8.727 & 0.000\\\\\n\\bottomrule\n\\end{tabular}\n\\begin{tablenotes}\n\\item Standard errors: Robust\n\\end{tablenotes}\n\\end{threeparttable}\n\\end{table}\n:::\n:::\n\n\n\n#### Double adjustment\n\n\n\n::: {.cell hash='propensityscore6_cache/pdf/duGdoubleadj2_361989f4b9d1a23f9541ae9fbcf969a9'}\n\n```{.r .cell-code}\n# Outcome model with covariates adjustment\nfit2.DA <- svyglm(I(diabetes == \"Yes\") ~ bmi + gender + age + race + income + \n                 education + married + cholesterol + diastolicBP + systolicBP, \n               design = w.design.s2, family = binomial(\"logit\"))\nsumm(fit2.DA, exp = TRUE, confint = TRUE, digits = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}[!h]\n\\centering\n\\begin{tabular}{lr}\n\\toprule\n\\cellcolor{gray!6}{Observations} & \\cellcolor{gray!6}{6316}\\\\\nDependent variable & I(diabetes == \"Yes\")\\\\\n\\cellcolor{gray!6}{Type} & \\cellcolor{gray!6}{Survey-weighted generalized linear model}\\\\\nFamily & binomial\\\\\n\\cellcolor{gray!6}{Link} & \\cellcolor{gray!6}{logit}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{tabular}{lr}\n\\toprule\n\\cellcolor{gray!6}{Pseudo-R² (Cragg-Uhler)} & \\cellcolor{gray!6}{0.196}\\\\\nPseudo-R² (McFadden) & 0.152\\\\\n\\cellcolor{gray!6}{AIC} & \\cellcolor{gray!6}{3154.781}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{threeparttable}\n\\begin{tabular}{lrrrrr}\n\\toprule\n  & exp(Est.) & 2.5\\% & 97.5\\% & t val. & p\\\\\n\\midrule\n\\cellcolor{gray!6}{(Intercept)} & \\cellcolor{gray!6}{0.043} & \\cellcolor{gray!6}{0.014} & \\cellcolor{gray!6}{0.131} & \\cellcolor{gray!6}{-5.537} & \\cellcolor{gray!6}{NA}\\\\\nbmiNot overweight & 0.235 & 0.169 & 0.325 & -8.730 & NA\\\\\n\\cellcolor{gray!6}{genderMale} & \\cellcolor{gray!6}{1.393} & \\cellcolor{gray!6}{1.150} & \\cellcolor{gray!6}{1.688} & \\cellcolor{gray!6}{3.381} & \\cellcolor{gray!6}{NA}\\\\\nage & 1.049 & 1.042 & 1.056 & 13.564 & NA\\\\\n\\cellcolor{gray!6}{raceHispanic} & \\cellcolor{gray!6}{0.813} & \\cellcolor{gray!6}{0.624} & \\cellcolor{gray!6}{1.061} & \\cellcolor{gray!6}{-1.524} & \\cellcolor{gray!6}{NA}\\\\\n\\addlinespace\nraceOther & 0.841 & 0.454 & 1.558 & -0.549 & NA\\\\\n\\cellcolor{gray!6}{raceWhite} & \\cellcolor{gray!6}{0.535} & \\cellcolor{gray!6}{0.369} & \\cellcolor{gray!6}{0.774} & \\cellcolor{gray!6}{-3.316} & \\cellcolor{gray!6}{NA}\\\\\nincomeBetween.25kto54k & 0.720 & 0.492 & 1.053 & -1.693 & NA\\\\\n\\cellcolor{gray!6}{incomeBetween.55kto99k} & \\cellcolor{gray!6}{0.659} & \\cellcolor{gray!6}{0.440} & \\cellcolor{gray!6}{0.985} & \\cellcolor{gray!6}{-2.035} & \\cellcolor{gray!6}{NA}\\\\\nincomeOver100k & 0.491 & 0.338 & 0.713 & -3.735 & NA\\\\\n\\addlinespace\n\\cellcolor{gray!6}{educationHigh.School} & \\cellcolor{gray!6}{0.930} & \\cellcolor{gray!6}{0.753} & \\cellcolor{gray!6}{1.150} & \\cellcolor{gray!6}{-0.667} & \\cellcolor{gray!6}{NA}\\\\\neducationSchool & 0.994 & 0.625 & 1.580 & -0.026 & NA\\\\\n\\cellcolor{gray!6}{marriedNever.married} & \\cellcolor{gray!6}{0.982} & \\cellcolor{gray!6}{0.671} & \\cellcolor{gray!6}{1.439} & \\cellcolor{gray!6}{-0.092} & \\cellcolor{gray!6}{NA}\\\\\nmarriedPreviously.married & 0.783 & 0.534 & 1.150 & -1.245 & NA\\\\\n\\cellcolor{gray!6}{cholesterol} & \\cellcolor{gray!6}{0.993} & \\cellcolor{gray!6}{0.989} & \\cellcolor{gray!6}{0.996} & \\cellcolor{gray!6}{-3.913} & \\cellcolor{gray!6}{NA}\\\\\n\\addlinespace\ndiastolicBP & 1.006 & 0.998 & 1.013 & 1.426 & NA\\\\\n\\cellcolor{gray!6}{systolicBP} & \\cellcolor{gray!6}{1.004} & \\cellcolor{gray!6}{0.995} & \\cellcolor{gray!6}{1.012} & \\cellcolor{gray!6}{0.853} & \\cellcolor{gray!6}{NA}\\\\\n\\bottomrule\n\\end{tabular}\n\\begin{tablenotes}\n\\item Standard errors: Robust\n\\end{tablenotes}\n\\end{threeparttable}\n\\end{table}\n:::\n\n```{.r .cell-code}\n\n# Log odds ratio with p-values\nsummary(fit2.DA, df.resid = degf(w.design.s2))\n#> \n#> Call:\n#> svyglm(formula = I(diabetes == \"Yes\") ~ bmi + gender + age + \n#>     race + income + education + married + cholesterol + diastolicBP + \n#>     systolicBP, design = w.design.s2, family = binomial(\"logit\"))\n#> \n#> Survey design:\n#> subset(w.design0, ind == 1)\n#> \n#> Coefficients:\n#>                            Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)               -3.143943   0.567807  -5.537 5.70e-05 ***\n#> bmiNot overweight         -1.450047   0.166099  -8.730 2.89e-07 ***\n#> genderMale                 0.331561   0.098056   3.381  0.00411 ** \n#> age                        0.047790   0.003523  13.564 7.97e-10 ***\n#> raceHispanic              -0.206657   0.135568  -1.524  0.14822    \n#> raceOther                 -0.172590   0.314341  -0.549  0.59105    \n#> raceWhite                 -0.625821   0.188746  -3.316  0.00471 ** \n#> incomeBetween.25kto54k    -0.328863   0.194223  -1.693  0.11107    \n#> incomeBetween.55kto99k    -0.417687   0.205223  -2.035  0.05989 .  \n#> incomeOver100k            -0.711500   0.190509  -3.735  0.00199 ** \n#> educationHigh.School      -0.072053   0.108040  -0.667  0.51496    \n#> educationSchool           -0.006136   0.236588  -0.026  0.97965    \n#> marriedNever.married      -0.017832   0.194660  -0.092  0.92822    \n#> marriedPreviously.married -0.244058   0.196041  -1.245  0.23226    \n#> cholesterol               -0.007067   0.001806  -3.913  0.00138 ** \n#> diastolicBP                0.005516   0.003869   1.426  0.17440    \n#> systolicBP                 0.003739   0.004381   0.853  0.40682    \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Zero or negative residual df; p-values not defined\n#> \n#> (Dispersion parameter for binomial family taken to be 0.9373219)\n#> \n#> Number of Fisher Scoring iterations: 6\n```\n:::\n\n\n\n### Approach by Austin et al. (2018)\n\n#### Step 1\n\n\n\n::: {.cell hash='propensityscore6_cache/pdf/Ausstep1_dab1fd7a1a7944627d9832476dcf28fb'}\n\n```{.r .cell-code}\n# Specify the PS model to estimate propensity scores\nps.formula3 <- as.formula(I(bmi == \"Not overweight\") ~ gender + age + race + income + education + \n                           married + cholesterol + diastolicBP + systolicBP)\n\n# Survey design\nrequire(survey)\nanalytic.design <- svydesign(id = ~psu, weights = ~interview.weight, strata = ~strata,\n                             data = analytic.data, nest = TRUE)\n```\n:::\n\n\n\n#### Step 2\n\n\n\n::: {.cell hash='propensityscore6_cache/pdf/Ausstep2_7e36490a018a7b25c24838000dcf8bdd'}\n\n```{.r .cell-code}\n# Propensity scores\nps.fit3 <- svyglm(ps.formula3, design = analytic.design, family = binomial(\"logit\"))\nanalytic.data$ps3 <- fitted(ps.fit3)\n\n# Stabilized weight\nanalytic.data$sweight.aus <- with(analytic.data, ifelse(I(bmi==\"Not overweight\"), \n                                                    mean(I(bmi==\"Not overweight\"))/ps3, \n                                                    (1-mean(I(bmi==\"Not overweight\")))/(1-ps3)))\nsummary(analytic.data$sweight.aus)\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>  0.4436  0.7138  0.8410  1.0392  1.0645 26.2776\n\n# Truncating stabilized weight\nanalytic.data <- analytic.data %>% \n  mutate(sweight.aus_t = pmin(pmax(sweight.aus, quantile(sweight.aus, 0.01)), \n                          quantile(sweight.aus, 0.99)))\nsummary(analytic.data$sweight.aus_t)\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>  0.5198  0.7138  0.8410  1.0071  1.0645  4.8830\n```\n:::\n\n\n\n#### Step 3\n\n\n\n::: {.cell hash='propensityscore6_cache/pdf/Ausstep_7b4c27f000835b3c53de23dc6d852454'}\n\n```{.r .cell-code}\n# Balance checking\nvars <- c(\"gender\", \"age\", \"race\", \"income\", \"education\", \"married\", \"cholesterol\", \n          \"diastolicBP\", \"systolicBP\")\n\n# Design with truncated stabilized weight\ndesign.stab <- svydesign(ids = ~ID, weights = ~sweight.aus_t, data = analytic.data)\n\n# Balance checking with truncated stabilized weight\ntab.stab.aus <- svyCreateTableOne(vars = vars, strata = \"bmi\", data = design.stab, test = F)\nprint(tab.stab.aus, smd = T)\n#>                          Stratified by bmi\n#>                           Overweight      Not overweight  SMD   \n#>   n                        3434.3          2926.8               \n#>   gender = Male (%)        1609.8 (46.9)   1458.6 (49.8)   0.059\n#>   age (mean (SD))           48.51 (17.32)   49.95 (18.14)  0.081\n#>   race (%)                                                 0.099\n#>      Black                  737.1 (21.5)    623.8 (21.3)        \n#>      Hispanic              1085.0 (31.6)    826.0 (28.2)        \n#>      Other                  471.2 (13.7)    489.7 (16.7)        \n#>      White                 1141.0 (33.2)    987.3 (33.7)        \n#>   income (%)                                               0.041\n#>      <25k                   933.7 (27.2)    813.0 (27.8)        \n#>      Between.25kto54k      1108.2 (32.3)    946.8 (32.3)        \n#>      Between.55kto99k       776.7 (22.6)    685.4 (23.4)        \n#>      Over100k               615.7 (17.9)    481.6 (16.5)        \n#>   education (%)                                            0.039\n#>      College               1908.2 (55.6)   1601.1 (54.7)        \n#>      High.School           1129.9 (32.9)   1011.4 (34.6)        \n#>      School                 396.2 (11.5)    314.3 (10.7)        \n#>   married (%)                                              0.030\n#>      Married               2063.9 (60.1)   1737.6 (59.4)        \n#>      Never.married          605.8 (17.6)    501.4 (17.1)        \n#>      Previously.married     764.6 (22.3)    687.8 (23.5)        \n#>   cholesterol (mean (SD))  182.67 (41.11)  182.70 (43.38)  0.001\n#>   diastolicBP (mean (SD))   66.76 (14.28)   66.85 (14.85)  0.006\n#>   systolicBP (mean (SD))   121.39 (16.74)  123.98 (23.72)  0.126\n```\n:::\n\n\n\nAll SMDs are less than our specified cut-point of 0.2.\n\n#### Step 4\n\n\n\n::: {.cell hash='propensityscore6_cache/pdf/Ausstep4_086039f427d778d29bc3ec618a5fd214'}\n\n```{.r .cell-code}\n# Create an indicator variable in the full dataset\ndat.full$ind <- 0\ndat.full$ind[dat.full$ID %in% analytic.data$ID] <- 1\n\n# New weight = interview weight * stabilized weight\nanalytic.data$new.sweight.aus_t <- with(analytic.data, interview.weight * sweight.aus_t)\nsummary(analytic.data$new.sweight.aus_t)\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>    3255   13604   22527   38953   43663  819622\n\n#  New weight variable in the full dataset\ndat.full$new.sweight.aus_t <- 0\ndat.full$new.sweight.aus_t[dat.full$ID %in% analytic.data$ID] <- analytic.data$new.sweight.aus_t\nsummary(dat.full$new.sweight.aus_t)\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>       0       0   12356   24675   28169  819622\n\n# Survey setup with full data \nw.design0 <- svydesign(id = ~psu, strata = ~strata, weights = ~new.sweight.aus_t, \n                       data = dat.full, nest = TRUE)\n\n# Subset the design for analytic sample\nw.design.s2 <- subset(w.design0, ind == 1)\n\n# Outcome model\nout.formula <- as.formula(I(diabetes == \"Yes\") ~ bmi)\nfit.stab.aus <- svyglm(out.formula, design = w.design.s2, family = binomial(\"logit\"))\nsumm(fit.stab.aus, exp = TRUE, confint = TRUE, digits = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}[!h]\n\\centering\n\\begin{tabular}{lr}\n\\toprule\n\\cellcolor{gray!6}{Observations} & \\cellcolor{gray!6}{6316}\\\\\nDependent variable & I(diabetes == \"Yes\")\\\\\n\\cellcolor{gray!6}{Type} & \\cellcolor{gray!6}{Survey-weighted generalized linear model}\\\\\nFamily & binomial\\\\\n\\cellcolor{gray!6}{Link} & \\cellcolor{gray!6}{logit}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{tabular}{lr}\n\\toprule\n\\cellcolor{gray!6}{Pseudo-R² (Cragg-Uhler)} & \\cellcolor{gray!6}{0.055}\\\\\nPseudo-R² (McFadden) & 0.041\\\\\n\\cellcolor{gray!6}{AIC} & \\cellcolor{gray!6}{3622.951}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{threeparttable}\n\\begin{tabular}{lrrrrr}\n\\toprule\n  & exp(Est.) & 2.5\\% & 97.5\\% & t val. & p\\\\\n\\midrule\n\\cellcolor{gray!6}{(Intercept)} & \\cellcolor{gray!6}{0.162} & \\cellcolor{gray!6}{0.140} & \\cellcolor{gray!6}{0.187} & \\cellcolor{gray!6}{-24.912} & \\cellcolor{gray!6}{0.000}\\\\\nbmiNot overweight & 0.291 & 0.225 & 0.377 & -9.397 & 0.000\\\\\n\\bottomrule\n\\end{tabular}\n\\begin{tablenotes}\n\\item Standard errors: Robust\n\\end{tablenotes}\n\\end{threeparttable}\n\\end{table}\n:::\n:::\n\n\n\n#### Double adjustment\n\n\n\n::: {.cell hash='propensityscore6_cache/pdf/Ausdoubleadj_209d2a97dccd6b8659c5c8111c92bba9'}\n\n```{.r .cell-code}\n# Outcome model with covariates adjustment\nfit3.DA <- svyglm(I(diabetes == \"Yes\") ~ bmi + gender + age + race + income + \n                 education + married + cholesterol + diastolicBP + systolicBP, \n               design = w.design.s2, family = binomial(\"logit\"))\nsumm(fit3.DA, exp = TRUE, confint = TRUE, digits = 3)\n```\n\n::: {.cell-output-display}\n\\begin{table}[!h]\n\\centering\n\\begin{tabular}{lr}\n\\toprule\n\\cellcolor{gray!6}{Observations} & \\cellcolor{gray!6}{6316}\\\\\nDependent variable & I(diabetes == \"Yes\")\\\\\n\\cellcolor{gray!6}{Type} & \\cellcolor{gray!6}{Survey-weighted generalized linear model}\\\\\nFamily & binomial\\\\\n\\cellcolor{gray!6}{Link} & \\cellcolor{gray!6}{logit}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{tabular}{lr}\n\\toprule\n\\cellcolor{gray!6}{Pseudo-R² (Cragg-Uhler)} & \\cellcolor{gray!6}{0.193}\\\\\nPseudo-R² (McFadden) & 0.149\\\\\n\\cellcolor{gray!6}{AIC} & \\cellcolor{gray!6}{3247.730}\\\\\n\\bottomrule\n\\end{tabular}\n\\end{table} \\begin{table}[!h]\n\\centering\n\\begin{threeparttable}\n\\begin{tabular}{lrrrrr}\n\\toprule\n  & exp(Est.) & 2.5\\% & 97.5\\% & t val. & p\\\\\n\\midrule\n\\cellcolor{gray!6}{(Intercept)} & \\cellcolor{gray!6}{0.045} & \\cellcolor{gray!6}{0.015} & \\cellcolor{gray!6}{0.129} & \\cellcolor{gray!6}{-5.735} & \\cellcolor{gray!6}{NA}\\\\\nbmiNot overweight & 0.233 & 0.175 & 0.311 & -9.886 & NA\\\\\n\\cellcolor{gray!6}{genderMale} & \\cellcolor{gray!6}{1.416} & \\cellcolor{gray!6}{1.186} & \\cellcolor{gray!6}{1.690} & \\cellcolor{gray!6}{3.850} & \\cellcolor{gray!6}{NA}\\\\\nage & 1.049 & 1.041 & 1.057 & 12.066 & NA\\\\\n\\cellcolor{gray!6}{raceHispanic} & \\cellcolor{gray!6}{0.773} & \\cellcolor{gray!6}{0.585} & \\cellcolor{gray!6}{1.022} & \\cellcolor{gray!6}{-1.808} & \\cellcolor{gray!6}{NA}\\\\\n\\addlinespace\nraceOther & 0.867 & 0.451 & 1.666 & -0.428 & NA\\\\\n\\cellcolor{gray!6}{raceWhite} & \\cellcolor{gray!6}{0.520} & \\cellcolor{gray!6}{0.353} & \\cellcolor{gray!6}{0.765} & \\cellcolor{gray!6}{-3.316} & \\cellcolor{gray!6}{NA}\\\\\nincomeBetween.25kto54k & 0.700 & 0.461 & 1.062 & -1.677 & NA\\\\\n\\cellcolor{gray!6}{incomeBetween.55kto99k} & \\cellcolor{gray!6}{0.650} & \\cellcolor{gray!6}{0.407} & \\cellcolor{gray!6}{1.039} & \\cellcolor{gray!6}{-1.801} & \\cellcolor{gray!6}{NA}\\\\\nincomeOver100k & 0.467 & 0.303 & 0.721 & -3.437 & NA\\\\\n\\addlinespace\n\\cellcolor{gray!6}{educationHigh.School} & \\cellcolor{gray!6}{0.948} & \\cellcolor{gray!6}{0.744} & \\cellcolor{gray!6}{1.209} & \\cellcolor{gray!6}{-0.428} & \\cellcolor{gray!6}{NA}\\\\\neducationSchool & 0.976 & 0.598 & 1.592 & -0.099 & NA\\\\\n\\cellcolor{gray!6}{marriedNever.married} & \\cellcolor{gray!6}{0.896} & \\cellcolor{gray!6}{0.629} & \\cellcolor{gray!6}{1.276} & \\cellcolor{gray!6}{-0.609} & \\cellcolor{gray!6}{NA}\\\\\nmarriedPreviously.married & 0.784 & 0.525 & 1.169 & -1.195 & NA\\\\\n\\cellcolor{gray!6}{cholesterol} & \\cellcolor{gray!6}{0.993} & \\cellcolor{gray!6}{0.990} & \\cellcolor{gray!6}{0.997} & \\cellcolor{gray!6}{-3.653} & \\cellcolor{gray!6}{NA}\\\\\n\\addlinespace\ndiastolicBP & 1.005 & 0.998 & 1.013 & 1.412 & NA\\\\\n\\cellcolor{gray!6}{systolicBP} & \\cellcolor{gray!6}{1.004} & \\cellcolor{gray!6}{0.995} & \\cellcolor{gray!6}{1.012} & \\cellcolor{gray!6}{0.826} & \\cellcolor{gray!6}{NA}\\\\\n\\bottomrule\n\\end{tabular}\n\\begin{tablenotes}\n\\item Standard errors: Robust\n\\end{tablenotes}\n\\end{threeparttable}\n\\end{table}\n:::\n\n```{.r .cell-code}\n\n# Log odds ratio with p-values\nsummary(fit3.DA, df.resid = degf(w.design.s2))\n#> \n#> Call:\n#> svyglm(formula = I(diabetes == \"Yes\") ~ bmi + gender + age + \n#>     race + income + education + married + cholesterol + diastolicBP + \n#>     systolicBP, design = w.design.s2, family = binomial(\"logit\"))\n#> \n#> Survey design:\n#> subset(w.design0, ind == 1)\n#> \n#> Coefficients:\n#>                            Estimate Std. Error t value Pr(>|t|)    \n#> (Intercept)               -3.109181   0.542121  -5.735 3.94e-05 ***\n#> bmiNot overweight         -1.456869   0.147369  -9.886 5.81e-08 ***\n#> genderMale                 0.347655   0.090292   3.850  0.00157 ** \n#> age                        0.047457   0.003933  12.066 4.01e-09 ***\n#> raceHispanic              -0.257364   0.142343  -1.808  0.09069 .  \n#> raceOther                 -0.142755   0.333175  -0.428  0.67440    \n#> raceWhite                 -0.653902   0.197190  -3.316  0.00470 ** \n#> incomeBetween.25kto54k    -0.357122   0.212996  -1.677  0.11432    \n#> incomeBetween.55kto99k    -0.430289   0.238964  -1.801  0.09190 .  \n#> incomeOver100k            -0.761311   0.221498  -3.437  0.00367 ** \n#> educationHigh.School      -0.052990   0.123816  -0.428  0.67475    \n#> educationSchool           -0.024734   0.249884  -0.099  0.92246    \n#> marriedNever.married      -0.109989   0.180532  -0.609  0.55148    \n#> marriedPreviously.married -0.243725   0.203990  -1.195  0.25072    \n#> cholesterol               -0.006605   0.001808  -3.653  0.00235 ** \n#> diastolicBP                0.005253   0.003721   1.412  0.17842    \n#> systolicBP                 0.003618   0.004380   0.826  0.42172    \n#> ---\n#> Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n#> \n#> Zero or negative residual df; p-values not defined\n#> \n#> (Dispersion parameter for binomial family taken to be 0.9416613)\n#> \n#> Number of Fisher Scoring iterations: 6\n```\n:::\n\n\n\n### References\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {
      "knitr": [
        "{\"type\":\"list\",\"attributes\":{\"knit_meta_id\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"\",\"Zanstep4\",\"Zanstep4\",\"Zanstep4\",\"Zanstep4\",\"Zanstep4\",\"Zanstep4\",\"Zanstep4\",\"Zanstep4\",\"Zanstep4\",\"Zanstep4\",\"Zanstep4\",\"Zanstep4\",\"Zanstep4\",\"Zanstep4\",\"Zanstep4\",\"Zanstep4stab\",\"Zanstep4stab\",\"Zanstep4stab\",\"Zanstep4stab\",\"Zanstep4stab\",\"Zanstep4stab\",\"Zanstep4stab\",\"Zanstep4stab\",\"Zanstep4stab\",\"Zanstep4stab\",\"Zanstep4stab\",\"Zanstep4stab\",\"Zanstep4stab\",\"Zanstep4stab\",\"Zanstep4stab\",\"Zandoubleadj\",\"Zandoubleadj\",\"Zandoubleadj\",\"Zandoubleadj\",\"Zandoubleadj\",\"Zandoubleadj\",\"Zandoubleadj\",\"Zandoubleadj\",\"Zandoubleadj\",\"Zandoubleadj\",\"Zandoubleadj\",\"Zandoubleadj\",\"Zandoubleadj\",\"Zandoubleadj\",\"Zandoubleadj\",\"duGstep4\",\"duGstep4\",\"duGstep4\",\"duGstep4\",\"duGstep4\",\"duGstep4\",\"duGstep4\",\"duGstep4\",\"duGstep4\",\"duGstep4\",\"duGstep4\",\"duGstep4\",\"duGstep4\",\"duGstep4\",\"duGstep4\",\"duGdoubleadj2\",\"duGdoubleadj2\",\"duGdoubleadj2\",\"duGdoubleadj2\",\"duGdoubleadj2\",\"duGdoubleadj2\",\"duGdoubleadj2\",\"duGdoubleadj2\",\"duGdoubleadj2\",\"duGdoubleadj2\",\"duGdoubleadj2\",\"duGdoubleadj2\",\"duGdoubleadj2\",\"duGdoubleadj2\",\"duGdoubleadj2\",\"Ausstep4\",\"Ausstep4\",\"Ausstep4\",\"Ausstep4\",\"Ausstep4\",\"Ausstep4\",\"Ausstep4\",\"Ausstep4\",\"Ausstep4\",\"Ausstep4\",\"Ausstep4\",\"Ausstep4\",\"Ausstep4\",\"Ausstep4\",\"Ausstep4\",\"Ausdoubleadj\",\"Ausdoubleadj\",\"Ausdoubleadj\",\"Ausdoubleadj\",\"Ausdoubleadj\",\"Ausdoubleadj\",\"Ausdoubleadj\",\"Ausdoubleadj\",\"Ausdoubleadj\",\"Ausdoubleadj\",\"Ausdoubleadj\",\"Ausdoubleadj\",\"Ausdoubleadj\",\"Ausdoubleadj\",\"Ausdoubleadj\"]}},\"value\":[{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"normalem\"]},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\",\"extra_lines\"]},\"class\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"latex_dependency\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"NULL\"},{\"type\":\"NULL\"}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"table\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"babel\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"greek\",\"english\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"table\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"babel\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"greek\",\"english\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"table\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"babel\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"greek\",\"english\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"table\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"babel\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"greek\",\"english\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"table\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"babel\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"greek\",\"english\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"table\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"babel\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"greek\",\"english\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"booktabs\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"longtable\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"array\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"multirow\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"xcolor\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"table\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"wrapfig\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"float\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"colortbl\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"pdflscape\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"tabu\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttable\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"threeparttablex\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"ulem\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"makecell\"]}]},{\"type\":\"list\",\"attributes\":{\"names\":{\"type\":\"character\",\"attributes\":{},\"value\":[\"name\",\"options\"]}},\"value\":[{\"type\":\"character\",\"attributes\":{},\"value\":[\"babel\"]},{\"type\":\"character\",\"attributes\":{},\"value\":[\"greek\",\"english\"]}]}]}"
      ]
    },
    "preserve": null,
    "postProcess": false
  }
}