{
  "hash": "f31405abc30b46220d88a2ae4754ad74",
  "result": {
    "markdown": "## Replicate Results {.unnumbered}\n\nThe tutorial aims to guide the users through fitting machine learning techniques with health survey data. We will replicate some of the results of this article by [Falasinnu et al. (2023)](https://doi.org/10.1016/j.jpain.2023.03.008).\n\n::: column-margin\nFalasinnu T, Hossain MB, Weber II KA, Helmick CG, Karim ME, Mackey S. The Problem of Pain in the United States: A Population-Based Characterization of Biopsychosocial Correlates of High Impact Chronic Pain Using the National Health Interview Survey. The Journal of Pain. 2023;24(6):1094-103. DOI: [10.1016/j.jpain.2023.03.008](https://doi.org/10.1016/j.jpain.2023.03.008)\n:::\n\nThe authors used the [National Health Interview Survey (NHIS) 2016](https://www.cdc.gov/nchs/nhis/nhis_2016_data_release.htm) dataset to develop prediction models for predicting high impact chronic pain (HICP). They also evaluated the predictive performances of the models within sociodemographic subgroups, such as sex (male, female), age ($<65$, $\\ge 65$), and race/ethnicity (White, Black, Hispanic). They used LASSO and random forest models with 5-fold cross-validation as an internal validation. To obtain population-level predictions, they account for survey weights in both models.\n\n::: column-margin\nFor those interested in the National Health Interview Survey (NHIS) dataset, can review the [earlier tutorial](accessing5.html) about the dataset.\n:::\n\n::: callout-note\nTo handle [missing data](missingdata.html) in the predictors, they used multiple imputation technique. However, for simplicity, this tutorial focuses on a complete case dataset. We will also only focus on predicting HICP for people aged 65 years or older (a dataset of \\~8,800 participants compared to the dataset of 33,000 participants aged 18 years or older).\n:::\n\n### Load packages\n\nWe load several R packages required for fitting LASSO and random forest models.\n\n\n::: {.cell hash='machinelearning6b_cache/html/setup_8c922ed69a10fa6e5f17dc78fb81e2c7'}\n\n```{.r .cell-code}\n# Load required packages\nlibrary(tableone)\nlibrary(gtsummary)\nlibrary(glmnet)\nlibrary(WeightedROC)\nlibrary(ranger)\nlibrary(scoring)\nlibrary(DescTools)\nlibrary(ggplot2)\nlibrary(mlr3misc)\n```\n:::\n\n\n### Analytic dataset\n\n#### Load\n\nWe load the dataset into the R environment and lists all available variables and objects.\n\n\n::: {.cell hash='machinelearning6b_cache/html/load_948ca4205b34465b8b10f5337523ac67'}\n\n```{.r .cell-code}\nload(\"Data/machinelearning/Falasinnu2023.RData\")\nls()\n#> [1] \"dat\"\n```\n:::\n\n::: {.cell hash='machinelearning6b_cache/html/dim_c6aaf885d23ba9d8341b4dea2b52c23c'}\n\n```{.r .cell-code}\ndim(dat)\n#> [1] 8881   49\n```\n:::\n\n\nThe dataset contains 8,881 participants aged 65 years or older with 49 variables:\n\n-   `studyid`: Unique identifier\n-   `psu`: Pseudo-PSU\n-   `strata`: Pseudo-stratum\n-   `weight`: Sampling weight\n-   `HICP`: HICP (binary outcome variable)\n-   `age`: Age\n-   `sex`: Sex\n-   `hhsize`: Number of people in household\n-   `born`: Citizenship\n-   `marital`: Marital status\n-   `region`: Region\n-   `race`: Race/ethnicity\n-   `education`: Education\n-   `employment.status`: Employment status\n-   `poverty.status`: Poverty status\n-   `veteran`: Veteran\n-   `insurance`: Health insurance coverage\n-   `sex.orientation`: Sexual orientation\n-   `worried.money`: Worried about money\n-   `good.neighborhood`: Good neighborhood\n-   `psy.symptom`: Psychological symptoms\n-   `visit.ED`: Number of times in ER/ED\n-   `surgery`: Number of surgeries in past 12 months\n-   `dr.visit`: Time since doctor visits\n-   `cancer`: Cancer\n-   `asthma`: Asthma\n-   `htn`: Hypertension\n-   `liver.disease`: Liver disease\n-   `diabetes`: Diabetes\n-   `ulcer`: Ulcer\n-   `stroke`: Stroke\n-   `emphysema`: Emphysema\n-   `copd`: COPD\n-   `high.cholesterol`: High cholesterol\n-   `coronary.heart.disease`: Coronary heart disease\n-   `angina`: Angina pectoris\n-   `heart.attack`: Heart attack\n-   `heart.disease`: Heart condition/disease\n-   `arthritis`: Arthritis and rheumatism\n-   `crohns.disease`: Crohn's disease\n-   `place.routine.care`: Usual place for routine care\n-   `trouble.asleep`: Trouble falling asleep\n-   `obese`: Obesity\n-   `current.smoker`: Current smoker\n-   `heavy.drinker`: Heavy drinker\n-   `hospitalization`: Hospital stay days\n-   `better.health.status`: Better health status\n-   `physical.activity`: Physical activity\n\nSee the NHIS 2016 dataset and the article for better understanding of the variables.\n\n#### Complete case data\n\n\n::: {.cell hash='machinelearning6b_cache/html/desc_79d37c03529591b516810b8b45d0e1bf'}\n\n```{.r .cell-code}\n# Age\ntable(dat$age, useNA = \"always\")\n#> \n#>  <65  65+ <NA> \n#>    0 8881    0\n```\n:::\n\n\nLet us consider a complete case dataset\n\n\n::: {.cell hash='machinelearning6b_cache/html/completecase_fd9cb2bbb6d2c2938c5284b27da3d5f7'}\n\n```{.r .cell-code}\ndat.complete <- na.omit(dat)\ndim(dat.complete)\n#> [1] 7280   49\n```\n:::\n\n\nAs we can see, there are 7,280 participants with complete case information. Let's see the descriptive statistics of the predictors stratified by HICP.\n\n#### Descriptive statistics\n\n\n::: {.cell hash='machinelearning6b_cache/html/tab1_edcbe8334c5d35682f4fe14cc0834017'}\n\n```{.r .cell-code}\n# Predictors\npredictors <- c(\"sex\", \"hhsize\", \"born\", \"marital\", \n                \"region\", \"race\", \"education\", \n                \"employment.status\", \"poverty.status\",\n                \"veteran\", \"insurance\", \n                \"sex.orientation\", \"worried.money\", \n                \"good.neighborhood\", \n                \"psy.symptom\", \"visit.ED\", \"surgery\", \n                \"dr.visit\", \"cancer\", \n                \"asthma\", \"htn\", \"liver.disease\", \n                \"diabetes\", \"ulcer\", \"stroke\",\n                \"emphysema\", \"copd\", \"high.cholesterol\",\n                \"coronary.heart.disease\", \n                \"angina\", \"heart.attack\", \n                \"heart.disease\", \"arthritis\", \n                \"crohns.disease\", \"place.routine.care\", \n                \"trouble.asleep\", \"obese\", \n                \"current.smoker\", \"heavy.drinker\",\n                \"hospitalization\", \n                \"better.health.status\", \n                \"physical.activity\")\n\n# Table 1 - Unweighted \ntbl_summary(data = dat.complete, \n            include = predictors, \n            by = HICP, missing = \"no\") %>% \n  modify_spanning_header(c(\"stat_1\", \n                           \"stat_2\") ~ \"**HICP**\")\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"ljmcchytei\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#ljmcchytei table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#ljmcchytei thead, #ljmcchytei tbody, #ljmcchytei tfoot, #ljmcchytei tr, #ljmcchytei td, #ljmcchytei th {\n  border-style: none;\n}\n\n#ljmcchytei p {\n  margin: 0;\n  padding: 0;\n}\n\n#ljmcchytei .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#ljmcchytei .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#ljmcchytei .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#ljmcchytei .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#ljmcchytei .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ljmcchytei .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ljmcchytei .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#ljmcchytei .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#ljmcchytei .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#ljmcchytei .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#ljmcchytei .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#ljmcchytei .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#ljmcchytei .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#ljmcchytei .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#ljmcchytei .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#ljmcchytei .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#ljmcchytei .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#ljmcchytei .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#ljmcchytei .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ljmcchytei .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#ljmcchytei .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#ljmcchytei .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#ljmcchytei .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ljmcchytei .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#ljmcchytei .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#ljmcchytei .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ljmcchytei .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ljmcchytei .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#ljmcchytei .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ljmcchytei .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#ljmcchytei .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#ljmcchytei .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ljmcchytei .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ljmcchytei .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#ljmcchytei .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#ljmcchytei .gt_left {\n  text-align: left;\n}\n\n#ljmcchytei .gt_center {\n  text-align: center;\n}\n\n#ljmcchytei .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#ljmcchytei .gt_font_normal {\n  font-weight: normal;\n}\n\n#ljmcchytei .gt_font_bold {\n  font-weight: bold;\n}\n\n#ljmcchytei .gt_font_italic {\n  font-style: italic;\n}\n\n#ljmcchytei .gt_super {\n  font-size: 65%;\n}\n\n#ljmcchytei .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#ljmcchytei .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#ljmcchytei .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#ljmcchytei .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#ljmcchytei .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#ljmcchytei .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#ljmcchytei .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings gt_spanner_row\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"2\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;Characteristic&lt;/strong&gt;\"><strong>Characteristic</strong></th>\n      <th class=\"gt_center gt_columns_top_border gt_column_spanner_outer\" rowspan=\"1\" colspan=\"2\" scope=\"colgroup\" id=\"&lt;strong&gt;HICP&lt;/strong&gt;\">\n        <span class=\"gt_column_spanner\"><strong>HICP</strong></span>\n      </th>\n    </tr>\n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;0&lt;/strong&gt;, N = 6,389&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>0</strong>, N = 6,389<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"&lt;strong&gt;1&lt;/strong&gt;, N = 891&lt;span class=&quot;gt_footnote_marks&quot; style=&quot;white-space:nowrap;font-style:italic;font-weight:normal;&quot;&gt;&lt;sup&gt;1&lt;/sup&gt;&lt;/span&gt;\"><strong>1</strong>, N = 891<span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span></th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">sex</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Female</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">3,587 (56%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">569 (64%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Male</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2,802 (44%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">322 (36%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">hhsize</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2 (1, 2)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">2 (1, 2)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">born</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Born in US</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">5,775 (90%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">802 (90%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Other place</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">614 (9.6%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">89 (10.0%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">marital</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Never married</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">411 (6.4%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">57 (6.4%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Married/with partner</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2,990 (47%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">349 (39%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Divorced/separated</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,161 (18%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">179 (20%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Widowed</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,827 (29%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">306 (34%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">region</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Northeast</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,172 (18%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">143 (16%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Midwest</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,451 (23%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">189 (21%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    South</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2,203 (34%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">331 (37%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    West</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,563 (24%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">228 (26%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">race</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    White</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">5,090 (80%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">694 (78%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Black</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">564 (8.8%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">88 (9.9%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Hispanic</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">406 (6.4%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">70 (7.9%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Others</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">329 (5.1%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">39 (4.4%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">education</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Less than high school</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">954 (15%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">220 (25%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    High school/GED</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,863 (29%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">269 (30%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Some college</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,716 (27%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">248 (28%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Bachelors degree or higher</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,856 (29%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">154 (17%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">employment.status</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Employed hourly</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">578 (9.0%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">22 (2.5%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Employed non-hourly</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">608 (9.5%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">27 (3.0%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Worked previously</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">4,923 (77%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">777 (87%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Never worked</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">280 (4.4%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">65 (7.3%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">poverty.status</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    &lt;100% FPL</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">496 (7.8%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">154 (17%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    100-200% FPL</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,401 (22%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">276 (31%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    200-400% FPL</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2,157 (34%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">283 (32%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    400%+ FPL</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2,335 (37%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">178 (20%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">veteran</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,482 (23%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">163 (18%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">insurance</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Uninsured</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">32 (0.5%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">6 (0.7%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Medicaid/Medicare</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2,995 (47%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">478 (54%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Privately Insured</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2,847 (45%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">311 (35%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Other</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">515 (8.1%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">96 (11%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">sex.orientation</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Heterosexual</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">6,224 (97%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">861 (97%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Other</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">165 (2.6%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">30 (3.4%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">worried.money</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">2,351 (37%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">491 (55%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">good.neighborhood</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">5,988 (94%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">781 (88%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">psy.symptom</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">694 (11%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">353 (40%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">visit.ED</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    None</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">5,050 (79%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">531 (60%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    One</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">949 (15%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">187 (21%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    2-3</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">313 (4.9%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">123 (14%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    4+</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">77 (1.2%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">50 (5.6%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">surgery</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    None</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">5,218 (82%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">650 (73%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    One</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">898 (14%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">176 (20%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Two</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">206 (3.2%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">44 (4.9%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    3+</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">67 (1.0%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">21 (2.4%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">dr.visit</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    &lt;6 months</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">5,390 (84%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">837 (94%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    6-12 months</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">591 (9.3%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">41 (4.6%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1-5 years</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">281 (4.4%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">10 (1.1%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    &gt;5 years/never</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">127 (2.0%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">3 (0.3%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">cancer</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,566 (25%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">271 (30%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">asthma</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">645 (10%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">176 (20%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">htn</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">3,953 (62%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">689 (77%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">liver.disease</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">122 (1.9%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">50 (5.6%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">diabetes</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,179 (18%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">278 (31%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">ulcer</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">545 (8.5%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">161 (18%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">stroke</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">485 (7.6%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">130 (15%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">emphysema</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">235 (3.7%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">76 (8.5%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">copd</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">496 (7.8%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">145 (16%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">high.cholesterol</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">3,373 (53%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">577 (65%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">coronary.heart.disease</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">814 (13%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">211 (24%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">angina</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">298 (4.7%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">100 (11%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">heart.attack</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">552 (8.6%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">154 (17%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">heart.disease</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,083 (17%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">210 (24%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">arthritis</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">3,017 (47%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">700 (79%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">crohns.disease</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">102 (1.6%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">29 (3.3%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">place.routine.care</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    No place</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">235 (3.7%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">26 (2.9%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Doctor's office</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">4,634 (73%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">621 (70%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Hospital/Clinic</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,403 (22%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">221 (25%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Other place</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">117 (1.8%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">23 (2.6%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">trouble.asleep</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,970 (31%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">424 (48%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">obese</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,757 (28%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">397 (45%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">current.smoker</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">565 (8.8%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">111 (12%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">heavy.drinker</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">308 (4.8%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">25 (2.8%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">hospitalization</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    None</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">5,009 (78%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">503 (56%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    1-2 days</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">592 (9.3%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">57 (6.4%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    3-5 days</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">360 (5.6%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">63 (7.1%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    6+ days</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">428 (6.7%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">268 (30%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">better.health.status</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">890 (14%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">119 (13%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">physical.activity</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\"><br /></td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\"><br /></td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Less</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">3,734 (58%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">743 (83%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    Moderate</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">1,794 (28%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">108 (12%)</td></tr>\n    <tr><td headers=\"label\" class=\"gt_row gt_left\">    High</td>\n<td headers=\"stat_1\" class=\"gt_row gt_center\">861 (13%)</td>\n<td headers=\"stat_2\" class=\"gt_row gt_center\">40 (4.5%)</td></tr>\n  </tbody>\n  \n  <tfoot class=\"gt_footnotes\">\n    <tr>\n      <td class=\"gt_footnote\" colspan=\"3\"><span class=\"gt_footnote_marks\" style=\"white-space:nowrap;font-style:italic;font-weight:normal;\"><sup>1</sup></span> n (%); Median (IQR)</td>\n    </tr>\n  </tfoot>\n</table>\n</div>\n```\n:::\n:::\n\n\n### LASSO for surveys\n\nNow, we will fit the LASSO model for predicting binary HICP with the listed predictors. Similar to the [previous chapter](machinelearning6a.html), we will normalize the weight.\n\n#### Weight normalization\n\n\n::: {.cell hash='machinelearning6b_cache/html/weight_99472cb95680de46313c6f53394684e0'}\n\n```{.r .cell-code}\n# Normalize weight\ndat.complete$wgt <- dat.complete$weight * \n  nrow(dat.complete)/sum(dat.complete$weight)\n\n# Weight summary\nsummary(dat.complete$weight)\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>     243    1503    2583    2886    3747   14662\nsummary(dat.complete$wgt)\n#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n#>  0.0842  0.5208  0.8950  1.0000  1.2983  5.0804\n\n# The weighted and unweighted n are equal\nnrow(dat.complete)\n#> [1] 7280\nsum(dat.complete$wgt)\n#> [1] 7280\n```\n:::\n\n\n#### Folds\n\nLet's create five random folds and specify the regression formula.\n\n\n::: {.cell hash='machinelearning6b_cache/html/folds_1ea30dcf9ccd6878e1e849d0f594ae52'}\n\n```{.r .cell-code}\nk <- 5\nset.seed(604)\nnfolds <- sample(1:k, \n                 size = nrow(dat.complete), \n                 replace = T)\ntable(nfolds)\n#> nfolds\n#>    1    2    3    4    5 \n#> 1451 1457 1496 1468 1408\n```\n:::\n\n\n#### Formula\n\n\n::: {.cell hash='machinelearning6b_cache/html/formula_5b2e41f715a6814d3f740df039bf8ff5'}\n\n```{.r .cell-code}\nFormula <- formula(paste(\"HICP ~ \", paste(predictors, \n                                          collapse=\" + \")))\nFormula\n#> HICP ~ sex + hhsize + born + marital + region + race + education + \n#>     employment.status + poverty.status + veteran + insurance + \n#>     sex.orientation + worried.money + good.neighborhood + psy.symptom + \n#>     visit.ED + surgery + dr.visit + cancer + asthma + htn + liver.disease + \n#>     diabetes + ulcer + stroke + emphysema + copd + high.cholesterol + \n#>     coronary.heart.disease + angina + heart.attack + heart.disease + \n#>     arthritis + crohns.disease + place.routine.care + trouble.asleep + \n#>     obese + current.smoker + heavy.drinker + hospitalization + \n#>     better.health.status + physical.activity\n```\n:::\n\n\n#### 5-fold CV LASSO\n\nNow, we will fit the LASSO model with 5-fold cross-validation (CV). Here are the steps:\n\n-   For fold 1, folds 2-5 is the training set and fold 1 is the test set\n-   Fit 5-fold cross-validation on the training set to find the value of lambda that gives minimum prediction error. Incorporate sampling weights in the model to account for survey design.\n-   Fit LASSO on the training with the optimum lambda from the previous step. Incorporate sampling weights in the model to account for survey design.\n-   Calculate predictive performance (e.g., AUC) on the test set\n-   Repeat the analysis for all folds.\n\n\n::: {.cell hash='machinelearning6b_cache/html/lassofit_a3101fce5f163ef11ad713a43b718562'}\n\n```{.r .cell-code}\nfit.lasso <- list(NULL)\nauc.lasso <- NULL\ncal.slope.lasso <- NULL\nbrier.lasso <- NULL\nfor (fold in 1:k) {\n  # Training data\n  dat.train <- dat.complete[nfolds != fold, ]\n  X.train <- model.matrix(Formula, dat.train)[,-1]\n  y.train <- as.matrix(dat.train$HICP)\n  \n  # Test data\n  dat.test <- dat.complete[nfolds == fold, ]\n  X.test <- model.matrix(Formula, dat.test)[,-1]\n  y.test <- as.matrix(dat.test$HICP)\n  \n  # Find the optimum lambda using 5-fold CV\n  fit.cv.lasso <- cv.glmnet(x = X.train, \n                            y = y.train, \n                            nfolds = 5, \n                            alpha = 1, \n                            family = \"binomial\", \n                            weights = dat.train$wgt)\n  \n  # Fit the model on the training set with optimum lambda\n  fit.lasso[[fold]] <- glmnet(\n    x = X.train, \n    y = y.train, \n    alpha = 1, \n    family = \"binomial\",\n    lambda = fit.cv.lasso$lambda.min,\n    weights = dat.train$wgt)\n  \n  # Prediction on the test set\n  dat.test$pred.lasso <- predict(fit.lasso[[fold]], \n                                 newx = X.test, \n                                 type = \"response\")\n  \n  # AUC on the test set with sampling weights\n  auc.lasso[fold] <- WeightedAUC(\n    WeightedROC(dat.test$pred.lasso,\n                dat.test$HICP, \n                weight = dat.test$wgt))\n  \n  # Weighted calibration slope\n  mod.cal <- glm(\n    HICP ~ Logit(dat.test$pred.lasso), \n    data = dat.test, \n    family = binomial, \n    weights = wgt)\n  cal.slope.lasso[fold] <- summary(mod.cal)$coef[2,1]\n  \n  # Weighted Brier Score\n  brier.lasso[fold] <- mean(\n    brierscore(HICP ~ dat.test$pred.lasso,\n               data = dat.test, \n               wt = dat.test$wgt))\n}\n```\n:::\n\n\n#### Model performance\n\nLet's check how prediction worked.\n\n\n::: {.cell hash='machinelearning6b_cache/html/lassofit2_8bb121e4e88089befb2331a1eed63ba0'}\n\n```{.r .cell-code}\n# Fitted LASSO models\nfit.lasso[[1]]\n#> \n#> Call:  glmnet(x = X.train, y = y.train, family = \"binomial\", weights = dat.train$wgt,      alpha = 1, lambda = fit.cv.lasso$lambda.min) \n#> \n#>   Df  %Dev   Lambda\n#> 1 46 23.91 0.002972\nfit.lasso[[2]]\n#> \n#> Call:  glmnet(x = X.train, y = y.train, family = \"binomial\", weights = dat.train$wgt,      alpha = 1, lambda = fit.cv.lasso$lambda.min) \n#> \n#>   Df  %Dev   Lambda\n#> 1 47 25.32 0.002559\nfit.lasso[[3]]\n#> \n#> Call:  glmnet(x = X.train, y = y.train, family = \"binomial\", weights = dat.train$wgt,      alpha = 1, lambda = fit.cv.lasso$lambda.min) \n#> \n#>   Df %Dev   Lambda\n#> 1 47 24.3 0.002724\nfit.lasso[[4]]\n#> \n#> Call:  glmnet(x = X.train, y = y.train, family = \"binomial\", weights = dat.train$wgt,      alpha = 1, lambda = fit.cv.lasso$lambda.min) \n#> \n#>   Df  %Dev   Lambda\n#> 1 34 25.27 0.004726\nfit.lasso[[5]]\n#> \n#> Call:  glmnet(x = X.train, y = y.train, family = \"binomial\", weights = dat.train$wgt,      alpha = 1, lambda = fit.cv.lasso$lambda.min) \n#> \n#>   Df  %Dev   Lambda\n#> 1 39 24.32 0.003525\n```\n:::\n\n::: {.cell hash='machinelearning6b_cache/html/lassofit3_17fa4aa113f7a227de228687891a71a3'}\n\n```{.r .cell-code}\n# Intercept from the LASSO models in different folds\nfit.lasso[[1]]$a0\n#>        s0 \n#> -3.733405\nfit.lasso[[2]]$a0\n#>        s0 \n#> -3.534898\nfit.lasso[[3]]$a0\n#>        s0 \n#> -3.486223\nfit.lasso[[4]]$a0\n#>        s0 \n#> -3.800206\nfit.lasso[[5]]$a0\n#>       s0 \n#> -3.68776\n```\n:::\n\n::: {.cell hash='machinelearning6b_cache/html/lassofit4_4089cdae7c32c32d3019f768896b5424'}\n\n```{.r .cell-code}\n# Beta coefficients from the LASSO models in different folds\nfit.lasso[[1]]$beta\n#> 67 x 1 sparse Matrix of class \"dgCMatrix\"\n#>                                                 s0\n#> sexMale                               .           \n#> hhsize                                0.0092060605\n#> bornOther place                       .           \n#> maritalMarried/with partner           .           \n#> maritalDivorced/separated             .           \n#> maritalWidowed                        0.0926365970\n#> regionMidwest                         .           \n#> regionSouth                           .           \n#> regionWest                            0.1470219542\n#> raceBlack                            -0.0436983700\n#> raceHispanic                          .           \n#> raceOthers                            .           \n#> educationHigh school/GED              .           \n#> educationSome college                 .           \n#> educationBachelors degree or higher   .           \n#> employment.statusEmployed non-hourly  .           \n#> employment.statusWorked previously    0.5412332930\n#> employment.statusNever worked         0.8300536966\n#> poverty.status100-200% FPL            0.0636289868\n#> poverty.status200-400% FPL           -0.0697612513\n#> poverty.status400%+ FPL              -0.2887583235\n#> veteranYes                           -0.0300714331\n#> insuranceMedicaid/Medicare            .           \n#> insurancePrivately Insured           -0.0924641963\n#> insuranceOther                        0.1503323815\n#> sex.orientationOther                  0.0765093892\n#> worried.moneyYes                      0.2812674935\n#> good.neighborhoodYes                 -0.2491796538\n#> psy.symptomYes                        0.9726200151\n#> visit.EDOne                           0.0674459188\n#> visit.ED2-3                           0.1375781535\n#> visit.ED4+                            0.4225671575\n#> surgeryOne                            .           \n#> surgeryTwo                            .           \n#> surgery3+                            -0.0839622285\n#> dr.visit6-12 months                  -0.2120063637\n#> dr.visit1-5 years                    -0.4068474570\n#> dr.visit>5 years/never               -0.1453128227\n#> cancerYes                             0.0993613856\n#> asthmaYes                             0.2997325771\n#> htnYes                                0.2082877598\n#> liver.diseaseYes                      0.8058966864\n#> diabetesYes                           0.0007357323\n#> ulcerYes                              0.4180133887\n#> strokeYes                             .           \n#> emphysemaYes                         -0.0509549802\n#> copdYes                               0.1002374105\n#> high.cholesterolYes                   0.1021030868\n#> coronary.heart.diseaseYes             0.0220558291\n#> anginaYes                             0.0849595261\n#> heart.attackYes                       0.2476656673\n#> heart.diseaseYes                      .           \n#> arthritisYes                          0.9746692568\n#> crohns.diseaseYes                     .           \n#> place.routine.careDoctor's office    -0.0583977619\n#> place.routine.careHospital/Clinic     .           \n#> place.routine.careOther place         .           \n#> trouble.asleepYes                     0.2030296869\n#> obeseYes                              0.3879895531\n#> current.smokerYes                     0.3374178965\n#> heavy.drinkerYes                     -0.1268971235\n#> hospitalization1-2 days               0.1192556336\n#> hospitalization3-5 days               .           \n#> hospitalization6+ days                1.0866087297\n#> better.health.statusYes              -0.1013785074\n#> physical.activityModerate            -0.7523741651\n#> physical.activityHigh                -0.6865233686\nfit.lasso[[2]]$beta\n#> 67 x 1 sparse Matrix of class \"dgCMatrix\"\n#>                                                s0\n#> sexMale                               .          \n#> hhsize                                0.018493189\n#> bornOther place                       .          \n#> maritalMarried/with partner           .          \n#> maritalDivorced/separated            -0.001903136\n#> maritalWidowed                        .          \n#> regionMidwest                        -0.077656662\n#> regionSouth                           0.066061919\n#> regionWest                            0.198988965\n#> raceBlack                            -0.313705357\n#> raceHispanic                         -0.160881871\n#> raceOthers                            .          \n#> educationHigh school/GED             -0.073948767\n#> educationSome college                 .          \n#> educationBachelors degree or higher  -0.092601336\n#> employment.statusEmployed non-hourly  .          \n#> employment.statusWorked previously    0.662301617\n#> employment.statusNever worked         0.990458783\n#> poverty.status100-200% FPL            .          \n#> poverty.status200-400% FPL           -0.253983648\n#> poverty.status400%+ FPL              -0.485846823\n#> veteranYes                           -0.095649252\n#> insuranceMedicaid/Medicare            .          \n#> insurancePrivately Insured           -0.005530756\n#> insuranceOther                        0.249278523\n#> sex.orientationOther                  .          \n#> worried.moneyYes                      0.301627606\n#> good.neighborhoodYes                 -0.554793692\n#> psy.symptomYes                        0.975043141\n#> visit.EDOne                           0.058872693\n#> visit.ED2-3                           0.255785667\n#> visit.ED4+                            0.422172434\n#> surgeryOne                            0.002831717\n#> surgeryTwo                            0.099101540\n#> surgery3+                             .          \n#> dr.visit6-12 months                  -0.105087667\n#> dr.visit1-5 years                    -0.381233762\n#> dr.visit>5 years/never               -0.459656177\n#> cancerYes                             0.281041121\n#> asthmaYes                             0.427654297\n#> htnYes                                0.219625784\n#> liver.diseaseYes                      0.580991873\n#> diabetesYes                           .          \n#> ulcerYes                              0.348542693\n#> strokeYes                             0.070369016\n#> emphysemaYes                          .          \n#> copdYes                               .          \n#> high.cholesterolYes                   0.150862244\n#> coronary.heart.diseaseYes             0.009536678\n#> anginaYes                             .          \n#> heart.attackYes                       0.405053759\n#> heart.diseaseYes                      .          \n#> arthritisYes                          0.954063592\n#> crohns.diseaseYes                     .          \n#> place.routine.careDoctor's office    -0.045764606\n#> place.routine.careHospital/Clinic     .          \n#> place.routine.careOther place         0.207253975\n#> trouble.asleepYes                     0.212898902\n#> obeseYes                              0.389340100\n#> current.smokerYes                     0.332982403\n#> heavy.drinkerYes                     -0.135194457\n#> hospitalization1-2 days               .          \n#> hospitalization3-5 days               .          \n#> hospitalization6+ days                1.018420971\n#> better.health.statusYes              -0.001173805\n#> physical.activityModerate            -0.703703292\n#> physical.activityHigh                -0.677811398\nfit.lasso[[3]]$beta\n#> 67 x 1 sparse Matrix of class \"dgCMatrix\"\n#>                                               s0\n#> sexMale                              -0.03555390\n#> hhsize                                0.01276707\n#> bornOther place                       .         \n#> maritalMarried/with partner          -0.00226132\n#> maritalDivorced/separated             .         \n#> maritalWidowed                        .         \n#> regionMidwest                         .         \n#> regionSouth                           .         \n#> regionWest                            0.25300309\n#> raceBlack                            -0.21629021\n#> raceHispanic                          .         \n#> raceOthers                            0.07458935\n#> educationHigh school/GED             -0.07527970\n#> educationSome college                 .         \n#> educationBachelors degree or higher  -0.08524865\n#> employment.statusEmployed non-hourly  .         \n#> employment.statusWorked previously    0.66693373\n#> employment.statusNever worked         0.96274685\n#> poverty.status100-200% FPL            .         \n#> poverty.status200-400% FPL           -0.11543598\n#> poverty.status400%+ FPL              -0.31422327\n#> veteranYes                           -0.08849244\n#> insuranceMedicaid/Medicare            .         \n#> insurancePrivately Insured           -0.14856615\n#> insuranceOther                        0.14368311\n#> sex.orientationOther                  .         \n#> worried.moneyYes                      0.28107756\n#> good.neighborhoodYes                 -0.37214169\n#> psy.symptomYes                        1.02129791\n#> visit.EDOne                           0.11427725\n#> visit.ED2-3                           0.23654896\n#> visit.ED4+                            0.53011900\n#> surgeryOne                            0.06030144\n#> surgeryTwo                            .         \n#> surgery3+                            -0.28355643\n#> dr.visit6-12 months                  -0.04219568\n#> dr.visit1-5 years                    -0.83131719\n#> dr.visit>5 years/never               -0.48832578\n#> cancerYes                             0.18366379\n#> asthmaYes                             0.13556093\n#> htnYes                                0.12622357\n#> liver.diseaseYes                      0.62123990\n#> diabetesYes                           .         \n#> ulcerYes                              0.39650846\n#> strokeYes                             .         \n#> emphysemaYes                          .         \n#> copdYes                               0.16563326\n#> high.cholesterolYes                   0.10541633\n#> coronary.heart.diseaseYes             0.08229669\n#> anginaYes                             .         \n#> heart.attackYes                       0.37154172\n#> heart.diseaseYes                      .         \n#> arthritisYes                          0.91902311\n#> crohns.diseaseYes                    -0.01478240\n#> place.routine.careDoctor's office    -0.04968533\n#> place.routine.careHospital/Clinic     .         \n#> place.routine.careOther place         0.20094580\n#> trouble.asleepYes                     0.07725267\n#> obeseYes                              0.40542559\n#> current.smokerYes                     0.27207489\n#> heavy.drinkerYes                     -0.06932537\n#> hospitalization1-2 days              -0.13525647\n#> hospitalization3-5 days               .         \n#> hospitalization6+ days                1.02580763\n#> better.health.statusYes               .         \n#> physical.activityModerate            -0.74686507\n#> physical.activityHigh                -0.90554222\nfit.lasso[[4]]$beta\n#> 67 x 1 sparse Matrix of class \"dgCMatrix\"\n#>                                                s0\n#> sexMale                               .          \n#> hhsize                                .          \n#> bornOther place                       .          \n#> maritalMarried/with partner           .          \n#> maritalDivorced/separated             .          \n#> maritalWidowed                        .          \n#> regionMidwest                         .          \n#> regionSouth                           .          \n#> regionWest                            0.151732262\n#> raceBlack                            -0.063747960\n#> raceHispanic                          .          \n#> raceOthers                            .          \n#> educationHigh school/GED              .          \n#> educationSome college                 .          \n#> educationBachelors degree or higher   .          \n#> employment.statusEmployed non-hourly  .          \n#> employment.statusWorked previously    0.521879242\n#> employment.statusNever worked         0.671265401\n#> poverty.status100-200% FPL            .          \n#> poverty.status200-400% FPL           -0.014851029\n#> poverty.status400%+ FPL              -0.229122884\n#> veteranYes                            .          \n#> insuranceMedicaid/Medicare            .          \n#> insurancePrivately Insured           -0.092128877\n#> insuranceOther                        .          \n#> sex.orientationOther                  0.150490732\n#> worried.moneyYes                      0.282333603\n#> good.neighborhoodYes                 -0.104236603\n#> psy.symptomYes                        1.132555465\n#> visit.EDOne                           0.009230339\n#> visit.ED2-3                           0.288663967\n#> visit.ED4+                            0.673934923\n#> surgeryOne                            .          \n#> surgeryTwo                            .          \n#> surgery3+                             .          \n#> dr.visit6-12 months                  -0.018831608\n#> dr.visit1-5 years                    -0.496368171\n#> dr.visit>5 years/never               -0.415165313\n#> cancerYes                             .          \n#> asthmaYes                             0.240957776\n#> htnYes                                0.125845727\n#> liver.diseaseYes                      0.672282863\n#> diabetesYes                           .          \n#> ulcerYes                              0.352645788\n#> strokeYes                             .          \n#> emphysemaYes                          .          \n#> copdYes                               0.054275559\n#> high.cholesterolYes                   0.057735457\n#> coronary.heart.diseaseYes             0.070550439\n#> anginaYes                             .          \n#> heart.attackYes                       0.234807175\n#> heart.diseaseYes                      .          \n#> arthritisYes                          1.043934915\n#> crohns.diseaseYes                     0.086038829\n#> place.routine.careDoctor's office     .          \n#> place.routine.careHospital/Clinic     .          \n#> place.routine.careOther place         .          \n#> trouble.asleepYes                     0.177916442\n#> obeseYes                              0.363088024\n#> current.smokerYes                     0.339985811\n#> heavy.drinkerYes                      .          \n#> hospitalization1-2 days               .          \n#> hospitalization3-5 days               0.073321609\n#> hospitalization6+ days                1.066617646\n#> better.health.statusYes               .          \n#> physical.activityModerate            -0.699175264\n#> physical.activityHigh                -0.642594150\nfit.lasso[[5]]$beta\n#> 67 x 1 sparse Matrix of class \"dgCMatrix\"\n#>                                               s0\n#> sexMale                               .         \n#> hhsize                                0.01585559\n#> bornOther place                       .         \n#> maritalMarried/with partner           .         \n#> maritalDivorced/separated            -0.04982466\n#> maritalWidowed                        0.03837620\n#> regionMidwest                        -0.25040909\n#> regionSouth                           .         \n#> regionWest                            0.08288425\n#> raceBlack                            -0.07020324\n#> raceHispanic                          .         \n#> raceOthers                            .         \n#> educationHigh school/GED              .         \n#> educationSome college                 .         \n#> educationBachelors degree or higher   .         \n#> employment.statusEmployed non-hourly  .         \n#> employment.statusWorked previously    0.64497666\n#> employment.statusNever worked         0.83560645\n#> poverty.status100-200% FPL            .         \n#> poverty.status200-400% FPL           -0.03113577\n#> poverty.status400%+ FPL              -0.22313059\n#> veteranYes                           -0.20269803\n#> insuranceMedicaid/Medicare            .         \n#> insurancePrivately Insured           -0.14170986\n#> insuranceOther                        0.19604683\n#> sex.orientationOther                  .         \n#> worried.moneyYes                      0.31572735\n#> good.neighborhoodYes                 -0.31850186\n#> psy.symptomYes                        1.15194136\n#> visit.EDOne                           0.05961452\n#> visit.ED2-3                           0.34349175\n#> visit.ED4+                            0.25637410\n#> surgeryOne                            .         \n#> surgeryTwo                            .         \n#> surgery3+                             .         \n#> dr.visit6-12 months                   .         \n#> dr.visit1-5 years                    -0.32790023\n#> dr.visit>5 years/never                .         \n#> cancerYes                             0.21372688\n#> asthmaYes                             0.21206722\n#> htnYes                                0.13025900\n#> liver.diseaseYes                      0.44892643\n#> diabetesYes                           0.05119678\n#> ulcerYes                              0.27325347\n#> strokeYes                             .         \n#> emphysemaYes                          .         \n#> copdYes                               0.04954730\n#> high.cholesterolYes                   0.14824572\n#> coronary.heart.diseaseYes             .         \n#> anginaYes                             .         \n#> heart.attackYes                       0.27924438\n#> heart.diseaseYes                      .         \n#> arthritisYes                          1.00382986\n#> crohns.diseaseYes                     .         \n#> place.routine.careDoctor's office    -0.01943640\n#> place.routine.careHospital/Clinic     .         \n#> place.routine.careOther place         0.07273335\n#> trouble.asleepYes                     0.14684831\n#> obeseYes                              0.38029871\n#> current.smokerYes                     0.14111139\n#> heavy.drinkerYes                      .         \n#> hospitalization1-2 days              -0.02310396\n#> hospitalization3-5 days               .         \n#> hospitalization6+ days                1.08731840\n#> better.health.statusYes               .         \n#> physical.activityModerate            -0.76639891\n#> physical.activityHigh                -0.38546251\n```\n:::\n\n::: {.cell hash='machinelearning6b_cache/html/lassoauc_1e94f57c90f69896949e8eeaf5aa85ad'}\n\n```{.r .cell-code}\n# AUCs from different folds\nauc.lasso\n#> [1] 0.8396619 0.8129805 0.8465035 0.7896878 0.8342721\n\n# Calibration slope from different folds\ncal.slope.lasso\n#> [1] 1.1287166 0.9985467 1.1224240 0.8934633 1.0131154\n\n# Brier score from different folds\nbrier.lasso\n#> [1] 0.08524781 0.08476661 0.08666820 0.09071329 0.08911735\n```\n:::\n\n\nNow we will average out the model performance measures:\n\n\n::: {.cell hash='machinelearning6b_cache/html/lassoaucmean_71f1b51295b1cb1a219f1384704da4f4'}\n\n```{.r .cell-code}\n# Average AUC\nmean(auc.lasso)\n#> [1] 0.8246212\n\n# Average calibration slope\nmean(cal.slope.lasso)\n#> [1] 1.031253\n\n# Average Brier score\nmean(brier.lasso)\n#> [1] 0.08730265\n```\n:::\n\n\nAlthough the authors used multiple imputation, our AUC from the LASSO model with complete case data analysis is not that different. Note: the authors reported the AUC values in Table 2.\n\n### Random forest for surveys\n\nNow, we will fit the random forest model for predicting binary HICP with the listed predictors. Here are the steps for fitting the model with 5-fold CV:\n\n-   For fold 1, folds 2-5 is the training set and fold 1 is the test set\n-   Fit random forest model on the training set to find the value of the hyperparameters (number of trees, number of predictors to split at in each node, and minimal node size to split at) that gives minimum prediction error. Incorporate sampling weights in the model to account for survey design.\n-   Grid-search with out-of-sample error approach is widely used in the literature. In this approach, we create a data frame from all combinations of the hyperparameters and check which combination gives the lowest out-of-sample error.\n-   Fit the random forest model on the training with the selected hyperparameters from the previous step. Incorporate sampling weights in the model to account for survey design.\n-   Calculate predictive performance (e.g., AUC) on the test set\n-   Repeat the analysis for all folds.\n\n#### Folds\n\n\n::: {.cell hash='machinelearning6b_cache/html/foldsrf_e7ec60debe6ae42b2952a0e9eb6c4982'}\n\n```{.r .cell-code}\nk <- 5\ntable(nfolds)\n#> nfolds\n#>    1    2    3    4    5 \n#> 1451 1457 1496 1468 1408\n```\n:::\n\n\n#### Formula\n\n\n::: {.cell hash='machinelearning6b_cache/html/formularf_f7c30fcfdfab79df0788db0599868ea4'}\n\n```{.r .cell-code}\nFormula\n#> HICP ~ sex + hhsize + born + marital + region + race + education + \n#>     employment.status + poverty.status + veteran + insurance + \n#>     sex.orientation + worried.money + good.neighborhood + psy.symptom + \n#>     visit.ED + surgery + dr.visit + cancer + asthma + htn + liver.disease + \n#>     diabetes + ulcer + stroke + emphysema + copd + high.cholesterol + \n#>     coronary.heart.disease + angina + heart.attack + heart.disease + \n#>     arthritis + crohns.disease + place.routine.care + trouble.asleep + \n#>     obese + current.smoker + heavy.drinker + hospitalization + \n#>     better.health.status + physical.activity\n```\n:::\n\n\n#### 5-fold CV random forest\n\n\n::: {.cell hash='machinelearning6b_cache/html/rffit_488e76d228cadde7888205af1119e373'}\n\n```{.r .cell-code}\nfit.rf <- list(NULL)\nauc.rf <- NULL\ncal.slope.rf <- brier.rf <- NULL\nfor (fold in 1:k) {\n  # Training data\n  dat.train <- dat.complete[nfolds != fold, ]\n  \n  # Test data\n  dat.test <- dat.complete[nfolds == fold, ]\n  \n  # Tuning the hyperparameters \n  ## Grid with 1000 models - huge time consuming\n  #grid.search <- expand.grid(mtry = 1:10, node.size = 1:10, \n  #                          num.trees = seq(50,500,50), \n  #                           OOB_RMSE = 0)\n  \n  ## Grid with 36 models as an exercise\n  grid.search <- expand.grid(\n    mtry = 5:7, \n    node.size = 1:3, \n    num.trees = seq(200,500,100),\n    OOB_RMSE = 0) \n  \n  ## Model with grids \n  for(ii in 1:nrow(grid.search)) {\n    # Model on training set with grid\n    fit.rf.tune <- ranger(\n      formula = Formula,\n      data = dat.train, \n      num.trees = grid.search$num.trees[ii],\n      mtry = grid.search$mtry[ii], \n      min.node.size = grid.search$node.size[ii],\n      importance = 'impurity', \n      case.weights = dat.train$wgt)\n    \n    # Add Out-of-bag (OOB) error to grid\n    grid.search$OOB_RMSE[ii] <- \n      sqrt(fit.rf.tune$prediction.error)\n  }\n  # Position of the tuned hyperparameters\n  position <- which.min(grid.search$OOB_RMSE)\n  \n  # Fit the model on the training set with tuned hyperparameters\n  fit.rf[[fold]] <- ranger(\n    formula = Formula,\n    data = dat.train, \n    case.weights = dat.train$wgt, \n    probability = T,\n    num.trees = grid.search$num.trees[position],\n    min.node.size = grid.search$node.size[position], \n    mtry = grid.search$mtry[position], \n    importance = 'impurity')\n  \n  # Prediction on the test set\n  dat.test$pred.rf <- predict(\n    fit.rf[[fold]], \n    data = dat.test)$predictions[,2]\n  \n  # AUC on the test set with sampling weights\n  auc.rf[fold] <- WeightedAUC(\n    WeightedROC(dat.test$pred.rf, \n                dat.test$HICP, \n                weight = dat.test$wgt))\n  \n  # Weighted calibration slope\n  dat.test$pred.rf[dat.test$pred.rf == 0] <- 0.00001\n  mod.cal <- glm(HICP ~ Logit(dat.test$pred.rf), \n                 data = dat.test, \n                 family = binomial, \n                 weights = wgt)\n  cal.slope.rf[fold] <- summary(mod.cal)$coef[2,1]\n  \n  # Weighted Brier Score\n  brier.rf[fold] <- mean(brierscore(\n    HICP ~ dat.test$pred.rf, \n    data = dat.test,\n    wt = dat.test$wgt))\n}\n```\n:::\n\n\n#### Model performance\n\nLet's check how prediction worked.\n\n\n::: {.cell hash='machinelearning6b_cache/html/rffit2_2d628014cd92229687bf08a9b4effb4b'}\n\n```{.r .cell-code}\n# Fitted random forest models\nfit.rf[[1]]\n#> Ranger result\n#> \n#> Call:\n#>  ranger(formula = Formula, data = dat.train, case.weights = dat.train$wgt,      probability = T, num.trees = grid.search$num.trees[position],      min.node.size = grid.search$node.size[position], mtry = grid.search$mtry[position],      importance = \"impurity\") \n#> \n#> Type:                             Probability estimation \n#> Number of trees:                  500 \n#> Sample size:                      5829 \n#> Number of independent variables:  42 \n#> Mtry:                             5 \n#> Target node size:                 3 \n#> Variable importance mode:         impurity \n#> Splitrule:                        gini \n#> OOB prediction error (Brier s.):  0.0899798\nfit.rf[[2]]\n#> Ranger result\n#> \n#> Call:\n#>  ranger(formula = Formula, data = dat.train, case.weights = dat.train$wgt,      probability = T, num.trees = grid.search$num.trees[position],      min.node.size = grid.search$node.size[position], mtry = grid.search$mtry[position],      importance = \"impurity\") \n#> \n#> Type:                             Probability estimation \n#> Number of trees:                  400 \n#> Sample size:                      5823 \n#> Number of independent variables:  42 \n#> Mtry:                             5 \n#> Target node size:                 2 \n#> Variable importance mode:         impurity \n#> Splitrule:                        gini \n#> OOB prediction error (Brier s.):  0.0899217\nfit.rf[[3]]\n#> Ranger result\n#> \n#> Call:\n#>  ranger(formula = Formula, data = dat.train, case.weights = dat.train$wgt,      probability = T, num.trees = grid.search$num.trees[position],      min.node.size = grid.search$node.size[position], mtry = grid.search$mtry[position],      importance = \"impurity\") \n#> \n#> Type:                             Probability estimation \n#> Number of trees:                  500 \n#> Sample size:                      5784 \n#> Number of independent variables:  42 \n#> Mtry:                             5 \n#> Target node size:                 3 \n#> Variable importance mode:         impurity \n#> Splitrule:                        gini \n#> OOB prediction error (Brier s.):  0.08972587\nfit.rf[[4]]\n#> Ranger result\n#> \n#> Call:\n#>  ranger(formula = Formula, data = dat.train, case.weights = dat.train$wgt,      probability = T, num.trees = grid.search$num.trees[position],      min.node.size = grid.search$node.size[position], mtry = grid.search$mtry[position],      importance = \"impurity\") \n#> \n#> Type:                             Probability estimation \n#> Number of trees:                  400 \n#> Sample size:                      5812 \n#> Number of independent variables:  42 \n#> Mtry:                             5 \n#> Target node size:                 3 \n#> Variable importance mode:         impurity \n#> Splitrule:                        gini \n#> OOB prediction error (Brier s.):  0.08934626\nfit.rf[[5]]\n#> Ranger result\n#> \n#> Call:\n#>  ranger(formula = Formula, data = dat.train, case.weights = dat.train$wgt,      probability = T, num.trees = grid.search$num.trees[position],      min.node.size = grid.search$node.size[position], mtry = grid.search$mtry[position],      importance = \"impurity\") \n#> \n#> Type:                             Probability estimation \n#> Number of trees:                  400 \n#> Sample size:                      5872 \n#> Number of independent variables:  42 \n#> Mtry:                             5 \n#> Target node size:                 3 \n#> Variable importance mode:         impurity \n#> Splitrule:                        gini \n#> OOB prediction error (Brier s.):  0.08929408\n```\n:::\n\n::: {.cell hash='machinelearning6b_cache/html/rfauc_623bb039748327fb326c80d928c330b8'}\n\n```{.r .cell-code}\n# AUCs from different folds\nauc.rf\n#> [1] 0.8393204 0.7905715 0.8244523 0.7811141 0.8301950\n\n# Calibration slope from different folds\ncal.slope.rf\n#> [1] 1.2842866 0.9933553 1.1486583 0.9134864 1.2263184\n\n# Brier score from different folds\nbrier.rf\n#> [1] 0.08745016 0.08881079 0.08913696 0.09163393 0.08895764\n```\n:::\n\n\nNow we will average out the model performance measures:\n\n\n::: {.cell hash='machinelearning6b_cache/html/rfaucmean_6bf63ea3856948e4a0b68b4682caf774'}\n\n```{.r .cell-code}\n# Average AUC\nmean(auc.rf)\n#> [1] 0.8131307\n\n# Average calibration slope\nmean(cal.slope.rf)\n#> [1] 1.113221\n\n# Average Brier score\nmean(brier.rf)\n#> [1] 0.0891979\n```\n:::\n\n\nThis AUC from random forest is approximately the same as obtained from the LASSO model.\n\n#### Variable importance\n\nOne nice feature of random forest is that we can rank the variables and generate a variable importance plot.\n\n\n::: {.cell hash='machinelearning6b_cache/html/vim_e3a7ac9dcfcf650682d744f440f0482d'}\n\n```{.r .cell-code}\n# Fold 1\nggplot(\n  enframe(fit.rf[[1]]$variable.importance, \n          name = \"variable\", \n          value = \"importance\"),\n  aes(x = reorder(variable, importance), \n      y = importance, fill = importance)) +\n  geom_bar(stat = \"identity\", \n           position = \"dodge\") +\n  coord_flip() +\n  ylab(\"Variable Importance\") +\n  xlab(\"\") + \n  ggtitle(\"\") +\n  guides(fill = \"none\") +\n  scale_fill_gradient(low = \"grey\", \n                      high = \"grey10\") + \n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](machinelearning6b_files/figure-html/vim-1.png){width=672}\n:::\n\n```{.r .cell-code}\n\n# Fold 5\nggplot(\n  enframe(fit.rf[[5]]$variable.importance,\n          name = \"variable\", \n          value = \"importance\"),\n  aes(x = reorder(variable, importance), \n      y = importance, fill = importance)) +\n  geom_bar(stat = \"identity\", \n           position = \"dodge\") +\n  coord_flip() +\n  ylab(\"Variable Importance\") +\n  xlab(\"\") + \n  ggtitle(\"\") +\n  guides(fill = \"none\") +\n  scale_fill_gradient(low = \"grey\", \n                      high = \"grey10\") + \n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](machinelearning6b_files/figure-html/vim-2.png){width=672}\n:::\n:::\n\n\n### References\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\r\n<script src=\"site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}